### ISSUE TITLE
Uso di AssignedDataset e Source in importazione.

### ISSUE THREAD

**Issue by spanezz** [ARPA-SIMC/arkimet#10]
Quando si importano dati in arkimet, in output vengono generati i metadati di quello che si è importato.

Al momento, tra quel metadati c'è un campo AssignedDataset che contiene il nome del database dove è stato importato il dato, e il Source rimane il source originale del file da importare.

Vorrei cambiare la cosa facendo sparire AssignedDataset, e settando a Source la posizione che il dato ora ha nel dataset di destinazione.

Ci sono controindicazioni?

(assegno per ora @edigiacomo, ma vorrei assegnare @edigiacomo e @brancomat)

**Comment by edigiacomo** [comment]
Molto probabilmente ho capito male, ma mi pare che sia già qualcosa del genere:

```
arkimet@arkimet:~ arki-query --dump 'reftime:=today' /arkivio/arkimet/dataset/lmsmr4x52
...
Source: BLOB(grib1,/arkivio/arkimet/dataset/lmsmr4x52/2015/12-18.grib1:528503712+186224)
Assigneddataset: lmsmr4x52 as 14720210 imported on 2015-12-18T07:37:39Z
Note: [2015-12-18T03:30:45Z]Scanned from /arkivio/arkimet/scambio/tmp/nplfff01120000.201512180000.GRIB:10428544+186224
...
```
In `Source` mi pare ci sia già la posizione che il dato ora ha nel dataset di destinazione.

L'informazione del file originale da cui è stato importato può risultare utile (e se la lasci in `Note` va benissimo), anche se lo abbiamo usato poche volte.

**Comment by brancomat** [comment]
Sì, vista la situazione descritta da Emanuele non mi pare un problema perdere l'AssignedDataset, anch'io però voterei per tenere le info del campo Note

**Comment by spanezz** [comment]
Done in a0559f30533b48a60b185e2706e11d872abc93b8
