### ISSUE TITLE
arki-check block dispatching for the whole iseg dataset

### ISSUE THREAD

**Issue by edigiacomo** [ARPA-SIMC/arkimet#108]
When running `arki-check -f` (or `arki-check -f -r`), `arki-scan` is blocked until the check is completed: it seems that the whole dataset is locked. I thought that write operations on dataset `iseg` locked the single segment, am I missing something?

Related issue #60.

**Comment by spanezz** [comment]
Write operations should only block the single segment, that was the reason behind designing iseg. This is clearly a bug, I'll look into why this happens.
