### ISSUE TITLE
arki-scan --dispatch performances due to sync

### ISSUE THREAD

**Issue by dcesari** [ARPA-SIMC/arkimet#110]
This is a known problem: when importing a lot of grib messages with `arki-scan --dispatch` most of the time is spent in syncing the fs rather than in real I/O operations, making it unsuitable when high throughput is required; paradoxically performance is better when the archive is on nfs, probably because on nfs a sync is only a sync in local cache, not on the remote hardware. A workaround is to use [eatmydata](https://www.flamingspork.com/projects/libeatmydata/), in that case a performance gain from 3x to 30x is noticed, depending on the fs type, but that's probably unsafe.
In principle (at least for me) it is acceptable to have nothing imported and unindexed garbage at the end of a ds file in case of an interrupted arki-scan (i.e. update the index db(s) in a single transaction only once at the end of a single file imported), in exchange for better performance, provided that the sqlite index is not corrupted, of course.
Is any improvement in this direction possible?
I can provide figures and data for testing if needed.

**Comment by spanezz** [comment]
It would be interesting to measure if the syncing delays are only significant when saving data to segments, or also when committing transactions to sqlite databases: eatmydata tends to also make sqlite much, much faster.

Having garbage at the end of a segment and a correct index does however require a sync on the segment's data, because otherwise I risk committing the transaction stating in the index that data is there, while the data isn't there and doesn't get there because of a crash. Currently the policy is to fdatasync the data and then commit the sqlite transaction, so that a crash after the fdatasync simply results in garbage at the end of a segment, which goes away at the next repack.

I would be interested in having details of what kind of import operations you are measuring: for example, are you importing more like many data items into a single dataset, or more like one data item per dataset for a lot of datasets?

**Comment by dcesari** [comment]
Thanks for the explanation. The typical import pattern is one file with many (100's) grib messages which are all dispatched to the same dataset, I think this is the typical use also for @brancomat , thus the idea of syncing once at the end of the arki-scan.
If I well understand the system there could be 2 strategies, 1. if a message is going to be dispatched to a different ds wrt the previous message then sync the segment and commit the db transactions before going on with the current message, 2. remember all the dataset affected and sync and commit all at the end. Strategy 1. is probably simpler and could be acceptable for our use.

**Comment by spanezz** [comment]
I implemented an optimization for this case for the iseg datasets. If you have iseg datasets to try, can you tell me if it improves things?

**Comment by spanezz** [comment]
Now it's also implemented for ondisk2 datasets, since the code in the end is rather similar

**Comment by dcesari** [comment]
I tested dispatching a big grib file on an iseg DS on my local hard disk and the results are very encouraging, the tests shown are respectively: installed arkimet w/o eatmydata, installed arkimet with eatmydata, master branch w/o eatmydata, master branch with eatmydata:
```
[dcesari@malina arki-scan]$ grib_count to_assim.grib
764
[dcesari@malina arki-scan]$ ls -l to_assim.grib
-rw-r--r-- 1 dcesari dcesari 617274444 31 gen 12.04 to_assim.grib
[dcesari@malina arki-scan]$ time arki-scan --dispatch=arki.1/config to_assim.grib >/dev/null

real	1m19.244s
user	0m1.106s
sys	0m1.530s
[dcesari@malina arki-scan]$ time eatmydata arki-scan --dispatch=arki.2/config to_assim.grib >/dev/null

real	0m20.580s
user	0m0.998s
sys	0m1.239s
[dcesari@malina arki-scan]$ time /scratch/dcesari/github/arkimet/run-local /scratch/dcesari/github/arkimet/src/arki-scan --dispatch=arki.3/config to_assim.grib >/dev/null

real	0m23.162s
user	0m1.139s
sys	0m1.798s
[dcesari@malina arki-scan]$ time eatmydata /scratch/dcesari/github/arkimet/run-local /scratch/dcesari/github/arkimet/src/arki-scan --dispatch=arki.4/config to_assim.grib >/dev/null

real	0m24.837s
user	0m1.150s
sys	0m1.846s
[dcesari@malina arki-scan]$ 
```

So the performances are almost the same as those obtained with eatmydata (and hd makes much less noise than before :-) ), thanks a lot!!!

**Comment by spanezz** [comment]
Excellent. I have now implemented optimized batch import also for simple datasets, which means all datasets are covered. Some more optimizations are still possible, like sorting the elements of the batch by reftime before importing to reduce the need of repacking later, but I think I can close the issue for now
