### ISSUE TITLE
[v1.5] tests failing on `ventiquattro`

### ISSUE THREAD

**Issue by brancomat** [ARPA-SIMC/arkimet#112]
on `ventiquattro`:
```
scan/grib-test.cc: In lambda function:
scan/grib-test.cc:379:50: error: no matching function for call to 'arki::scan::Grib::open(const char [31])'
     scanner.open("inbound/calmety_20110215.grib2");
                                                  ^
```
full log:
[github-rpmbuild.log](https://github.com/ARPA-SIMC/arkimet/files/1506777/github-rpmbuild.log)

**Comment by spanezz** [comment]
I pushed a fix that makes it compile, but some tests still fail

**Comment by brancomat** [comment]
Ok, if you don't need log/feedback on the other failing tests please close this bug when all tests pass. I'll try to edit the issue to reflect this.

**Comment by spanezz** [comment]
This morning tests are passing on ventiquattro, with no changes needed. I launched tests on venti, it will take a while
