### ISSUE TITLE
arki-query e redirect HTTP

### ISSUE THREAD

**Issue by edigiacomo** [ARPA-SIMC/arkimet#114]
Il client HTTP non segue una redirezione da parte del server (HTTP status 3xx). La possibilità di supportare le redirezioni era stata discussa tempo fa a voce e poi lasciata cadere.

La cosa è tornata fuori in questi giorni parlando con @brancomat  e @dcesari, perché si parlava di mettere in piedi un server centralizzato da interrogare che potrebbe rispondere redirezionando la `arki-query` al giusto `arki-server` e mettendo quindi i due in comunicazione diretta.

Prima ancora che implementare il supporto della redirezione, mi chiedevo se non ci fossero delle controindicazioni in particolare nella soluzione, in generale nell'implementazione stessa e se non ci fossero soluzioni alternative e più furbe.

O forse varrebbe la pena, prima, esplicitare bene tutte le funzionalità che ci aspettiamo da un 'arki-server` centralizzato e poi affrontare questa questione?

**Comment by brancomat** [comment]
La premessa è che stiamo andando verso una situazione a più arki-server su più datacenter diversi e soprattutto in una prima fase è possibile che i dataset si spostino con una certa frequenza. Si poneva il problema di creare una sorta di front-end/smistatore con la visibilità completa di tutti i dataset per non doversi preoccupare di dove sta il dataset X.

Al momento la possibilità di configurare dataset remoti è comoda ma il traffico passa comunque dall'arki-server a cui si punta per la query aggiungendo overhead di rete inutile.

**Comment by edigiacomo** [comment]
Si potrebbe usare un web server (Apache, nginx) che, sulla base dell'IP del client e del dataset richiesto, decida se rispondere con HTTP 302 e redirezionare ad un arki-server oppure, se il client non ha visibilità dell'arki-server, fare da reverse proxy.

Il secondo scenario lo stiamo già implementando con un arki-server che fa da proxy (ma potrebbe essere un web server), mentre per il primo basterebbe - credo - permettere ai client arkimet di seguire il redirect.

**Comment by spanezz** [comment]
Non vedo problemi nell'implementare la gestione del redirect in arki-query (se non funziona già di suo), e documentarla. L'idea di un server http, pure statico, che faccia da punto di accesso unico e poi faccia dei redirect ai posti giusti, mi sembra sensata.

C'è una finezza da discutere: il server smistatore/redirectante, potrebbe essere trattato come un server solo, o come piú server se ridirige in posti diversi. Nel primo caso, forse basta dire a libcurl "segui i redirect", nel secondo caso serve una cosa un po' piú furba, che prima faccia un ping al server per ogni dataset, segua tutte le ridirezioni, e poi gestisca i link risultanti.

Questa finezza è relativa al fatto che ad arki-query, quando si fanno query su piú dataset, interessa sapere quali sono sullo stesso server e quali no, perché server diversi potrebbero avere alias diversi e catene di postprocessazione diverse, per cui cerca di tenerne conto: per esempio, risolve la query usando gli alias di ogni server, e procede solo se la query risultante in ogni server è la stessa, altrimenti segnala che quella query viene interpretata da server diversi in modo diverso.

È una finezza, perché non mi sembra che si facciano spesso query su piú dataset, però per evitare sorprese, mi fa piacere tenerne conto.

Opzione 1: si considera tutto un server unico, e se facendo query multidataset escono dati strani, si sta piú attenti la prossima volta

Opzione 2: risolvo i redirect in arki-query/arki-mergeconf, e procedo come se si stessero facendo query ai server finali

Mi piace abbastanza la seconda: ha senso per voi?

**Comment by edigiacomo** [comment]
Anche a me piace la seconda.

Il giorno gio 23 mag 2019 alle ore 16:14 Enrico Zini <
notifications@github.com> ha scritto:

**Comment by brancomat** [comment]
+1 per la seconda

**Comment by spanezz** [comment]
Guardando il codice, il compito si semplifica perché viene già contattato il server remoto per avere la configurazione del dataset, e mi basta seguire i redirect in quel punto.

Il problema piú grosso è forse scrivere unit test per il codice che gestisce i redirect.

**Comment by spanezz** [comment]
Come non detto, la configurazione può puntare a dataset remoti che fanno poi redirect ad altri punti.

Domanda: potrebbe bastare, invece di fare dei redirect con apache, servire un file statico `/config` con l'elenco dei dataset remote che puntano ai server finali?

Questo dovrebbe pure già funzionare.

**Comment by spanezz** [comment]
Per fare un esempio, il server di smistamento dovrebbe solo servire un file statico `/config` del tipo:
```
[dataset1]
type = remote
path = http://server1/dataset/dataset1
            
[dataset2]
type = remote
path = http://server1/dataset/dataset2
            
[dataset3]
type = remote
path = http://server2/examplepath/dataset/dataset

**Comment by spanezz** [comment]
The work I did trying to add more testing for redirection cases led to some code cleanup that I merged into master.

If the current situation is sufficient/works for you, you can close the bug.

**Comment by brancomat** [comment]
Thanks, I changed the label to review, I'll close the bug as soon we manage to test the solution suggested.

**Comment by edigiacomo** [comment]
> Per fare un esempio, il server di smistamento dovrebbe solo servire un file statico `/config` del tipo:

@spanezz Non dovrebbero essere N + 1 file `config` statici, uno per dataset più un `config` che li contiene tutti? Oppure `arki-query` interroga sempre quest'ultimo, cioé quello della radice, anche quando richiede uno specifico dataset?

**Comment by brancomat** [comment]
> Non dovrebbero essere N + 1 file `config` statici, uno per dataset più un `config` che li contiene tutti?

Empiricamente confermo, non sembra possibile puntare ad un singolo dataset con il `config` unico.

Non è che sia un problemissimo visto che comunque per automatizzare la cosa va parsato in qualche modo l'output di `arki-mergeconf`, a quel punto gli si potrebbe comunque far creare tutto l'albero.

Se proprio ci punge vaghezza di enhancement estremo si potrebbe anche pensare ad una qualche opzione di `arki-mergeconf` che faccia magie tipo:
```
arki-mergeconf http://arkiserver1:8090/ http://arkiserver2:8090/ http://arkiserver3:8090 --static-web-tree=/some/path/
```
ma tutto sommato non mi fa impazzire (snatura un po' troppo `arki-mergeconf`) e lascerei la cosa a script esterno

**Comment by spanezz** [comment]
@edigiacomo hai ragione, se si interroga un singolo dataset viene chiesto [/dataset/<name>/config](https://github.com/ARPA-SIMC/arkimet/blob/master/doc/web-api.md#datasetnamesummaryshortqueryquerystylestyle-endpointarkidatasetsummaryshort)

Inoltre, al momento non c'è codice per seguire esplicitamente le redirezioni, per cui anche se il primo passo funzionerebbe (chiedo la config al server A, che mi restituisce una configurazione con un path che punta al server B, faccio la query al server B), se il server B cerca di nuovo di redirigere, quella redirezione non verrebbe seguita.

Direi che ce ne sia abbastanza per rivedere il comportamento dei dataset remote. Alcune possibilità, non mutuamente esclusive:

1. non chiedere la configurazione a `/dataset/<name>/config` ma sempre a `/config`
2. distinguere path relativi ("su questo server") da path assoluti (possibilmente su un altro server, a cui chiedere di nuovo `/config`, e fare detect di redirect loop, e di server che puntano a se stessi per compatibilità con l'esistente)
3. tornare all'idea di fare redirect con apache, e assicurarmi che i redirect HTTP vengano seguiti

**Comment by brancomat** [comment]
> 1. non chiedere la configurazione a `/dataset/<name>/config` ma sempre a `/config`

questo mi pare crei un paio di problemi: se il `/config` contiene più dataset (di cui non ho altre informazioni se non il fatto che sono remote) l'arkiquery viene rimbalzata a tutti i dataset remoti, e se sono interessato ad un solo dataset con parametri di query potenzialmente comuni ad altri dataset mi tornano dati a cui non sono interessato.

Per non perderci troppo riprendo il secondo commento con l'effettiva esigenza:

> Si poneva il problema di creare una sorta di front-end/smistatore con la visibilità completa di tutti i dataset per non doversi preoccupare di dove sta il dataset X.

Quindi: _un_ solo redirect (dallo smistatore all'arki-server interessato) e necessità di retrocompatibilità (gli script con query che puntano a `http://arkimet:8090/dataset/qualcosa` se sposto l'alias dns `arkimet` allo smistatore non se ne devono accorgere) 

In questa fase, correggetemi se sbaglio, basterebbe uno script che prepari (partendo da un mergeconf dei vari arkiserver) una serie di file da dare in pasto ad un webserver con un `/config` comune con l'elenco di tutti i dataset ed una serie di sottodir (ad es. `/dataset/qualcosa/config` con banalmente ad es.:

```
[qualcosa]
type = remote
path = http://arkiqualcosa/dataset/qualcosa
```
(poi nel caso specifico per una retrocompatiblità completa si fa rispondere il webserver sulla `8090`)

**Comment by spanezz** [comment]
Per quello che vedo, per un solo livello di redirect dovrebbe bastare uno script del genere. Ve ne faccio uno al volo da provare?

**Comment by brancomat** [comment]
Ok, grazie!

**Comment by spanezz** [comment]
Eccolo: 
[mock-arki-server.zip](https://github.com/ARPA-SIMC/arkimet/files/3734088/mock-arki-server.zip)

**Comment by brancomat** [comment]
Grazie, gli serve arkimet versione `issue177` ma funziona perfettamente.
Devo ancora testare in maniera più approfondita l'arki-smistatore risultante quindi lascio l'issue in review assegnata a noi.

**Comment by brancomat** [comment]
Lo script salvo una piccola correzione sull'header dei config singoli funziona, in accordo con @edigiacomo si pensava di integrarlo in arkimet e arricchirlo un po', apro issue separata
