### ISSUE TITLE
arki-query from metadata file fails

### ISSUE THREAD

**Issue by brancomat** [ARPA-SIMC/arkimet#117]
found by @dcesari 
quick recap by commands:

```
$ arki-scan grib:/scratch/dcesari/github/libsim/data/t_p.grb > t_p.metadata

$ arki-scan --yaml '' t_p.metadata
#  this works (only if the file is called '.metadata'
# or if we have a `metadata:` before the file name)

$ arki-query --data -o ppp '' t_p.metadata
cannot retrieve data: BLOB source has no reader associated
```
The last command used to work on older versions of arkimet. Right now we're unsure if we still need it (the use case being: speeding multiple query on huge grib files) but the error message is kind of confusing.

**Comment by spanezz** [comment]
I assume it's `arki-scan --yaml t_p.metadata`?  (Without `''` for `arki-scan`)

**Comment by spanezz** [comment]
You can use `metadata` or `arkimet`. Supported names are here:

https://github.com/ARPA-SIMC/arkimet/blob/master/arki/utils/files.cc#L69
