### ISSUE TITLE
Add minimal python3 bindings

### ISSUE THREAD

**Issue by spanezz** [ARPA-SIMC/arkimet#12]
I intend to implement minimal python3 bindings, functional enough to replace arki-server with a python version that uses python's HTTP implementation, and to do away with the internal http server in arkimet.

There is no need at first to access the contents of a Metadata from python, and there can just be the binding of a dataset::Reader with query methods that stream output to an integer file descriptor.

Further steps from there can be to expand the bindings to replace one at a time all the other command line tools.

**Comment by spanezz** [comment]
Done in f5425fd90557afb1c9cacc7ab4cebc4ba2dbf2e0, in branch `python`.

Testing on venti failed because of a missing dependency on the python3 version of werkzeug (python3-werkzeug in debian). The package should be available, because it is a dependency of the popular web framework Flask.

The nose2 module for python3 is also needed for testing (python3-nose2 in Debian).

Daniele, can you install these packages on Venti?

**Comment by edigiacomo** [comment]
`python3-flask-0.10.1-3` installed.

**Comment by spanezz** [comment]
Is nose2 available?

**Comment by spanezz** [comment]
In the meantime, all tests of the new python-based arki-server pass on venti \o/

**Comment by spanezz** [comment]
Ok, this is ready for a test deployment.

**Comment by brancomat** [comment]
I'm late to the party and I'm not sure abut the missing dependency situation, right now we can choose between available modules from fedora official repo (recommended) or manual pip install.
Here's the "venti" situation:
```
[root@venti ~]# rpm -q python3-nose
python3-nose-1.3.0-1.fc20.noarch
[root@venti ~]# rpm -q python3-werkzeug
python3-werkzeug-0.9.4-1.fc20.noarch
```
so no nose2 on f20, is this ok?

About test deployment: further updates coming soon(ish)

**Comment by edigiacomo** [comment]
@spanezz this issue can be closed?

**Comment by spanezz** [comment]
I was leaving it open until I heard someone saying "it works".

Since that has not come yet, we can close this now, and if at some point it doesn't work, a new bug can be created about it not working.
