### ISSUE TITLE
Error in scanning grib2 with different time units

### ISSUE THREAD

**Issue by dcesari** [ARPA-SIMC/arkimet#120]
The attached unlucky [grib2 message](https://github.com/ARPA-SIMC/arkimet/files/1667734/oddunits.zip), generated by a third-party application, has a different unit for forecastTime and lengthOfTimeRange (3 hours and 1440 minutes respectively) and it is erroneously scanned by arki-scan:
```
arki-scan --yaml oddunits.grib
...
Timerange: Timedef(1443h, 4, 1440m)
...
```
because in [this line](https://github.com/ARPA-SIMC/arkimet/blob/master/conf/scan-grib2/01-common.lua#L57) forecast time and time range are added regardless of their unit. Can anything be done to improve the situation?
We could either convert to the shortest of the two units or convert both to seconds, sum and go back to the most reasonable unit/shortest unit. Since each successive time unit in grib standard is an integer multiple of the previous (neglecting for the moment months, years and longer variable-length units), I think the first algorithm would be better, since it would guarantee metadata homogeneity within an homogeneous dataset. Around [these lines](https://github.com/ARPA-SIMC/libsim/blob/master/volgrid6d/gridinfo_class.F90#L1598) you can get some inspiration.

**Comment by spanezz** [comment]
I'm adding it to the test suite: what is the expected time range value for this grib?

**Comment by dcesari** [comment]
```
18        indicatorOfUnitOfTimeRange = 1 [Hour  (grib2/tables/11/4.4.table) ]
19-22     forecastTime = 3
62        indicatorOfUnitForTimeRange = 0 [Minute  (grib2/tables/11/4.4.table) ]
63-66     lengthOfTimeRange = 1440

```
so one of:
 * Timerange: Timedef(27h, 4, 24h)
 * Timerange: Timedef(1620m, 4, 1440m)
or a mix of the two.

BTW will `Timerange: Timedef(1620m, 4, 1440m)` match a query as `Timedef,,4,24h` or `Timedef,27h,4,`? if yes, then they are all equivalent, if not, then it would be preferable to privilege hour units in metadata when possible, but that's an extra.

**Comment by spanezz** [comment]
I confirm that match is done independently of units. I'll try to see if I can privilege the biggest unit that doesn't loose precision
