### ISSUE TITLE
Timerange for BUFR "generic"

### ISSUE THREAD

**Issue by edigiacomo** [ARPA-SIMC/arkimet#125]
`conf/scan-bufr/generic.lua` doesn't handle very well BUFR "generic" with forecast data, because the timerange is ignored (and the `Reftime` is the verification time).

It's ok to add the `timerange` metadata to observed (`p1=0`) data too? This means that some datasets should be rescanned.

Now:

```
$ arki-scan --dump ~/an.bufr 
Source: BLOB(bufr,/autofs/nethomes/edigiacomo/an.bufr:0+206)
Origin: BUFR(200, 000)
Product: BUFR(255, 255, 000, t=locali)
Reftime: 2018-03-01T00:00:00Z
Area: GRIB(lat=4460016, lon=1207738)
```

After:

```
Source: BLOB(bufr,/autofs/nethomes/edigiacomo/an.bufr:0+206)
Origin: BUFR(200, 000)
Product: BUFR(255, 255, 000, t=locali)
Timerange: Timedef(0s)
Reftime: 2018-03-01T00:00:00Z
Area: GRIB(lat=4460016, lon=1207738)
```

The forecast BUFR will have the emission time as `Reftime` metadata.

Now:

```
Source: BLOB(bufr,/autofs/nethomes/edigiacomo/fc.bufr:8520+120)
Origin: BUFR(200, 000)
Product: BUFR(255, 255, 000, t=generic)
Reftime: 2018-03-03T23:00:00Z
Area: GRIB(lat=4311660, lon=1176985)
```

After:

```
Source: BLOB(bufr,/autofs/nethomes/edigiacomo/fc.bufr:8520+120)
Origin: BUFR(200, 000)
Product: BUFR(255, 255, 000, t=generic)
Timerange: Timedef(71h)
Reftime: 2018-03-01T00:00:00Z
Area: GRIB(lat=4311660, lon=1176985)
```

**Comment by dcesari** [comment]
For me it would be great for handling forecast archives, I only see some possible inconsistency with the dballe way of thinking where reference time coincides with verification time, a kind of original sin in our construction, but the advantages compensate the disadvantages. If this shift of reftime may have too much side-effects we could limit, if possible, to a specific network/rep-memo, e.g. "forecast".

**Comment by edigiacomo** [comment]
> we could limit, if possible, to a specific network/rep-memo, e.g. "forecast".

Ok for me!

Just a comment:

> I only see some possible inconsistency with the dballe way of thinking where reference time coincides with verification time

For `temp`, `temp_ship` and `pilot` archived in Arkimet the `Timerange` is set (for observations too) and the `Reftime` coincides with emission time for many years already:

```
$ arki-query \
   --data 'reftime:=today 00:00; timerange:Timedef,3h' \
   http://arkimet.metarpa:8090/dataset/lami_ope_temp | \
   dbamsg dump --interpreted | grep '^#' | head -n1
#0[0] temp message, rep_memo: , 44.50000,11.34000, ident: , dt: 2018-03-01T03:00:00, 44 contexts:
```

**Comment by pat1** [comment]
io vorrei capire bene ...

**Comment by pat1** [comment]
ho capito e tutti insieme abbiamo deciso:
il metadato Timerange: Timedef va messo in TUTTI i generici e tolto da TUTTI gli altri (temp,pilot...)
