### ISSUE TITLE
arki-scan and arki-query cannot scan data from stdin

### ISSUE THREAD

**Issue by pat1** [ARPA-SIMC/arkimet#126]
rpm -q arkimet
 arkimet-1.5-2.x86_64

 arki-scan --inline bufr:-
 unknown option --inline

I use it in pipe with arki-xargs
 arki-scan --inline bufr:- | arki-xargs -n 1 toamqp

**Comment by pat1** [comment]
arki-query --inline '' bufr:-
cannot scan -: file does not exist

**Comment by dcesari** [comment]
this may work, but is not the clean solution:
`arki-query --inline '' bufr:/dev/stdin`

**Comment by edigiacomo** [comment]
Sorry Paolo, I never tried with stdin before.

Arkimet should read from stdin, but it's not supported in the implementation (see arki::scan::scan_file, called from `arki::scan::scan`).

> this may work, but is not the clean solution:
> arki-query --inline '' bufr:/dev/stdin

It works! Very nice!

**Comment by pat1** [comment]
Do not work for me:

cat tmp.bufr |arki-query --inline --debug --verbose "" bufr:/dev/stdin 
arkimet 1.5, compiled on Dec 12 2017 16:35:38
Copyright (C) 2007-2010 ARPA Emilia Romagna.
arkimet comes with ABSOLUTELY NO WARRANTY.
This is free software, and you are welcome to redistribute it and/or modify it
under the terms of the GNU General Public License as published by the Free
Software Foundation; either version 2 of the License, or (at your option) any
later version.
Processing /dev/stdin...

**Comment by pat1** [comment]
[tmp.bufr.gz](https://github.com/ARPA-SIMC/arkimet/files/1799244/tmp.bufr.gz)

**Comment by dcesari** [comment]
Hai questo link sul tuo sistema?
```
ls -l /dev/stdin
lrwxrwxrwx 1 root root 15 12 feb 09.50 /dev/stdin -> /proc/self/fd/0
```

**Comment by pat1** [comment]
ls -l /dev/stdin
lrwxrwxrwx 1 root root 15 27 feb 19.43 /dev/stdin -> /proc/self/fd/0

**Comment by pat1** [comment]
the pull request work for me

**Comment by pat1** [comment]
the pull request do not work importing data:
 arki-scan --dispatch=/rmap/arkimet/sample_fixed.conf bufr:tmp.bufr --summary --dump --status --debug --verbose
 arkimet 1.6, compiled on Mar 13 2018 18:19:01
 Copyright (C) 2007-2010 ARPA Emilia Romagna.
 arkimet comes with ABSOLUTELY NO WARRANTY.
 This is free software, and you are welcome to redistribute it and/or modify it
 under the terms of the GNU General Public License as published by the Free
 Software Foundation; either version 2 of the License, or (at your option) any
 later version.
 /tmp/tmp.bufr: everything ok: 1 message imported in 0.047548 seconds
 SummaryItem:
  Origin: BUFR(200, 000)
  Product: BUFR(255, 255, 000, t=fixed)
  Area: GRIB(lat=4449367, lon=1134309)
  Proddef: GRIB(id=pat1)
 SummaryStats:
  Count: 1
  Size: 132
  Reftime: 2018-03-09T11:40:23Z

 cat tmp.bufr |arki-scan --dispatch=/rmap/arkimet/sample_fixed.conf bufr:- --summary --dump --status --debug --verbose
 arkimet 1.6, compiled on Mar 13 2018 18:19:01
 Copyright (C) 2007-2010 ARPA Emilia Romagna.
 arkimet comes with ABSOLUTELY NO WARRANTY.
 This is free software, and you are welcome to redistribute it and/or modify it
 under the terms of the GNU General Public License as published by the Free
 Software Foundation; either version 2 of the License, or (at your option) any
 later version.
 -: serious problems: 0 ok, 0 duplicates, 0 in error dataset, 1 NOT imported in 0.006026 seconds
 SummaryItem:
  Origin: BUFR(200, 000)
  Product: BUFR(255, 255, 000, t=fixed)
  Area: GRIB(lat=4449367, lon=1134309)
  Proddef: GRIB(id=pat1)
 SummaryStats:
  Count: 1
  Size: 132
  Reftime: 2018-03-09T11:40:23Z

**Comment by edigiacomo** [comment]
PR #127 doesn't fix the issue because I didn't notice that, when dispatching, `arki-scan` reads input data in a different way.

**Comment by edigiacomo** [comment]
I have talked with @pat1 and we decided to freeze this issue until we have decided (with @brancomat and @dcesari) what behaviour we need, e.g.

- Enable stdin
- Disable stdin
- Disable stdin for dispatching only
- Other

**Comment by pat1** [comment]
question:
quanto è oneroso implemenatre la gestione di stdin in tutti i tools ?
quanto è oneroso disabilitare in modo esplicito e nella doc lo stdin in tutti i tools (fare riferimento a Emanuele)?

**Comment by spanezz** [comment]
Rather than hard to implement, it may very well be impossible.

When scanning, it is not arkimet reading input data, but the libraries that decode the various data formats, and not all of them support reading from standard input: for example, HDF5.

If for some reason I manage to find a workaround for HDF5, there is no guarantee that in the future we will need a data format for which that workaround will not work.

A possible solution is to write standard input to a temporary file, and import that file.

If you cannot do that because your standard input is a continuous data source, then the actual request is to be able to have an arkimet daemon that does continuous import of all data that gets fed to it at any time. That is an entirely new feature request, and if that is the case, and it is indeed needed, please open a separate issue for it.

**Comment by pat1** [comment]
question:
quanto è oneroso implemenatre la gestione di stdin in tutti i tools per i formati che lo possono implementare (grib/bufr) tornando semplicemente errore per quelli che non lo supportano?
Per l'opzione --dispatch the problem "is not for a continuous data source" ma eventualmente per travasi di volumi dati enormemente grandi.

**Comment by spanezz** [comment]
Implementato in 7a8eeee613ad30a81059a654a7c3e8084cd00498: ora c'è l'opzione `--stdin` che però non funziona con `--dispatch`

**Comment by edigiacomo** [comment]
`arki-query --stdin=FORMAT` (at least from version 1.7-6) ignores the match expression.

```
$ rpm -qi arkimet | head
Name        : arkimet
Version     : 1.7
Release     : 6
Architecture: x86_64
Install Date: Thu 20 Sep 2018 03:59:15 PM CEST
Group       : Applications/Meteo
Size        : 5243994
License     : GPL
Signature   : RSA/SHA1, Tue 18 Sep 2018 04:14:35 PM CEST, Key ID a9137d5448628f8d
Source RPM  : arkimet-1.7-6.src.rpm

$ cat test/data/fixture.vm2 
200707081300,1,227,1.2,,,000000000
200707070000,12,1,800,,,000000000
200710090000,12,2,50,,,000000000

$ arki-query --data 'area:VM2,1' test/data/fixture.vm2
200707081300,1,227,1.2,,,000000000

$ arki-query --data --stdin=vm2 'area:VM2,1'  < test/data/fixture.vm2
200707081300,1,227,1.2,,,000000000
200707070000,12,1,800,,,000000000
200710090000,12,2,50,,,000000000
```

**Comment by spanezz** [comment]
I'm reclosing this bug and opening a new one with an appropriate title
