### ISSUE TITLE
[build with eccodes] import_largefile fails

### ISSUE THREAD

**Issue by brancomat** [ARPA-SIMC/arkimet#128]
We're trying some pseudo-rolling release of all simc software with eccodes instead of grib_api.

Arkimet is built without `--enable-arpae-tests` because eccodes still doesn't have our custom tables.

The CentOs build worked out fine, but Fedora 26 and 27 builds are both failing with the same error (as in: the very same difference in bytes read):

```
arki_report: ..

arki_dataset_writer_ondisk2.import_largefile: St13runtime_error: cannot read 10485760 bytes of grib data from /tmp/tmp.OfVSHmmDp0/testds/2014/12-11.grib/000007.grib:7: only 2170880/10485760 bytes have been read
  dataset-writer-test.cc:119:reader->query_bytes(bq, out)

arki_dataset_writer_simple_plain.import_largefile: St13runtime_error: cannot read 10485760 bytes of grib data from /tmp/tmp.OfVSHmmDp0/testds/2014/12-11.grib/000007.grib:7: only 2215936/10485760 bytes have been read
  dataset-writer-test.cc:119:reader->query_bytes(bq, out)

arki_dataset_writer_simple_sqlite.import_largefile: St13runtime_error: cannot read 10485760 bytes of grib data from /tmp/tmp.OfVSHmmDp0/testds/2014/12-11.grib/000007.grib:7: only 2170880/10485760 bytes have been read
  dataset-writer-test.cc:119:reader->query_bytes(bq, out)

arki_dataset_writer_iseg.import_largefile: St13runtime_error: cannot read 10485760 bytes of grib data from /tmp/tmp.OfVSHmmDp0/testds/2014/12-11.grib/000006.grib:6: only 9850880/10485760 bytes have been read
  dataset-writer-test.cc:119:reader->query_bytes(bq, out)

4/2287 tests failed
Failed with result 1
```

**Comment by spanezz** [comment]
Is there a fedora 26 or 27 machine I can log into, to try to reproduce and debug this?

**Comment by brancomat** [comment]
Ok, this is funny (as in _not_ funny):

- on `sette` the `import_largefile` tests pass
- on copr builds the `import_largefile` tests fails

(btw: both systems apparently are missing `all.odimh5` but that's a separate issue)

since the OS (and the enabled repos) are the same, maybe there's some missing requirements that's already installed on our servers.

**Comment by spanezz** [comment]
can you compare the output of `./configure` from the two systems and see if there are differences?

**Comment by brancomat** [comment]
Apparently they're identical (see attachment)

[build-copr.log](https://github.com/ARPA-SIMC/arkimet/files/1893781/build-copr.log)
[build-sette.log](https://github.com/ARPA-SIMC/arkimet/files/1893783/build-sette.log)

**Comment by brancomat** [comment]
About the `all.odimh5` issue: the cause is the old kernel of CentOS7 (3.10) that doesn't support OFD.

For older kernels all OFD locks related tests should be skipped (apparently all `arki_dataset_concurrent_odim_*read_repack`)

**Comment by spanezz** [comment]
Tests that require OFD locks should also now be skipped since 52abe9065.
