### ISSUE TITLE
tar segments

### ISSUE THREAD

**Issue by spanezz** [ARPA-SIMC/arkimet#131]
@brancomat asked if it is possible to have .tar files instead of directory segments inside archives

**Comment by spanezz** [comment]
Would you like it if when archiving a directory segment, it gets automatically archived as a .tar file?

**Comment by brancomat** [comment]
It's ok for me to be the default (also for @palberoni, I just asked him).

Regarding old archived section: could it be possibile to mantain readability of the old existing dir-based structure? In other words, can the new tar-based daily archive and the old dir-based daily archive coexist? While it's ok to have tar archives from one day forward, re-archiving old (and already backupped) archives would be time consuming.

**Comment by spanezz** [comment]
Yes, I'm thinking of needing a specific `arki-check --tar` to tar existing segments, so if I auto-tar on archival, it would only affect new segments, and the existing segments would remain as they are until manually tarred.

**Comment by spanezz** [comment]
I have implemented `arki-check --tar`. By default it works on all archived segments that are directories, converting them into `.tar` files. You can use `--online`, `--offline`, and `--filter` to choose which segments it should operate on.

**Comment by spanezz** [comment]
For auto-archiving using `.tar` files, I have a question: currently, archival is done by moving (via the rename syscall) the data from the online dataset to the archives. This takes almost no time.

If I auto-archive using `.tar` files, instead, I need to perform a fully copy of all the data in the segment from the individual files to the `.tar` file. This is more time consuming, but it's worth it if you're going to tar it all anyways later.

Would you prefer to:
 - tar always
 - tar if the dataset config has an option like `archive tar = true`
 - always tar as a separate step with `arki-check --tar`
?

**Comment by spanezz** [comment]
While I was playing with tar, I implemented the option `--archive={tar|tar.gz|tar.xz|zip}` for `arki-query` and `arki-scan`.

This finally allows to query ODIM data with `arki-query` and have them output as a `.tar` that can be easily extracted without needing to do hacks with `arki-xargs`.

The archives contain the data files, and also a file `metadata.md` with the metadata. `metadata.md` can work like a dataset, so one can query it with `arki-query` to further filter the data.

**Comment by spanezz** [comment]
For fun, this is a new unexpected way to split a pack of GRIB messages into individual files:
```
arki-scan --archive=tar test/data/fixture.grib1 |tar xf -
```

**Comment by brancomat** [comment]
> Would you prefer to:
> 
> tar always
> tar if the dataset config has an option like archive tar = true
> always tar as a separate step with arki-check --tar
> ?

This will need a little internal discussion (maybe during the meeting already scheduled). 

Personally I'd say we could have a dataset config option, keeping the possibility to tar old existing segments with the `--tar` option (assuming that adding the "`archive tar = true`" option on datasets wouldn't impact pre-existing archives)

Speaking of whitch:
> I have implemented arki-check --tar. By default it works on all archived segments that are directories, converting them into .tar files. 

Would it work on the whole `.archive` dir or only on `.archive/last/YYYY`? (We tipically have other subdirs with custom data periods associated with a summary file in .`archive`)

**Comment by spanezz** [comment]
`arki-check --tar` should work on the whole `.archive` directory
