### ISSUE TITLE
Implement `.zip` datasets

### ISSUE THREAD

**Issue by spanezz** [ARPA-SIMC/arkimet#132]
Now that there is a `--archive=zip` option, and that `.zip` files can be accessed randomly, it is possible to implement a dataset-in-a-zip-file:
1. open the .zip file
2. extract data/metadata.md and keep it in memory as an index, using a new `types::Source::Zip` that stores filenames instead of offsets
3. when needing to produce data, extract the right file from inside the `.zip`

This cannot be done with libarchive because it does not support random access, but it would be possible with [libzip](https://libzip.org/documentation/)

With this, one could use `arki-scan --archive=zip` to turn any input file into an efficient and self-contained dataset

**Comment by edigiacomo** [comment]
Questa issue è stata chiusa per inattività. Nel caso in cui sia un argomento ancora rilevante, si prega di riaprirla con una motivazione che tenga conto delle modifiche applicate nel corso degli anni al progetto.
