### ISSUE TITLE
should any missing grib definitions result in failed tests?

### ISSUE THREAD

**Issue by brancomat** [ARPA-SIMC/arkimet#138]
this build went up with a version of `eccodes-simc` that missed a definition (now fixed):
https://api.travis-ci.org/v3/job/376302915/log.txt

the relevant part:
```
arki_scan_grib: .........ECCODES ERROR   :  Unable to find template localDefinition from grib1/local.200.254.def 
ECCODES ERROR   :  Unable to find template localDefinition from grib1/local.200.254.def 
ECCODES ERROR   :  Unable to find template localDefinition from grib1/local.200.254.def 
(...)
```

That didn't impact the test exit status (the build succeeded) but I'm unsure if it's the intended behaviour and we're all ok with that

**Comment by spanezz** [comment]
It looks like eccodes is printing the error but going on successfully anyway. If this is not intended behaviour, I can look through the eccodes documentation to see if they have a system to catch these warnings and turn them into errors

**Comment by brancomat** [comment]
So eccodes prints 80 times (I counted them) `ECCODES ERROR` as a warning? Ok then.

![](https://utbblogs.com/home/bradu25/public_html/wp-content/uploads/2016/11/You-keep-using-that-word.jpg)

It's clearly not an arkimet issue.
