### ISSUE TITLE
arki_metadata_libarchive test fail

### ISSUE THREAD

**Issue by brancomat** [ARPA-SIMC/arkimet#139]
All of Travis' Fedora builds fail in the `arki_metadata_libarchive` test. (e.g: https://api.travis-ci.org/v3/job/376302916/log.txt )
Right now we have no recent fedora internal test server, I'll update this bug when we have one.
(Or if @spanezz develops some divination skills and fix this, whichever comes first)

Maybe I'll try and disable compressed archive to see if it's the only issue.

```
 * Test failures

arki_metadata_libarchive.zip: 'Archive:  test.zip
  Length      Date    Time    Name
---------  ---------- -----   ----
     7218  07-08-2007 13:00   data/000001.grib
    34960  07-07-2007 00:00   data/000002.grib
     2234  10-09-2007 00:00   data/000003.grib
      588  05-08-2018 10:50   data/metadata.md
---------                     -------
    45000                     4 files
' does not match 'Archive:  test.zip
  Length      Date    Time    Name
---------  ---------- -----   ----
     7218  2007-07-08 15:00   data/000001.grib
    34960  2007-07-07 02:00   data/000002.grib
     2234  2007-10-09 02:00   data/000003.grib
      588  [0-9]+-[0-9]+-[0-9]+ [0-9]+:[0-9]+   data/metadata.md
---------                     -------
    45000                     4 files
'
  metadata/libarchive-test.cc:102:actual(sys::read_file("test.out")).matches( R"(Archive:  test.zip
  Length      Date    Time    Name
---------  ---------- -----   ----
     7218  2007-07-08 15:00   data/000001.grib
    34960  2007-07-07 02:00   data/000002.grib
     2234  2007-10-09 02:00   data/000003.grib
      588  [0-9]+-[0-9]+-[0-9]+ [0-9]+:[0-9]+   data/metadata.md
---------                     -------
    45000                     4 files
)" )

 * Result summary

1/2546 tests failed
```

**Comment by brancomat** [comment]
good news (?) `arki_metadata_libarchive` test fails also on fedora 24, so it could be reproduced on internal server `ventiquattro`

**Comment by dcesari** [comment]
Isn't it related to the expected/actual date format (LANG=it_IT.UTF-8 or whatever)?

**Comment by brancomat** [comment]
I don't know, I don't think that docker images used by travis share the same language settings of our internal servers. I tried another build on `ventiquattro` unsetting `LANG` variable but the output is the same

**Comment by dcesari** [comment]
More in depth: `./arki/metadata/libarchive-test.cc` has an hardcoded test on lines that should look like:
```
     7218  2007-07-08 15:00   data/000001.grib
    34960  2007-07-07 02:00   data/000002.grib
     2234  2007-10-09 02:00   data/000003.grib
```
while on Fedora 24 i do not manage to force unzip by environmental variables (unsetting LANG, TZ, etc) to use a date format other than DD-MM-YYYY (and probably timezone CEST), does it depends on unzip version? Or where the cabbage does unzip get locale information? Maybe in the zip file itself?

**Comment by dcesari** [comment]
Note that also the time of the files does not match (time zone? summer time?). See PR #141.
