### ISSUE TITLE
error compiling

### ISSUE THREAD

**Issue by pat1** [ARPA-SIMC/arkimet#14]
with rpmbuild on a i386 fedora 20 system I get:

libtool: compile:  g++ -DHAVE_CONFIG_H -I.. -I.. -L/usr/lib -DCONF_DIR=\"/etc/arkimet\" -DPOSTPROC_DIR=\"/usr/lib/arkimet\" -I/usr/include -Werror -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m32 -march=i686 -mtune=atom -fasynchronous-unwind-tables -Wall -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m32 -march=i686 -mtune=atom -fasynchronous-unwind-tables -std=c++11 -c iotrace.cc -o libarkimet_la-iotrace.o
iotrace.cc: In member function 'virtual void arki::iotrace::Logger::operator()(const arki::iotrace::Event&)':
iotrace.cc:136:83: error: format '%zu' expects argument of type 'size_t', but argument 4 has type 'off_t {aka long long int}' [-Werror=format=]
     fprintf(out, "%s:%zu:%zu:%s\n", e.filename().c_str(), e.offset, e.size, e.desc);
                                                                                   ^
cc1plus: all warnings being treated as errors
make[4]: *** [libarkimet_la-iotrace.lo] Error 1
make[4]: Leaving directory `/root/rpmbuild/BUILD/arkimet-1.0-1/arki'
make[3]: *** [all-recursive] Error 1
make[3]: Leaving directory `/root/rpmbuild/BUILD/arkimet-1.0-1/arki'
make[2]: *** [all] Error 2
make[2]: Leaving directory `/root/rpmbuild/BUILD/arkimet-1.0-1/arki'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/root/rpmbuild/BUILD/arkimet-1.0-1'
make: *** [all] Error 2
errore: Stato d'uscita errato da /var/tmp/rpm-tmp.PkCPvY (%build)

**Comment by spanezz** [comment]
I fixed that problem, but there may be more. Is there a Fedora 20 i386 machine I can log into, to try a build myself?

**Comment by pat1** [comment]
ora infatti in un altro punto:
libtool: compile:  g++ -DHAVE_CONFIG_H -I.. -I.. -L/usr/lib -DCONF_DIR=\"/usr/local/etc/arkimet\" -DPOSTPROC_DIR=\"/usr/local/lib/arkimet\" -I/usr/include -Werror -g -O2 -Wall -g -O2 -std=c++11 -MT utils/libarkimet_la-datareader.lo -MD -MP -MF utils/.deps/libarkimet_la-datareader.Tpo -c utils/datareader.cc -o utils/libarkimet_la-datareader.o
utils/datareader.cc: In member function 'virtual void arki::utils::datareader::DirReader::read(off_t, size_t, void*)':
utils/datareader.cc:81:63: error: format '%zd' expects argument of type 'signed size_t', but argument 4 has type 'off_t {aka long long int}' [-Werror=format=]
         snprintf(dataname, 32, "%06zd.%s", ofs, format.c_str());
                                                               ^
utils/datareader.cc:81:63: error: format '%zd' expects argument of type 'signed size_t', but argument 4 has type 'off_t {aka long long int}' [-Werror=format=]

**Comment by pat1** [comment]
con questa patch, pare non ci siano altri problemi di questo genere:
git diff
diff --git a/arki/utils/datareader.cc b/arki/utils/datareader.cc
index 5a5e697..e3d4ceb 100644
--- a/arki/utils/datareader.cc
+++ b/arki/utils/datareader.cc
@@ -78,7 +78,7 @@ public:
     void read(off_t ofs, size_t size, void* buf)
     {
         char dataname[32];
-        snprintf(dataname, 32, "%06zd.%s", ofs, format.c_str());
+        snprintf(dataname, 32, "%06zd.%s", (size_t)ofs, format.c_str());
         sys::File file_fd(dirfd.openat(dataname, O_RDONLY | O_CLOEXEC), str::joinpath(dirfd.name(), dataname));
 
         if (posix_fadvise(file_fd, 0, size, POSIX_FADV_DONTNEED) != 0)

**Comment by pat1** [comment]
però in ultimo il problema è questo:

Making all in src
make[2]: Entering directory `/root/git/arkimet/src'
depbase=`echo arki-check.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
g++ -DHAVE_CONFIG_H   -I.. -I..   -L/usr/lib     -DSERVER_DIR=\"/usr/local/share/arkimet/server\" -Wall -Werror -I/usr/include   -g -O2  -g -O2 -std=c++11 -MT arki-check.o -MD -MP -MF $depbase.Tpo -c -o arki-check.o arki-check.cc &&\
mv -f $depbase.Tpo $depbase.Po
/bin/sh ../libtool  --tag=CXX   --mode=link g++  -g -O2 -std=c++11   -o arki-check arki-check.o ../arki/libarkimet.la  -ldballe -lwreport -llua -lm -ldl -lsqlite3  -I/usr/include -lsqlite3 -lgrib_api -ljasper -lm -llua -lm -ldl  -L/usr/lib -lz   -lpthread -L/usr/lib -lgeos -lcurl  -llzo2 -lreadline
libtool: link: g++ -g -O2 -std=c++11 -o arki-check arki-check.o -I/usr/include  ../arki/.libs/libarkimet.a -L/usr/lib -L/usr/lib/mysql /usr/lib/libmeteo-vm2.so -lhdf5 -lhdf5_hl -lnetcdf_c++ /usr/lib/libdballe.so -lpq -lmysqlclient -lssl -lcrypto -lodbc -lpopt /usr/lib/libwreport.so -lsqlite3 /usr/lib/libgrib_api.so -lpng -lopenjpeg -lnetcdf -ljasper -llua -lm -ldl -lz -lpthread -lgeos -lcurl -llzo2 -lreadline
../arki/.libs/libarkimet.a(libarkimet_la-grib.o): In function `arki::scan::grib::GribValidator::validate_file(arki::utils::sys::NamedFileDescriptor&, long long, unsigned int) const':
/root/git/arkimet/arki/scan/grib.cc:37: undefined reference to `arki::utils::sys::FileDescriptor::pread(void*, unsigned int, long long)'
/root/git/arkimet/arki/scan/grib.cc:42: undefined reference to `arki::utils::sys::FileDescriptor::pread(void*, unsigned int, long long)'
../arki/.libs/libarkimet.a(libarkimet_la-odimh5.o): In function `arki::scan::odimh5::OdimH5Validator::validate_file(arki::utils::sys::NamedFileDescriptor&, long, unsigned int) const':
/root/git/arkimet/arki/scan/odimh5.cc:46: undefined reference to `arki::scan::Validator::throw_check_error(arki::utils::sys::NamedFileDescriptor&, long, std::string const&) const'
/root/git/arkimet/arki/scan/odimh5.cc:55: undefined reference to `arki::scan::Validator::throw_check_error(arki::utils::sys::NamedFileDescriptor&, long, std::string const&) const'
/root/git/arkimet/arki/scan/odimh5.cc:52: undefined reference to `arki::scan::Validator::throw_check_error(arki::utils::sys::NamedFileDescriptor&, long, std::string const&) const'
../arki/.libs/libarkimet.a(lt21-libarkimet_la-vm2.o): In function `arki::scan::vm2::VM2Validator::validate_file(arki::utils::sys::NamedFileDescriptor&, long, unsigned int) const':
/root/git/arkimet/arki/scan/vm2.cc:44: undefined reference to `arki::scan::Validator::throw_check_error(arki::utils::sys::NamedFileDescriptor&, long, std::string const&) const'
/root/git/arkimet/arki/scan/vm2.cc:52: undefined reference to `arki::scan::Validator::throw_check_error(arki::utils::sys::NamedFileDescriptor&, long, std::string const&) const'
../arki/.libs/libarkimet.a(lt22-libarkimet_la-dir.o): In function `arki::dataset::segment::dir::Segment::write_file(arki::Metadata&, arki::utils::sys::File&)':
/root/git/arkimet/arki/dataset/segment/dir.cc:203: undefined reference to `arki::utils::sys::FileDescriptor::pwrite(void const*, unsigned int, long long)'
../arki/.libs/libarkimet.a(libarkimet_la-fd.o): In function `arki::dataset::segment::fd::Segment::wrpos()':
/root/git/arkimet/arki/dataset/segment/fd.cc:87: undefined reference to `arki::utils::sys::FileDescriptor::lseek(long long, int)'
../arki/.libs/libarkimet.a(libarkimet_la-manifest.o): In function `arki::dataset::index::manifest::PlainManifest::reread()':
/root/git/arkimet/arki/dataset/index/manifest.cc:303: undefined reference to `arki::utils::sys::inode(std::string const&, unsigned long long)'
../arki/.libs/libarkimet.a(libarkimet_la-bufr.o): In function `arki::scan::bufr::BufrValidator::validate_file(arki::utils::sys::NamedFileDescriptor&, long long, unsigned int) const':
/root/git/arkimet/arki/scan/bufr.cc:51: undefined reference to `arki::utils::sys::FileDescriptor::pread(void*, unsigned int, long long)'
/root/git/arkimet/arki/scan/bufr.cc:55: undefined reference to `arki::utils::sys::FileDescriptor::pread(void*, unsigned int, long long)'
../arki/.libs/libarkimet.a(libarkimet_la-concat.o): In function `arki::dataset::segment::concat::HoleSegment::write(std::vector<unsigned char, std::allocator<unsigned char> > const&)':
/root/git/arkimet/arki/dataset/segment/concat.cc:136: undefined reference to `arki::utils::sys::FileDescriptor::lseek(long long, int)'
../arki/.libs/libarkimet.a(libarkimet_la-datareader.o): In function `arki::utils::datareader::FileReader::read(long long, unsigned int, void*)':
/root/git/arkimet/arki/utils/datareader.cc:46: undefined reference to `arki::utils::sys::FileDescriptor::pread(void*, unsigned int, long long)'
../arki/.libs/libarkimet.a(libarkimet_la-datareader.o): In function `arki::utils::datareader::IdxZlibFileReader::reposition(long long)':
/root/git/arkimet/arki/utils/datareader.cc:164: undefined reference to `arki::utils::sys::FileDescriptor::lseek(long long, int)'
../arki/.libs/libarkimet.a(libarkimet_la-datareader.o): In function `arki::utils::datareader::DirReader::read(long long, unsigned int, void*)':
/root/git/arkimet/arki/utils/datareader.cc:87: undefined reference to `arki::utils::sys::FileDescriptor::pread(void*, unsigned int, long long)'
collect2: error: ld returned 1 exit status
make[2]: *** [arki-check] Errore 1
make[2]: Leaving directory `/root/git/arkimet/src'
make[1]: *** [all-recursive] Errore 1
make[1]: Leaving directory `/root/git/arkimet'
make: *** [all] Errore 2

**Comment by spanezz** [comment]
I cannot fix this without trying out options first hand. Is there a Fedora 20 i386 machine I can log into, to try a build myself?

**Comment by pat1** [comment]
si, ma mi devi contattare direttamente.

**Comment by spanezz** [comment]
It now builds, but make check still fails. dballe and wreport need to be fixed with a similar patch as with 774cc977ed0ef363d0289348c5755a052b716c13

At the moment, arkimet and wreport/dballe have a different idea of the layout of in-memory structures, because wreport and dballe for some things still use 32bit file offsets.
