### ISSUE TITLE
arki_binary.integer test fail on fedora 20

### ISSUE THREAD

**Issue by brancomat** [ARPA-SIMC/arkimet#142]
Fedora 20 is not completely dismissed but we can consider it dismissed.
Anyway, I tried building arkimet 1.7 and (only on F20) it fails a test:

```
arki_binary.integer: value '257' is different than the expected '256'
  binary-test.cc:58:actual(dec.pop_uint((2u), "value")) == (256u)
```
As I said, it's not a problem dismissing f20 builds, I'm reporting it only in the off chance it's something that could somehow have an impact on recent systems.
`venti` internal server is available for testing purposes, last build is in `/home_local/makerpm/rpmbuild/BUILD/arkimet-1.7-1/`

**Comment by spanezz** [comment]
I managed to create a minimal test case.

Given this source:
```c++
#include <cstdio>
#include <vector>

using namespace std;

struct BinaryEncoder
{
    /// Encode an unsigned integer in the given amount of bytes, big endian
    void add_unsigned(std::vector<unsigned char>& dest, unsigned short val)
    {
        for (unsigned int i = 0; i < 2; ++i)
            dest.push_back((val >> ((2 - i - 1) * 8)) & 0xff);
    }
};

bool issue()
{
    vector<unsigned char> enc;
    BinaryEncoder e;
    e.add_unsigned(enc, 256u);
    fprintf(stderr, "size: %zd==2\n", enc.size());
    fprintf(stderr, "bytes: %hhu==1 %hhu==0\n", enc[0], enc[1]);
    if (enc[0] != 1) return false;
    if (enc[1] != 0) return false;
    return true;
}

int main(int argc, const char* argv[])
{
    return issue() ? 0 : 1;
}
```

Compiling it on Fedora 20 with -O2 makes it fail:
```
$ g++ main.cpp -o main -O2 && ./main || echo FAIL
size: 2==2
bytes: 1==1 1==0
FAIL
```
On other systems, or using -O1, it works:
```
$ g++ main.cpp -o main -O1 && ./main || echo FAIL
size: 2==2
bytes: 1==1 0==0
```
Can you force arkimet to be built on Fedora 20 with -O1 instead of -O2?

**Comment by brancomat** [comment]
Chapeau!
This behaviour is slightly unsettling... anyway, right now I'm building arkimet on Fedora 20 with `-O1`, if it the `make check` passes I'll patch the specfile to change `CXXFLAGS` only for F20

**Comment by spanezz** [comment]
> This behaviour is slightly unsettling...

It looks like a compiler bug, long fixed since the version in Fedora 20
