### ISSUE TITLE
format = <format> missed in documentation

### ISSUE THREAD

**Issue by pat1** [ARPA-SIMC/arkimet#143]
I see format = <format> in arkiguide.it.txt only.
No other documentation ( in ds-iseg.md for example).

**Comment by spanezz** [comment]
I can add a `doc/config.md` documenting the dataset configuration file. Would it address your problem, or would it just be a duplicate of what is in arkiguide?

**Comment by pat1** [comment]
Ok, good idea, it would be useful to document dataset configuration options in arkimet's documentation

**Comment by brancomat** [comment]
This was one of the topics of issue #67, in one of the comments there's a list of the supported dataset fields (uptated to April 2017).

I agree that sooner or later the list should be placed in the official arkimet documentation.

**Comment by spanezz** [comment]
To summarise, the current arkimet documentation misses a section documenting dataset configuration directives, and it should be added. Correct?

**Comment by brancomat** [comment]
Yes.
