### ISSUE TITLE
expa extractions don't work with remote datasets

### ISSUE THREAD

**Issue by brancomat** [ARPA-SIMC/arkimet#145]
we just moved a bunch of datasets from an arki-server that now shows the same datasets as remote

expa extraction does not work anymore:
```
[simdaemon@simdaemon24 cosmo_5M]$  arki-query --data --qmacro="expa 2018-06-05" --file="00.expa" -o buttami.grib http://arkimet.metarpa:8090/
while Cannot query http://arkimet.metarpa:8090/query: Server returned nothing (no headers, no data)(Empty reply from server)
[simdaemon@simdaemon24 cosmo_5M]$ echo $?
1
```

expected result (now I'm using the arki-server that's actually hosting the dataset):
```
[simdaemon@simdaemon24 cosmo_5M]$  arki-query --data --qmacro="expa 2018-06-05" --file="00.expa" -o buttami.grib http://arkiope.metarpa:8090/
[simdaemon@simdaemon24 cosmo_5M]$ ls -la buttami.grib 
-rw-rw-r--. 1 simdaemon simdaemon 338324192  5 giu 11.02 buttami.grib
```

Here is the expa (but it seems that any expa on remote datasets doesn't work):
[00.expa.txt](https://github.com/ARPA-SIMC/arkimet/files/2071642/00.expa.txt)

**Comment by brancomat** [comment]
some logging info:
`/var/log/arkimet/server-error.log` shows nothing

`/var/log/arkimet/server-access.log` for that client shows only
 [05/Jun/2018:09:11:28 +0000] "GET /config HTTP/1.1" 200 -

**Comment by brancomat** [comment]
Update:
so, the first time we experienced this issue on `arkimet 1.4-3` and:
- `arki-query` with expa on remote datasets weren't working (zero output) with exit status 0
- `arki-query` without expa on remote dataset were working

then we updated to `arkimet `arkimet-1.6-3` (last release available on fedora 20) and the current situation is:
- `arki-query` with or without expa don't work with `Cannot query http://arkimet.metarpa:8090/dataset/cosmo_5M_ita/query: Server returned nothing (no headers, no data)(Empty reply from server)`

right now I'm downgrading again to 1.4-3, but a fix for f20 would incur in #142

**Comment by spanezz** [comment]
It seems that all remote queries stopped working in arkimet, which is strange to me, because they are tested a bit in the test suite at build time.

Can you reproduce this with current master? If so, can you give me access to the machine where you can reproduce it?

**Comment by spanezz** [comment]
> right now I'm downgrading again to 1.4-3, but a fix for f20 would incur in #142
I might have found a potential workaround for #142

**Comment by brancomat** [comment]
right now from any internal client (such as `ventiquattro`):
```
arki-query --summary --yaml 'Reftime:=2018-06-12 0:00' http://arkimet.metarpa:8090/dataset/cosmo_2I_ruc/
http://arkimet.metarpa:8090/dataset/cosmo_2I_ruc failed: while Cannot query http://arkimet.metarpa:8090/dataset/cosmo_2I_ruc/summary: Server returned nothing (no headers, no data)(Empty reply from server)
```

server `arkimet` has this conf for that dataset:
```
[cosmo_2I_ruc]
__logname = CINECA;cosmo_2I_ruc
archive age = 10
description = COSMO 2.2Km Rapid Update Cycle, Italian area
filter = origin:GRIB1,80,,14; area:GRIB:Ni=576,Nj=701
index = reftime, timerange, level, product
name = cosmo_2I_ruc
path = http://arkiope.metarpa:8090/dataset/cosmo_2I_ruc
postprocess = singlepoint, subarea
replace = yes
restrict = simc, cosmo
server = http://arkiope.metarpa:8090
step = daily
type = remote
unique = origin, reftime, timerange, level, product
```

**Comment by brancomat** [comment]
nothing apparently useful in arki-server error logs but in system logs I have several:
```
Jun 12 11:37:12 localhost kernel: [15113434.156985] arki-server htt[16742]: segfault at 0 ip           (null) sp 00007fff4687c2c8 error 14 in python3.3[400000+1000]
Jun 12 11:37:12 localhost kernel: arki-server htt[16742]: segfault at 0 ip           (null) sp 00007fff4687c2c8 error 14 in python3.3[400000+1000]
```
I'm downgrading again the arki-server and I'll try to create a test case somewhere else

**Comment by edigiacomo** [comment]
With arkimet v1.14-1

* arki-query with expa on remote datasets weren't working (zero output) with exit status 0
* arki-query without expa on remote dataset were working

**Comment by edigiacomo** [comment]
Run arki-server:
```
$ curl http://arkimet.metarpa:8090/dataset/itfs_atl025/config > config
$ arki-server --url http://localhost:8080 --debug config
```
Run arki-query:
```
$ echo "ds:ifs_atl025. d:@. t:0000. s:F210. l:G00. v:TP." > expa
$ arki-query --data --qmacro="expa 2019-03-05" --file=expa http://localhost:8080/dataset/ifs_atl025 | wc -c
0
$ echo ${PIPESTATUS[*]}
0 0
```

**Comment by edigiacomo** [comment]
Updating both to arki-server v14-1 fixes the bug.

**Comment by edigiacomo** [comment]
Assuming the match-alias.conf are the same, in recent versions of arkimet the issue is fixed.
