### ISSUE TITLE
arkimet do not compile on 32 bit machine

### ISSUE THREAD

**Issue by pat1** [ARPA-SIMC/arkimet#148]
On fedora 20 32 bit machine I get:

sh autogen.sh
autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal --force -I m4
autoreconf: configure.ac: tracing
autoreconf: running: libtoolize --copy --force
libtoolize: putting auxiliary files in `.'.
libtoolize: copying file `./ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIR, `m4'.
libtoolize: copying file `m4/libtool.m4'
libtoolize: copying file `m4/ltoptions.m4'
libtoolize: copying file `m4/ltsugar.m4'
libtoolize: copying file `m4/ltversion.m4'
libtoolize: copying file `m4/lt~obsolete.m4'
autoreconf: running: /usr/bin/autoconf --force
autoreconf: running: /usr/bin/autoheader --force
autoreconf: running: automake --add-missing --copy --force-missing
configure.ac:88: installing './compile'
configure.ac:13: installing './config.guess'
configure.ac:13: installing './config.sub'
configure.ac:5: installing './install-sh'
configure.ac:5: installing './missing'
arki/Makefile.am: installing './depcomp'
python/Makefile.am:7: installing './py-compile'
autoreconf: Leaving directory `.'
+ exit 0
Esecuzione(%build) in corso: /bin/sh -e /var/tmp/rpm-tmp.ao31K2
+ umask 022
+ cd /root/rpmbuild/BUILD
+ cd arkimet-1.7-5
+ export 'CXXFLAGS=-O1 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic'
+ CXXFLAGS='-O1 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic'
+ echo 'Enabling ARPAE tests'
Enabling ARPAE tests
+ CFLAGS='-O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches  -m32 -march=i686 -mtune=atom -fasynchronous-unwind-tables'
+ export CFLAGS
+ CXXFLAGS='-O1 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic'
+ export CXXFLAGS
+ FFLAGS='-O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches  -m32 -march=i686 -mtune=atom -fasynchronous-unwind-tables -I/usr/lib/gfortran/modules'
+ export FFLAGS
+ FCFLAGS='-O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches  -m32 -march=i686 -mtune=atom -fasynchronous-unwind-tables -I/usr/lib/gfortran/modules'
+ export FCFLAGS
+ LDFLAGS='-Wl,-z,relro '
+ export LDFLAGS
++ find . -name config.guess -o -name config.sub
+ for i in '$(find . -name config.guess -o -name config.sub)'
++ basename ./config.sub
+ '[' -f /usr/lib/rpm/redhat/config.sub ']'
+ /usr/bin/rm -f ./config.sub
++ basename ./config.sub
+ /usr/bin/cp -fv /usr/lib/rpm/redhat/config.sub ./config.sub
'/usr/lib/rpm/redhat/config.sub' -> './config.sub'
+ for i in '$(find . -name config.guess -o -name config.sub)'
++ basename ./config.guess
+ '[' -f /usr/lib/rpm/redhat/config.guess ']'
+ /usr/bin/rm -f ./config.guess
++ basename ./config.guess
+ /usr/bin/cp -fv /usr/lib/rpm/redhat/config.guess ./config.guess
'/usr/lib/rpm/redhat/config.guess' -> './config.guess'
+ ./configure --build=i686-redhat-linux-gnu --host=i686-redhat-linux-gnu --program-prefix= --disable-dependency-tracking --prefix=/usr --exec-prefix=/usr --bindir=/usr/bin --sbindir=/usr/sbin --sysconfdir=/etc --datadir=/usr/share --includedir=/usr/include --libdir=/usr/lib --libexecdir=/usr/libexec --localstatedir=/var --sharedstatedir=/var/lib --mandir=/usr/share/man --infodir=/usr/share/info --enable-arpae-tests
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking build system type... i686-redhat-linux-gnu
checking host system type... i686-redhat-linux-gnu
checking how to print strings... printf
checking for style of include used by make... GNU
checking for i686-redhat-linux-gnu-gcc... no
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking dependency style of gcc... none
checking for a sed that does not truncate output... /usr/bin/sed
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for fgrep... /usr/bin/grep -F
checking for ld used by gcc... /usr/bin/ld
checking if the linker (/usr/bin/ld) is GNU ld... yes
checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
checking the name lister (/usr/bin/nm -B) interface... BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 1572864
checking whether the shell understands some XSI constructs... yes
checking whether the shell understands "+="... yes
checking how to convert i686-redhat-linux-gnu file names to i686-redhat-linux-gnu format... func_convert_file_noop
checking how to convert i686-redhat-linux-gnu file names to toolchain format... func_convert_file_noop
checking for /usr/bin/ld option to reload object files... -r
checking for i686-redhat-linux-gnu-objdump... no
checking for objdump... objdump
checking how to recognize dependent libraries... pass_all
checking for i686-redhat-linux-gnu-dlltool... no
checking for dlltool... no
checking how to associate runtime and link libraries... printf %s\n
checking for i686-redhat-linux-gnu-ar... no
checking for ar... ar
checking for archiver @FILE support... @
checking for i686-redhat-linux-gnu-strip... no
checking for strip... strip
checking for i686-redhat-linux-gnu-ranlib... no
checking for ranlib... ranlib
checking command to parse /usr/bin/nm -B output from gcc object... ok
checking for sysroot... no
checking for i686-redhat-linux-gnu-mt... no
checking for mt... no
checking if : is a manifest tool... no
checking how to run the C preprocessor... gcc -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for dlfcn.h... yes
checking for objdir... .libs
checking if gcc supports -fno-rtti -fno-exceptions... no
checking for gcc option to produce PIC... -fPIC -DPIC
checking if gcc PIC flag -fPIC -DPIC works... yes
checking if gcc static flag -static works... no
checking if gcc supports -c -o file.o... yes
checking if gcc supports -c -o file.o... (cached) yes
checking whether the gcc linker (/usr/bin/ld) supports shared libraries... yes
checking whether -lc should be explicitly linked in... no
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... yes
checking for i686-redhat-linux-gnu-g++... no
checking for i686-redhat-linux-gnu-c++... no
checking for i686-redhat-linux-gnu-gpp... no
checking for i686-redhat-linux-gnu-aCC... no
checking for i686-redhat-linux-gnu-CC... no
checking for i686-redhat-linux-gnu-cxx... no
checking for i686-redhat-linux-gnu-cc++... no
checking for i686-redhat-linux-gnu-cl.exe... no
checking for i686-redhat-linux-gnu-FCC... no
checking for i686-redhat-linux-gnu-KCC... no
checking for i686-redhat-linux-gnu-RCC... no
checking for i686-redhat-linux-gnu-xlC_r... no
checking for i686-redhat-linux-gnu-xlC... no
checking for g++... g++
checking whether we are using the GNU C++ compiler... no
checking whether g++ accepts -g... yes
checking dependency style of g++... none
checking how to run the C++ preprocessor... g++ -E
checking whether the g++ linker (/usr/bin/ld) supports shared libraries... yes
libtool.m4: error: problem compiling CXX test program
checking for g++ option to produce PIC...  -DPIC
checking if g++ PIC flag  -DPIC works... no
checking if g++ static flag  works... no
checking if g++ supports -c -o file.o... no
checking if g++ supports -c -o file.o... (cached) no
checking whether the g++ linker (/usr/bin/ld) supports shared libraries... yes
checking dynamic linker characteristics... (cached) GNU/Linux ld.so
checking how to hardcode library paths into programs... unsupported
checking whether make sets $(MAKE)... (cached) yes
checking for library containing strerror... no
checking for i686-redhat-linux-gnu-gcc... gcc
checking whether we are using the GNU C compiler... (cached) yes
checking whether gcc accepts -g... (cached) yes
checking for gcc option to accept ISO C89... (cached) none needed
checking dependency style of gcc... (cached) none
checking whether we are using the GNU C++ compiler... (cached) no
checking whether g++ accepts -g... (cached) yes
checking dependency style of g++... (cached) none
checking whether g++ supports C++11 features by default... no
checking whether g++ supports C++11 features with -std=c++11... no
configure: No compiler with C++11 support was found
checking for flex... flex
checking lex output file root... lex.yy
checking lex library... none needed
checking whether yytext is a pointer... no
checking for bison... bison -y
checking for i686-redhat-linux-gnu-gcc... (cached) gcc
checking whether we are using the GNU C compiler... (cached) yes
checking whether gcc accepts -g... (cached) yes
checking for gcc option to accept ISO C89... (cached) none needed
checking dependency style of gcc... (cached) none
checking for ANSI C header files... (cached) yes
checking whether gcc and cc understand -c and -o together... yes
checking for i686-redhat-linux-gnu-pkg-config... /usr/bin/i686-redhat-linux-gnu-pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for special C compiler options needed for large files... no
checking for _FILE_OFFSET_BITS value needed for large files... unknown
checking for _LARGE_FILES value needed for large files... unknown
checking for _LARGEFILE_SOURCE value needed for large files... unknown
checking for d_type member in directory struct... no
checking for mkdtemp... no
checking for splice... no
checking for i686-redhat-linux-gnu-pkg-config... (cached) /usr/bin/i686-redhat-linux-gnu-pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for SQLite3 library >= 3.14... not found
configure: WARNING: Cannot find an appropriate version of SQLite, using the embedded version
checking for a readline compatible library... no
configure: WARNING: compiling without libarchive
configure: WARNING: compiling without libzip
checking for DBALLE... yes
checking for ZLIB... yes
checking for LUA... yes
checking for grib_get_long in -lgrib_api... no
checking grib_api.h usability... no
checking grib_api.h presence... yes
configure: WARNING: grib_api.h: present but cannot be compiled
configure: WARNING: grib_api.h:     check for missing prerequisite headers?
configure: WARNING: grib_api.h: see the Autoconf documentation
configure: WARNING: grib_api.h:     section "Present But Cannot Be Compiled"
configure: WARNING: grib_api.h: proceeding with the compiler's result
configure: WARNING:     ## ------------------------------------ ##
configure: WARNING:     ## Report this to enrico@enricozini.org ##
configure: WARNING:     ## ------------------------------------ ##
checking for grib_api.h... no
configure: WARNING: compiling without grib_api
checking for HDF5... no
checking for h5cc... /usr/bin/h5cc
checking for HDF5 libraries... yes (version 1.8.11)
checking hdf5.h usability... no
checking hdf5.h presence... yes
configure: WARNING: hdf5.h: present but cannot be compiled
configure: WARNING: hdf5.h:     check for missing prerequisite headers?
configure: WARNING: hdf5.h: see the Autoconf documentation
configure: WARNING: hdf5.h:     section "Present But Cannot Be Compiled"
configure: WARNING: hdf5.h: proceeding with the compiler's result
configure: WARNING:     ## ------------------------------------ ##
configure: WARNING:     ## Report this to enrico@enricozini.org ##
configure: WARNING:     ## ------------------------------------ ##
checking for hdf5.h... no
checking for H5Fcreate in -lhdf5... no
configure: WARNING: Unable to compile HDF5 test program
checking for main in -lhdf5_hl... no
checking for matching HDF5 Fortran wrapper... /usr/bin/h5fc
checking for gawk... (cached) gawk
checking for curl-config... /usr/bin/curl-config
checking for the version of libcurl... 7.32.0
checking whether libcurl is usable... no
checking for geos-config... /usr/bin/geos-config
checking for __lzo_init_v2 in -llzo2... no
checking lzo/lzoconf.h usability... no
checking lzo/lzoconf.h presence... yes
configure: WARNING: lzo/lzoconf.h: present but cannot be compiled
configure: WARNING: lzo/lzoconf.h:     check for missing prerequisite headers?
configure: WARNING: lzo/lzoconf.h: see the Autoconf documentation
configure: WARNING: lzo/lzoconf.h:     section "Present But Cannot Be Compiled"
configure: WARNING: lzo/lzoconf.h: proceeding with the compiler's result
configure: WARNING:     ## ------------------------------------ ##
configure: WARNING:     ## Report this to enrico@enricozini.org ##
configure: WARNING:     ## ------------------------------------ ##
checking for lzo/lzoconf.h... no
configure: WARNING: Cannot find an appropriate version of LZO, using the embedded version
checking for VM2... yes
checking for a Python interpreter with version >= 3.3... python3
checking for python3... /usr/bin/python3
checking for python3 version... 3.3
checking for python3 platform... linux
checking for python3 script directory... ${prefix}/lib/python3.3/site-packages
checking for python3 extension module directory... ${exec_prefix}/lib/python3.3/site-packages
checking for asciidoc... yes
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating conf/Makefile
config.status: creating embedded/Makefile
config.status: creating embedded/sqlite/Makefile
config.status: creating embedded/minilzo/Makefile
config.status: creating arki/Makefile
config.status: creating src/Makefile
config.status: creating python/Makefile
config.status: creating doc/Makefile
config.status: creating test/Makefile
config.status: creating config.h
config.status: creating arki/libconfig.h
config.status: executing depfiles commands
config.status: executing libtool commands
configure:
===================================================
arkimet-1.7 configuration:
  BUFR via DB-All.e:      yes
  GRIB 1+2 via grib_api:  no
  ODIMH5 via hdf5:        yes
  VM2 support:            yes
  CURL support:           no
  Lua support:            yes
  GEOS support:           yes, version 3
  GNU readline support:   no
  libarchive support:     no
  libzip support:         no
  LZO compression:        embedded
  Zlib compression:       yes
  SQLite version:         embedded
  Python:                 3.3
  ARPAE specific tests:   yes
  I/O profiling:          yes
  Code coverage:          no
===================================================
+ make
make  all-recursive
make[1]: Entering directory `/root/rpmbuild/BUILD/arkimet-1.7-5'
Making all in conf
make[2]: Entering directory `/root/rpmbuild/BUILD/arkimet-1.7-5/conf'
make[2]: Nothing to be done for `all'.
make[2]: Leaving directory `/root/rpmbuild/BUILD/arkimet-1.7-5/conf'
Making all in embedded
make[2]: Entering directory `/root/rpmbuild/BUILD/arkimet-1.7-5/embedded'
Making all in sqlite
make[3]: Entering directory `/root/rpmbuild/BUILD/arkimet-1.7-5/embedded/sqlite'
/bin/sh ../../libtool  --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H      -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches  -m32 -march=i686 -mtune=atom -fasynchronous-unwind-tables -c -o sqlite3.lo sqlite3.c
libtool: compile:  gcc -DHAVE_CONFIG_H -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m32 -march=i686 -mtune=atom -fasynchronous-unwind-tables -c sqlite3.c  -fPIC -DPIC -o .libs/sqlite3.o
libtool: compile:  gcc -DHAVE_CONFIG_H -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m32 -march=i686 -mtune=atom -fasynchronous-unwind-tables -c sqlite3.c -o sqlite3.o >/dev/null 2>&1
/bin/sh ../../libtool  --tag=CC   --mode=link gcc  -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches  -m32 -march=i686 -mtune=atom -fasynchronous-unwind-tables  -Wl,-z,relro  -o libsqlite3.la  sqlite3.lo  
libtool: link: ar cru .libs/libsqlite3.a .libs/sqlite3.o 
libtool: link: ranlib .libs/libsqlite3.a
libtool: link: ( cd ".libs" && rm -f "libsqlite3.la" && ln -s "../libsqlite3.la" "libsqlite3.la" )
make[3]: Leaving directory `/root/rpmbuild/BUILD/arkimet-1.7-5/embedded/sqlite'
Making all in minilzo
make[3]: Entering directory `/root/rpmbuild/BUILD/arkimet-1.7-5/embedded/minilzo'
/bin/sh ../../libtool  --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H      -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches  -m32 -march=i686 -mtune=atom -fasynchronous-unwind-tables -c -o minilzo.lo minilzo.c
libtool: compile:  gcc -DHAVE_CONFIG_H -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m32 -march=i686 -mtune=atom -fasynchronous-unwind-tables -c minilzo.c  -fPIC -DPIC -o .libs/minilzo.o
libtool: compile:  gcc -DHAVE_CONFIG_H -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m32 -march=i686 -mtune=atom -fasynchronous-unwind-tables -c minilzo.c -o minilzo.o >/dev/null 2>&1
/bin/sh ../../libtool  --tag=CC   --mode=link gcc  -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches  -m32 -march=i686 -mtune=atom -fasynchronous-unwind-tables  -Wl,-z,relro  -o libminilzo.la  minilzo.lo  
libtool: link: ar cru .libs/libminilzo.a .libs/minilzo.o 
libtool: link: ranlib .libs/libminilzo.a
libtool: link: ( cd ".libs" && rm -f "libminilzo.la" && ln -s "../libminilzo.la" "libminilzo.la" )
gcc -DHAVE_CONFIG_H      -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches  -m32 -march=i686 -mtune=atom -fasynchronous-unwind-tables -c -o testmini.o testmini.c
/bin/sh ../../libtool  --tag=CC   --mode=link gcc  -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches  -m32 -march=i686 -mtune=atom -fasynchronous-unwind-tables  -Wl,-z,relro  -o testmini testmini.o libminilzo.la 
libtool: link: gcc -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m32 -march=i686 -mtune=atom -fasynchronous-unwind-tables -Wl,-z -Wl,relro -o testmini testmini.o  ./.libs/libminilzo.a
make[3]: Leaving directory `/root/rpmbuild/BUILD/arkimet-1.7-5/embedded/minilzo'
make[3]: Entering directory `/root/rpmbuild/BUILD/arkimet-1.7-5/embedded'
make[3]: Nothing to be done for `all-am'.
make[3]: Leaving directory `/root/rpmbuild/BUILD/arkimet-1.7-5/embedded'
make[2]: Leaving directory `/root/rpmbuild/BUILD/arkimet-1.7-5/embedded'
Making all in arki
make[2]: Entering directory `/root/rpmbuild/BUILD/arkimet-1.7-5/arki'
./buildflex matcher/reftime/reftime-lex.ll
./buildbison matcher/reftime/reftime-parse.yy
/root/rpmbuild/BUILD/arkimet-1.7-5/arki/matcher/reftime/reftime-parse.yy: conflicts: 5 shift/reduce
make  all-recursive
make[3]: Entering directory `/root/rpmbuild/BUILD/arkimet-1.7-5/arki'
Making all in .
make[4]: Entering directory `/root/rpmbuild/BUILD/arkimet-1.7-5/arki'
/bin/sh ../libtool  --tag=CXX   --mode=compile g++ -DHAVE_CONFIG_H   -I.. -I.. -I/root/rpmbuild/BUILD/arkimet-1.7-5/embedded/sqlite/ -DCONF_DIR=\"/etc/arkimet\" -DPOSTPROC_DIR=\"/usr/lib/arkimet\"     -I/root/rpmbuild/BUILD/arkimet-1.7-5/embedded/minilzo/  -I/usr/include      -Werror    -O1 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -c -o wibble/sys/libarkimet_la-process.lo `test -f 'wibble/sys/process.cpp' || echo './'`wibble/sys/process.cpp
libtool: compile:  g++ -DHAVE_CONFIG_H -I.. -I.. -I/root/rpmbuild/BUILD/arkimet-1.7-5/embedded/sqlite/ -DCONF_DIR=\"/etc/arkimet\" -DPOSTPROC_DIR=\"/usr/lib/arkimet\" -I/root/rpmbuild/BUILD/arkimet-1.7-5/embedded/minilzo/ -I/usr/include -Werror -O1 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -c wibble/sys/process.cpp 
wibble/sys/process.cpp:1:0: sorry, unimplemented: 64-bit mode not compiled in
 #include "process.h"
 ^
make[4]: *** [wibble/sys/libarkimet_la-process.lo] Error 1
make[4]: Leaving directory `/root/rpmbuild/BUILD/arkimet-1.7-5/arki'
make[3]: *** [all-recursive] Error 1
make[3]: Leaving directory `/root/rpmbuild/BUILD/arkimet-1.7-5/arki'
make[2]: *** [all] Error 2
make[2]: Leaving directory `/root/rpmbuild/BUILD/arkimet-1.7-5/arki'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/root/rpmbuild/BUILD/arkimet-1.7-5'
make: *** [all] Error 2
errore: Stato d'uscita errato da /var/tmp/rpm-tmp.ao31K2 (%build)

Errori di compilazione RPM:
    Stato d'uscita errato da /var/tmp/rpm-tmp.ao31K2 (%build)

**Comment by brancomat** [comment]
Note after talking with @pat1 and @edigiacomo: if I remember correctly (but I can't find any transcript on this) years ago we decided to support 32 bit architecture only on selected project (IIRC wreport, dballe).

I'm keeping the bug open for the time being since I can't find hard evidence on this right now but I'm quite sure of it.

**Comment by brancomat** [comment]
@pat1 : please see mail thread "di bug githubbi, sviluppo, deploy e quant'altro" (2016-04-01) with you, @spanezz @dcesari @edigiacomo as recipients, the mail was basically a working draft asking for corrections/integrations that stated:

- 32bit and CentOS7 support for `dballe` and `wreport` packages
- CentOS7 support for `arkimet`
