### ISSUE TITLE
alias per dataset multipli / postprocessatori map-reduce

### ISSUE THREAD

**Issue by brancomat** [ARPA-SIMC/arkimet#153]
Sarebbe interessante poter avere la possibilità di arki-querare un dataset unico che in realtà spalmi la stessa query su più dataset (simile a quello che avviene con gli alias in expa.lua)

Visto che il tipo di dataset "remote" mi pare preveda un rapporto 1:1 si potrebbe implementare un nuovo tipo di dataset che consenta il magheggio, ma ne ignoro difficoltà implementativa.

Questa cosa si potrebbe intersecare marginalmente con la dimenticata ma non dimenticata issue #114

**Comment by spanezz** [comment]
arkimet già supporta un dataset virtuale composto dal merge di piú dataset, ed è come viene implementato internamente il run di `arki-query` su piú di un dataset.

L'unica cosa che serve direi sia decidere un qualche modo di descrivere/configurare un dataset del genere.

**Comment by brancomat** [comment]
Chiedo parere anche a @edigiacomo ma basterebbe anche una roba tipo `type = multi` (o quel che è) nel quale `path` (o altra variabile) supporti una lista di path/url e che serializzi le `arki-query` che gli arrivano sui vari dataset senza preoccuparsi di altro.

(l'ideale sarebbe poter mischiare path locali e url ma se fosse un problema si può tenere solo url, A differenza del `type = remote` però il campo `server` dovrebbe essere in qualche modo dedotto dalla lista)

Per il resto dei campi c'è da capire se è necessario/opportuno vincolarne alcuni per permettere l'accorpamento di più dataset. Va da sè che il contenuto di `postprocess` dovrà essere supportato da tutti i dataset coinvolti.

Però, in generale:
 - la cosa più utile al momento sarebbe accorpare dataset completamente analoghi per conf divisi solo per intervalli temporali su server diversi
 - la seconda cosa più utile potrebbe essere accorpare dataset simili solo per `unique` e diversi per filter (es. evoluzioni storiche di un modello particolare)

Personalmente al momento non ho altre casistiche degne di nota.

**Comment by edigiacomo** [comment]
L'unico problema che ci vedo è che il postprocessing è attualmente disabilitato per query su più dataset e i motivi di questa scelta immagino che si ripercuoterebbero anche su dataset di tipo "multi".

**Comment by spanezz** [comment]
Corretto: se uso il postprocessing server side, il risultato della query di ogni singolo dataset sono dati binari opachi, e non saprei come fare merge dei vari risultati in un output unico.

In alternativa, faccio postprocessing di tutto client-side, e alla peggio, se il postprocessing è l'estrazione di un singolo punto su un'area, devo trasferire tutte le aree per estrarre quei singoli punti.

**Comment by edigiacomo** [comment]
Fare postprocessing client-side potrebbe essere a volte troppo oneroso (e.g. singolo punto su una serie temporale). Se non ci sono casi d'uso che lo richiedono, si potrebbero semplicemente vietare i postprocessatori nel caso di dataset "multi", come accade nel caso di query su più dataset. Altrimenti, si disabilitano, nei dataset "multi", i postprocessatori che potrebbero essere troppo onerosi.

**Comment by brancomat** [comment]
Il postprocessing no, non l'avevo considerato (cit)

Dunque: uno degli scopi principali della proposta era di mascherare la complessità di alcuni dataset sparpagliati per esigenze sistemistiche ma di fatto analoghi per dati contenuti.

Ad esempio dataset storico con:
- il pezzo recentissimo su arkiserver in dr
- il pezzo meno recente in arkiserver su nas blasonato
- il pezzo più anziano in arkiserver su nas della mutua

Questa roba idealmente si ripercuoterebbe anche in realtà come arkiweb, dove c'è abbondante uso dei postprocessatori, e, in generale nel momento in cui metti in pista un dataset del genere il fatto di avere un comportamento sostanzialmente diverso (o assente) del postprocessing temo creerebbe più confusione che altro, non so.

**Comment by spanezz** [comment]
Se i postprocessatori sono necessari, in un caso come quello di un dataset storico splittato su vari server/storage, l'unico modo di postprocessare temo sia farlo client side.

Per fare un esempio, supponi di avere un postprocessatore che calcola la temperatura media su tutti i bufr risultanti da una query: se postprocessi 3 pezzi diversi di dataset su 3 macchine diverse, ottieni 3 numeri.

Nell'esempio della media, si potrebbe pensare a postprocessatori che restituiscono dati intermedi (tipo somma dei valori e numero di valori) e postprocessatori client-side che li mettono soltanto assieme, e farci su un lavoro di design su come riorganizzare tutto il discorso postprocessazione di conseguenza.

Altrimenti, con gli strumenti che abbiamo adesso, temo che davvero l'unica cosa che funzioni sia o querare un dataset alla volta, o trasferire tutti i dati al cliene e postprocessare lí.

**Comment by spanezz** [comment]
In alternativa, possiamo prevedere due tipi di postprocessatori: map e reduce. I postprocessatori map girano server side e producono json. I postprocessatori reduce girano client side e calcolano il risultato finale dai json ricevuti dai vari server.

(https://en.wikipedia.org/wiki/MapReduce)

**Comment by edigiacomo** [comment]
Questa cosa è bellissima e molto interessante e tra l'altro di questa esigenza ne parlavamo proprio qualche giorno fa io, @brancomat e @dcesari

**Comment by spanezz** [comment]
Parliamone. Potete farmi una piccola cernita di esempi di postprocessazioni che beneficierebbero di una struttura del genere?

**Comment by edigiacomo** [comment]
Questa issue è stata chiusa per inattività. Nel caso in cui sia un argomento ancora rilevante, si prega di riaprirla con una motivazione che tenga conto delle modifiche applicate nel corso degli anni al progetto.
