### ISSUE TITLE
test failures with arkimet 1.10

### ISSUE THREAD

**Issue by brancomat** [ARPA-SIMC/arkimet#161]
several maintenance related tests fail:

https://travis-ci.org/ARPA-SIMC/arkimet/jobs/467929467#L2561

(or see logs attached)
[testfailures.txt](https://github.com/ARPA-SIMC/arkimet/files/2681014/testfailures.txt)

**Comment by spanezz** [comment]
I can reproduce it here. I wondered why when I pushed the fixes last time I was sure all the tests passed.

**Comment by spanezz** [comment]
Fixed on my side and pushed. Let's see what the CI says...

**Comment by spanezz** [comment]
CI says it's fixed in master \o/
