### ISSUE TITLE
arki-xargs exit at first error

### ISSUE THREAD

**Issue by pat1** [ARPA-SIMC/arkimet#167]
I am not sure this is a bug or a feature ... but as result now I lost messages.

cat somebufr.bufr |arki-query --stdin=bufr --inline "" | arki-xargs -n 1 grep NONE
cannot run grep: process returned exit status 256

when command executed by arki-xargs exit with error the successive messages are ignored and the error message report "256" as constant value (the exit code of grep is ignored)

with no error every works well:
cat 01.bufr |arki-query --stdin=bufr --inline "" | arki-xargs -n 1 grep -v NONE
Binary file /tmp/arki-xargs.WrrSPG matches
Binary file /tmp/arki-xargs.XOSeN7 matches
Binary file /tmp/arki-xargs.ztN0Ky matches
Binary file /tmp/arki-xargs.HH80IZ matches
Binary file /tmp/arki-xargs.s9BjHq matches
Binary file /tmp/arki-xargs.d9cRFR matches
Binary file /tmp/arki-xargs.gKpDEi matches
Binary file /tmp/arki-xargs.jzlFDJ matches
Binary file /tmp/arki-xargs.c3W2Ca matches
Binary file /tmp/arki-xargs.9UAGCB matches
Binary file /tmp/arki-xargs.aXhBC2 matches
Binary file /tmp/arki-xargs.HxDLCt matches
Binary file /tmp/arki-xargs.S2N9CU matches
Binary file /tmp/arki-xargs.hdnMDl matches
Binary file /tmp/arki-xargs.O1hDEM matches
Binary file /tmp/arki-xargs.9DaIFd matches
Binary file /tmp/arki-xargs.wjR1GE matches
Binary file /tmp/arki-xargs.gtBAI5 matches
Binary file /tmp/arki-xargs.K7bpKw matches
Binary file /tmp/arki-xargs.IPhuMX matches
Binary file /tmp/arki-xargs.u0jPOo matches
Binary file /tmp/arki-xargs.ywUpRP matches
Binary file /tmp/arki-xargs.4lXfUg matches
Binary file /tmp/arki-xargs.s49rXH matches
Binary file /tmp/arki-xargs.zBmW08 matches
Binary file /tmp/arki-xargs.sm7H4z matches
Binary file /tmp/arki-xargs.VqMM80 matches
Binary file /tmp/arki-xargs.UkIads matches
Binary file /tmp/arki-xargs.vj5WhT matches
Binary file /tmp/arki-xargs.hE29mk matches
Binary file /tmp/arki-xargs.QMmAsL matches
Binary file /tmp/arki-xargs.Npdhyc matches
Binary file /tmp/arki-xargs.QmykED matches
Binary file /tmp/arki-xargs.D7NBK4 matches
Binary file /tmp/arki-xargs.DSf6Qv matches
Binary file /tmp/arki-xargs.G7QNXW matches
Binary file /tmp/arki-xargs.dDDI4n matches
Binary file /tmp/arki-xargs.FGzQbP matches
Binary file /tmp/arki-xargs.1dEbjg matches
Binary file /tmp/arki-xargs.VKCKqH matches
Binary file /tmp/arki-xargs.8sUyy8 matches
Binary file /tmp/arki-xargs.pnsCGz matches
Binary file /tmp/arki-xargs.8l4UO0 matches
Binary file /tmp/arki-xargs.e6itXr matches
Binary file /tmp/arki-xargs.JNHh6S matches
Binary file /tmp/arki-xargs.yRrlfk matches
Binary file /tmp/arki-xargs.QXIEoL matches

**Comment by edigiacomo** [comment]
I always considered it a feature: if something goes wrong, the command stops immediately.

If you want to ignore the exit statuses, you can wrap your command inside a script:

```
$ echo <<EOF > mygrep.sh
#!/bin/bash
# File mygrep.sh
grep NONE
exit 0
EOF
$ chmod ugo+x mygrep.sh
$ cat somebufr.bufr | arki-query --stdin=bufr --inline "" | arki-xargs -n 1 ./mygrep.sh
```

**Comment by brancomat** [comment]
How is this production blocking? Did it change its behaviour compared to previous versions? If not please change it to "devel blocking".

**Comment by pat1** [comment]
Tranquilli, ho messo production blocking sottoposta a review.
Il problema si è evidenziato dopo anni di funzionamento corretto e sto cercando di capire esattamente a cosa sia dovuto.
Si è passati dal server RMAP su Fedora 20 a server RMAP su Centos7 in Lepida.
Posso recuperare le versioni esatte passata e presente se necessario, ma oltre a arkimet sono cambiate altre 1000 e 1000 cose.
La seconda configurazione è stata testata per circa un anno, ma alcuni problemi si evidenziano solo quando il tutto diventa veramente operativo.
Cosa considerare operativo e cosa no mi pare sia ampiamente in discussione al SIMC (vedi gruppo COCO) quindi fare una review e togliete i tag che ritenete opportuni.
Il risultato netto è che ci sono stati nelle ultime 48 ore già due fault della rete cluster per un totale di circa 12 ore; sotto i dettagli tecnici.

**Comment by pat1** [comment]
il comando è eseguito da python in modalità daemon controllato da monit.
Il comportamenti aspettati potrebbero essere due:
a) uscita per errore del daemon (che essendo su stream poi porta a perdita di dati ma a notifica)
b) segnalazione dell'errore nei log e ignorare l'errore (perdita minima di dati ma non notifica)

al momento della segnalazione del bug l'errore non terminava il daemon, dava un messaggio errato nei log e terminava qualsiasi elaborazione successiva.
Ora con una strada simile a quella suggerita da Emanuele abbiamo circa una soluzione b)

Il problema è che pare una soluzione molto instabile, mi pare ci siano situazioni in cui b) non sia stabile e si riconduca alla situazione daemone attivo e messaggi non elaborati.
Questo il daemon:
https://github.com/r-map/rmap/blob/python3/python/mqtt2dballed
questo toamqp modificato per non dare mai errore:
https://github.com/r-map/rmap/blob/python3/python/toamqp

Se il problema interessa solo me fate review e chiudete il bug.

**Comment by edigiacomo** [comment]
Non ho capito: è instabile perché nonostante la modifica suggerita (i.e. uscire sempre con status 0) arki-xargs termina lo stesso senza processare tutti i messaggi? In tal caso è un bug, ma è necessario trovare un caso replicabile.

**Comment by pat1** [comment]
non riesco a replicare facilmente; diciamo che su migliaia di elaborazioni (e spesso parecchie al secondo) basta un errore una tantum per perdere permanentemente messaggi. L'ultima volta potrebbe essere stato a causa di un aggiornamento e indisponibilità temporanea dell'eseguibile o indisponibilità temporanea del file system; in questi rari casi sarebbe opportuno forse terminare con errore il daemon e attendere il restart. Ma forse questo è un problema della costruzione della pipe in python. Comunque se il caso non interessa il postprocessing di arkimet in generale chiudo il bug e limito il problema al mio caso.

**Comment by pat1** [comment]
comunque il messaggio:
process returned exit status 256
è forviante.

**Comment by edigiacomo** [comment]
@pat1 propongo di chiudere questa issue e

1. Aprirne un'altra se riesci a replicare il problema
2. Aprirne comunque un'altra in cui possiamo discutere degli exit status di `arki-xargs`

**Comment by edigiacomo** [comment]
@pat1 chiudo la issue, perché si è finiti a parlare di due cose che non sono l'argomento della issue.

1. Se pensi che il problema del tuo demone che si perde i messaggi sia causato da un bug di arkimet, apri una nuova issue, con info su come replicare il problema.
2. Per quanto riguarda invece gli exit status, direi di parlarne in una issue nuova relativa ad `arki-xargs`, che ti chiedo di aprire in modo che tu e @spanezz possiate confrontarvi un po' come ti ha proposto per gli exit status di `arki-scan` (https://github.com/ARPA-SIMC/arkimet/issues/177#issuecomment-515917006).
