### ISSUE TITLE
arki-check --zip and --tar don't work on the whole .archive directory

### ISSUE THREAD

**Issue by brancomat** [ARPA-SIMC/arkimet#168]
As stated in #131 `--zip` and `--tar` options should work on the whole `.archive` directory, right now they seem to work only in `.archive/last`

**Comment by spanezz** [comment]
I added tests to make sure that --zip and --tar work on non-`last` archive directories and they seem to.

Can you give me instructions to replicate the behaviour that you are seeing?

**Comment by spanezz** [comment]
I found the issue: in the datasets you are using, there is a `<name>.summary` file next to the `<name>` archive directory. Arkimet sees it, and assumed is is a readonly archive that has been temporarily brought online, and won't touch it when checking.

Remove the `<name>.summary` file and you'll see that arkimet does start zipping/tarring those directories.

Is there a specific reason for generating that summary file?

**Comment by brancomat** [comment]
My bad... as stated by the documentation, placing a `<name>.summary` besides `<name>` archive has the effect to mark the archive readonly:
https://github.com/ARPA-SIMC/arkimet/blob/master/doc/ds-archive.md

Removing the `<name>.summary` files solves the issue.

For the record, it's probably better to copy summary files outside archive segments only before putting the segment offline.
