### ISSUE TITLE
"duplicate detected while reordering segment" on iseg

### ISSUE THREAD

**Issue by edigiacomo** [ARPA-SIMC/arkimet#171]
```
$ arki-check -f --filter='reftime:=2001-01' /arkivio/arkimet/dataset/spdsra
spdsra:2001/01-31.vm2: item at offset 81399 is wrongly ordered before item at offset 82053
spdsra: check 30 files ok

$ arki-check -fr --filter='reftime:=2001-01' /arkivio/arkimet/dataset/spdsra
spdsra:2001/01-31.vm2: item at offset 81399 is wrongly ordered before item at offset 82053
duplicate detected while reordering segment
```

But I don't understand what the problem is and how to solve it.

**Comment by spanezz** [comment]
This is an example of conflicting duplicate data:
```
200101312300,12475,161,10.7308,,,
200101312300,12475,161,0.107308,,,000000000
```
checking with arki-query (for example, `arki-query --dump 'reftime:=2001-01-31 23:00'`) (look for the tail of the lines in the Value metadata) you can see that they give identical metadata.

In the index, however, the area data is different:

```
sqlite3 01-31.vm2.index
sqlite> select mduniq.area, md.data, hex(sub_area.data) from md join mduniq on md.uniq = mduniq.id join sub_area on sub_area.id=mduniq.area where md.data like '%7308,,%';
45|10.7308,,,|03000030BB056964656E74853132343735036C617442430F3D036C6F6E4211ED2B0372657086737064737261
73|0.107308,,,000000000|03000030BB036C617442430F3D036C6F6E4211ED2B0372657086737064737261
```

I suspect that, given that the index compares areas bit-by-bit, and the VM2 area implementations compares them only by ID, at some point the area data changed for that ID, and the index is not able to see that they are the same.

Ideally, comparison of VM2 areas should have the same behaviour as bit-by-bit comparison of their serialized values.

We might need to redesign how VM2 areas are serialized/matched to restore this invariant.

**Comment by edigiacomo** [comment]
Thank you! I will open an issue about the serialization and matching of VM2 area and product.

**Comment by edigiacomo** [comment]
I reopen this issue, because the problem still persists (or it came back after the fix).

With arkimet v1.28-1 and a sample dataset [cer.zip](https://github.com/ARPA-SIMC/arkimet/files/5074680/cer.zip)


```
$  arki-check cer
cer:2020/02-16.vm2: item at offset 3952 is wrongly ordered before item at offset 12549
cer:2020/02-16.vm2: should be packed
cer: check 0 files ok, 1 file should be packed

$ arki-check -f cer
cer:2020/02-16.vm2: item at offset 3952 is wrongly ordered before item at offset 12549
cer: check 0 files ok

$ arki-check -f cer
cer:2020/02-16.vm2: item at offset 3952 is wrongly ordered before item at offset 12549
cer: check 0 files ok

[edg@oliva tmp]$ arki-check -fr cer
cer:2020/02-16.vm2: item at offset 3952 is wrongly ordered before item at offset 12549
Traceback (most recent call last):
  File "/usr/bin/arki-check", line 11, in <module>
    main()
  File "/usr/bin/arki-check", line 7, in main
    sys.exit(Check.main())
  File "/usr/lib/python3.8/site-packages/arkimet/cmdline/base.py", line 75, in main
    cmd.run()
  File "/usr/lib/python3.8/site-packages/arkimet/cmdline/check.py", line 125, in run
    arki_check.repack()
RuntimeError: duplicate detected while reordering segment
```

The only workaround that I found is to remove the index and then rescan and repack the dataset:

```
$ rm cer/2020/02-16.vm2.index

$ arki-check -f cer
cer:2020/02-16.vm2: segment found on disk with no associated index data
cer:2020/02-16.vm2: rescanned
cer: check 0 files ok, 1 file rescanned

$ arki-check -fr cer
cer:2020/02-16.vm2: item at offset 3952 is wrongly ordered before item at offset 12549
cer:2020/02-16.vm2: repacked (843 freed)
cer: repack 0 files ok, 1 file packed, 843 total bytes freed

$ arki-check -f cer
cer: check 1 file ok
```

**Comment by spanezz** [comment]
Intanto ho trovato il dato duplicato:
```
$ grep 202002162300,5305,161,5.31,,,000000000 cer/2020/02-16.vm2
202002162300,5305,161,5.31,,,000000000
202002162300,5305,161,5.31,,,000000000
```

Ora cerco di capire perché non lo trova lui

**Comment by spanezz** [comment]
Questi i metadati corrispondenti:
```
Source: BLOB(vm2,/home/enrico/lavori/arpa/arkimet/cer/2020/02-16.vm2:12843+38)
Product: VM2(161, bcode=B13215, l1=0, l2=0, lt1=1, lt2=0, p1=0, p2=0, tr=254, unit=m)
Reftime: 2020-02-16T23:00:00Z
Area: VM2(5305,lat=4492834, lon=1143941, rep=cer)
Value: 5.31,,,000000000
Note: [2020-02-16T23:36:06Z]Scanned from CAE_20200216233401860283890.VM2

Source: BLOB(vm2,/home/enrico/lavori/arpa/arkimet/cer/2020/02-16.vm2:13458+38)
Product: VM2(161, bcode=B13215, l1=0, l2=0, lt1=1, lt2=0, p1=0, p2=0, tr=254, unit=m)
Reftime: 2020-02-16T23:00:00Z
Area: VM2(5305,lat=4492834, lon=1143941, rep=cer)
Value: 5.31,,,000000000
Note: [2020-03-04T12:12:54Z]Scanned from CAE_20200304121001983852818_001.VM2
```

**Comment by spanezz** [comment]
sqlite has:
```
sqlite> select * from md where offset in (12843, 13458);
12843|38|2��y,Scanned from CAE_20200216233401860283890.VM2|2020-02-16 23:00:00|1|1|5.31,,,000000000
13458|38|6���60Scanned from CAE_20200304121001983852818_001.VM2|2020-02-16 23:00:00|9|1|5.31,,,000000000
sqlite> select * from mduniq where id in (1, 9);
1|1|1
9|1|8
sqlite> select id, hex(data) from sub_area where id in (1, 8);
1|03000014B9036C617442448E22036C6F6E421174850372657083636572
8|03000014B9
sqlite> select id, quote(data) from sub_area where id in (1, 8);
1|X'03000014B9036C617442448E22036C6F6E421174850372657083636572'
8|X'03000014B9'
```

**Comment by spanezz** [comment]
A VM2 area has a station ID and a ValueBag with other data filled with it. Arkimet compares areas only by station id, but sqlite does a bit by bit comparison. Given that the two serialized areas begin with the same bytes, and one is longer, I supposed one was serialized with only the station ID, and the other with the full information.

It would be interesting to serialize binary areas without the derived values, to reduce index sizes and make them bit-by-bit comparable. Would this break something, that you can think of?

**Comment by spanezz** [comment]
(note, this doesn't seem to look like a regression after all, but a different issue with the same error message)

**Comment by edigiacomo** [comment]
> It would be interesting to serialize binary areas without the derived values, to reduce index sizes and make them bit-by-bit comparable. Would this break something, that you can think of?

No, I don't think so - as far as the derived values can be used in arki-query and are serialized in the summary.

**Comment by spanezz** [comment]
Interestingly, this seems to have already been fixed in #172, and indeed creating a dataset with a current arkimet, I see the VM2 serialized in index tables without the extra information

**Comment by spanezz** [comment]
Could it be that the datasets were previously written with an older (pre-#172) version of arkimet?

**Comment by edigiacomo** [comment]
To dispel any doubt, I removed all the `.index` file in `cer` dataset and rescanned/repacked all the data. Let's see if this problem comes back.

**Comment by edigiacomo** [comment]
> To dispel any doubt, I removed all the `.index` file in `cer` dataset and rescanned/repacked all the data. Let's see if this problem comes back.

Today I rescanned and repacked all VM2 datasets (`arkimet-1.29-1`). I'll leave the issue open for a couple of months to see if the problem still persists.
