### ISSUE TITLE
VM2 should be indexed by id only

### ISSUE THREAD

**Issue by edigiacomo** [ARPA-SIMC/arkimet#172]
VM2 should be indexed by id only, but it should be possible to match against the "derived values" (e.g. "area:VM2:lat=1212345" or "product:VM2:bcode=B12101" or "area:bbox ...") and to use them in the Lua script executed when using the `--annotate` option.

See #171.

**Comment by spanezz** [comment]
I committed a fix. I can't think of a way to unit test it: to do so I'd need to have `arki::utils::vm2::get_station` return two different values at two different times during testing, and I would not know how.

Can you please either try it out to see if it works, or let me know if there's a way to mock the result of `get_station`/`get_variable` during tests?

**Comment by edigiacomo** [comment]
In bbbac9d I changed (in a backward compatible way) the signature of VM2 utility functions.

I implemented a test for `arki::utils::vm2::get_station` too, I hope I have interpreted correctly your question.

Note: maybe I'm missing something but it seems that `ensure(condition)` never fails. In `arki_utils_vm2.get_station` test I've used `wassert(actual(value) == expected)`.

**Comment by edigiacomo** [comment]
Close in ca539a9622aa89290d487581f27544494723618d
