### ISSUE TITLE
all build fails on current master

### ISSUE THREAD

**Issue by brancomat** [ARPA-SIMC/arkimet#173]
Full build:
https://travis-ci.org/ARPA-SIMC/arkimet/builds/520648534

CentOS7:
https://travis-ci.org/ARPA-SIMC/arkimet/jobs/520648535
```
utils/zip.cc:211:5: error: 'zip_source_t' was not declared in this scope
```

F28 (and F29):
https://travis-ci.org/ARPA-SIMC/arkimet/jobs/520648536
```
dataset/iseg-test.cc:74:41: error: invalid use of incomplete type 'struct arki::types::source::Blob'
```

**Comment by spanezz** [comment]
Fixed, it looks all green now, except Fedora 30
