### ISSUE TITLE
zstd seekable compression with shared dictionary

### ISSUE THREAD

**Issue by spanezz** [ARPA-SIMC/arkimet#174]
The [zstandard comperssion library](https://facebook.github.io/zstd/) has a good compression ratio and allows to compress various chunks using a precomputed dictionary.

This means that a big `.bufr` segment could be compressed building a shared dictionary that keeps into account redundancy between each individual bufr, but with each compressed bufr seekable individually.

I made some tests (code attached) using one 10Mb BUFR file taken from an archive, and these are the results, compared to other compression systems:
```
seekable zstd: 3047307
test.zip: 6031797
test.tar.gz: 3351371
test.tar.xz: 1907308
test.gz: 2703495
test.xz: 1760396
05-02.bufr: 10043968
```
Note that of those files, besides the compressed zstd, only the uncompressed `.bufr` and the `.zip` file are seekable.

Pros of this approach:

* compression similar to gzip but immediately seekable
* decompression should be very fast
* compressed files can be repacked freely without decompression, and also appended. The compression efficiency of appending depends on how much the appended data is similar to the existing data

Cons of this approach:

* compression is slow
* the resulting data segment would use a custom arkimet format, which cannot be unpacked with standard tools
* it needs `libzstd-dev`

Would it be a route worth exploring?

[zstd-tests.tar.gz](https://github.com/ARPA-SIMC/arkimet/files/3277447/zstd-tests.tar.gz)

**Comment by spanezz** [comment]
I tarred the wrong files, and lost the zstd source. I'll redo it as soon as I can, also because I want to test whether seekable zstd files created by me can actually be uncompressed with zstd standard tools.

**Comment by spanezz** [comment]
Here's the updated zip that actually works: [zstd-test.tar.gz](https://github.com/ARPA-SIMC/arkimet/files/3278129/zstd-test.tar.gz)

Updates to the pros and cons:

Compression can be fast, choosing a different compression level.

The resulting format can be read with zstd: `zstd -D test.dct -d test.zst` will decompress the file correctly.

I could not find how to bundle the dictionary with the file, but they can be saved separately. This also opens the possibility to have a per-directory dictionary.

**Comment by brancomat** [comment]
> Would it be a route worth exploring?

Our main storage space offenders are grib archives, it would be interesting to see the compression ratio in this cases.

`arkimet6` hosts the archives, in the internal page  https://simc.arpae.it/arkidataset/ you can see the daily increment, best test cases could be  `cosmo_2I_arc` and `cosmo_5M_ita_arc` datasets.

**Comment by brancomat** [comment]
As discussed yesterday, at the moment the most attractive scenario for zstd use could be compressing grib (or odim?) datasets, provided that zstd compression significantly outperforms already implemented zip/gunzip compressions.

In short, we need to test zstd compression ratio on grib and odim files, and since at the moment this isn't a priority I'm adding the "help wanted" label
