### ISSUE TITLE
Remove arki-scan/arki-query `--targetfile`

### ISSUE THREAD

**Issue by spanezz** [ARPA-SIMC/arkimet#180]
L'opzione `--targetfile` di `arki-query` e `arki-scan` viene usata?

Mi sto chiedendo se portarla da Lua a Python, o se toglierla del tutto.

**Comment by dcesari** [comment]
Non la conoscevo per cui non l'avevo mai usata, ora che lo dici ci faccio un pensiero :-), a parte gli scherzi per me puoi eliminarla, credo si possa sempre emulare con una `grib_copy ... [key1][key2]...`

**Comment by spanezz** [comment]
I removed the `--targetfile` code in branch `issue177`
