### ISSUE TITLE
Remove query macro 'gridspace'

### ISSUE THREAD

**Issue by spanezz** [ARPA-SIMC/arkimet#181]
La query macro `expa` so che dovrebbe venire usata. `gridspace` invece, la usa qualcuno o la posso togliere?

**Comment by edigiacomo** [comment]
Io non l'ho mai usato.

**Comment by spanezz** [comment]
Visto che fu creata per l'ISAC e non è mai stata documentata in ARPA, do' per scontato che non sia mai stata usata, e la tolgo.

**Comment by dcesari** [comment]
Confermo che anche di questa non sapevo dell'esistenza.

**Comment by brancomat** [comment]
> Confermo che anche di questa non sapevo dell'esistenza.

+1

**Comment by spanezz** [comment]
I removed the `gridspace` macro in branch `issue177`
