### ISSUE TITLE
Remove `arki-query`/`arki-scan` `--report`

### ISSUE THREAD

**Issue by spanezz** [ARPA-SIMC/arkimet#184]
`arki-query --report` e `arki-scan --report` sono utilizzati?

Gli script Lua di reportistica non vengono toccati dal 2010. Se non sono utilizzati, li rimuovo volentieri.

**Comment by edigiacomo** [comment]
Mai usati.

**Comment by dcesari** [comment]
Anch'io credo di non averli mai usati.

**Comment by spanezz** [comment]
I removed the `--report` option in branch `issue177`
