### ISSUE TITLE
Deprecate ondisk2 datasets

### ISSUE THREAD

**Issue by spanezz** [ARPA-SIMC/arkimet#185]
`iseg` datasets seem to have proven equivalent or superior to `ondisk2`, and `ondisk2` archives have more management and consistency issues than `iseg`.

I'd like to consider `ondisk2` datasets deprecated, and once they are not in use anymore, I'd like to remove their implementation from arkimet, which would make compiling and especially unit testing significantly faster, and reduce the amount of code that needs to be maintained.

Are ondisk2 datasets still in use?

**Comment by pat1** [comment]
I use iseg only

**Comment by dcesari** [comment]
I also have switched to iseg everywhere

**Comment by edigiacomo** [comment]
We still have ~50 ondisk2 datasets (mostly GRIB2). I'd like to switch to iseg, but we have to discuss it.

**Comment by brancomat** [comment]
What @edigiacomo said. `ondisk2` are still widely used, a migration is feasible (while not immediate: there are several aki-servers, and one of them has a pre-iseg arkimet version) but not a priority at the moment.
We could make a medium-term plan for it.

If `iseg` datasets are really equivalent or superior to `ondisk2` (my experience with `iseg` datasets is limited right now) and we all agree to the transition we could start by editing `ondisk2` documentation deprecating the dataset to avoid further prolification of it and maybe add some quick migration guide for existing archives (that could remain in the future to mantain a backward compatibility).

**Comment by spanezz** [comment]
I said equivalent or superior in that I haven't heard of performance issues with iseg, and they have less concurrency issues than ondisk2.

I'd like to deprecate them to reduce the complexity of code that needs to be maintained. It's not at all urgent, though. Meanwhile, good idea, I documented the deprecation in the `ondisk2` documentation.

**Comment by spanezz** [comment]
ondisk2 dataset implementation has been removed in 676e3eaffef0244f573100e1cd87f798c6a56a39

Closing this issue
