### ISSUE TITLE
problema di arki-query su un filesystem esportato in sola lettura

### ISSUE THREAD

**Issue by gianfrancomarras** [ARPA-SIMC/arkimet#186]
Ciao,
come possiamo eseguire il seguente comando su un archivio che sta su un filesystem esportato in sola lettura ?
Il comando è:
developer@rapydo_server:[/arkimet/datasets]: arki-query --json --summary-short --annotate '' lm5

/arkimet/datasets/lm5 failed: cannot open file /arkimet/datasets/lm5/lock: Permission denied
{"items":{"summarystats":{"c":0,"s":0}}}

naturlamente non riesce a creare il "lock", pertanto fallisce.
Un opzione può essere di lanciare il server sull'host remoto, abbiamo altre opzione per superare l'ostacolo?
Ciao
       Gian Franco

**Comment by spanezz** [comment]
Direi che l'unica opzione sia usare arki-server sull'host remoto. `arki-query` ha bisogno di fare lock sui dataset per segnalare a eventuali `arki-check` che probabilmente leggerà dati dal segmento, e `arki-check` si occuperà di postporre eventuali operazioni di repack.

**Comment by gianfrancomarras** [comment]
Abbiamo escluso l'apertura del server in remoto perchè dovrebbe stare su una macchina di calcolo e questo purtroppo non mostra garanzie di affidabilità. Abbiamo allora creato un nuovo utente appartenente allo stesso gruppo. Purtroppo però due utenti dello stesso gruppo si bloccano a vicenda. Entrambi lasciano i lock e pertanto il secondo non può accedervi (forse sbagliamo qualcosa?) anche se il comando risulta terminato (non so se è un problema causato dal fatto che è un filesystem paralleo GPFS?).
Semplicemente se il primo fa una query alla fine non rimuove il lock e pertanto il secondo utente non può acedervi.
Ancor peggio si comporta  il secondo utente, se riesce ad interrogare l'archivio, lascia il lock e in più crea due file, index.sqlite-shm e index.sqlite-wal (per quel poco che so di sqlite questi file dovrebbero essere cancellati alla fine della richiesta). Questi file li crea solamente l'utente appartenente al gruppo ma non l'owner della cartella principale.
Per ripristinare l'archivio e il database alle funzionalità originali cancello questi file ed eventualmente eseguo un arki-check per verificare la consistenza dell'archivio.
Vorrei però evitare tutto questo.

**Comment by spanezz** [comment]
arkimet si aspetta semantiche di file system POSIX piú [Open File Descriptor locks](https://gavv.github.io/articles/file-locks/#open-file-description-locks-fcntl) non è mai stato testato su filesystem GPFS. Come prima cosa suggerirei di fare un make check, esportando TMPDIR a una directory in GPFS, e vedere se passano i test.

I file di lock non vengono rimossi intenzionalmente, per evitare operazioni inutili di creazione e rimozione sul filesystem a ogni operazione: il locking viene effettuato tramite chiamata `fcntl` sul file, e tramite verifica dell'esistenza del file.

I file .wal non bloccano le query, a meno ché il processo che ha aperto il primo .wal non sia ancora in esecuzione con una query aperta. Vedi https://sqlite.org/wal.html alla voce "The WAL file". Se il processo che ha fatto la query invece è uscito ma non ha cancellato il file .wal, mi aspetto che sia crashato, e sarebbe utile avere dettagli del crash.

In generale, arkimet è stato finora progettato e testato per i casi d'uso in ARPA, che prevedono, anche per motivi di performance, accesso a un filesystem locale e trasmissione via rete tramite `arki-server`. Se c'è la necessità di espandere la casistica di ambienti di deploy da supportare, e non funziona out of the box, credo sia il caso di non focalizzarsi sui singoli bug, ma di raccogliere i requisiti dei nuovi casi da supportare e ragionarci per bene.

**Comment by brancomat** [comment]
Fermo restando quanto scritto sopra, i casi d'uso che si stanno delineando legati al progetto mistral al CINECA vanno purtroppo in direzione diversa:

1. la situazione sshfs+gpfs descritta sopra da @gianfrancomarras che al momento sta funzionando anche se in situazione di carico relativo (e se capisco bene in futuro potrà essere sostituita da protocolli http)

1. un secondo archivio con dataset appoggiati su file nfs

Questo secondo scenario quindi non avrebbe sicuramente gli Open File Descriptor locks ma il filesystem sarebbe pseudo-POSIX, stiamo cercando di capire quale potrebbe essere il worst case scenario di questa soluzione, al di là degli aspetti prestazionali (gli indici sqlite su un filesystem di rete non sono una situazione ideale)

Gli aspetti più critici che ipotizzo:

- Andrebbe esternalizzato un qualche sistema per impedire l'importazione di nuovi dati (arki-scan) in contemporanea alle operazioni di controllo e repack degli archivi (arki-check) sullo stesso dataset
- Le arki-query su dataset in fase di modifica (per importazione nuovi dati o repack) potrebbero risultare incomplete o fallire

**Comment by edigiacomo** [comment]
Questa issue è stata chiusa per inattività. Nel caso in cui sia un argomento ancora rilevante, si prega di riaprirla con una motivazione che tenga conto delle modifiche applicate nel corso degli anni al progetto.
