### ISSUE TITLE
[arki-check] log issues in a repack with duplicates

### ISSUE THREAD

**Issue by brancomat** [ARPA-SIMC/arkimet#187]
Let's say I have a odim dataset with daily updates, `replace=yes` is set and `unique` fields are defined. `archive` option is not set:

```
description = Probability of Hail (POH), odim format (Opera)
filter = origin:ODIMH5,,,itspc or ODIMH5,,,itgat;product:ODIMH5,IMAGE,,; task:POH
index = reftime,origin,product
replace = yes
step = daily
type = ondisk2
unique = reftime,origin
```
Let's say I have to reimport some data with older reftime because of some validation/correction process.

So I import the old data and launch a repack. I was expecting a ton of warning about duplicates but I only get a lot of `wrongly ordered` warning each one followed by an alarming `repacked (0 freed)`.
In the recap at the end of the process I see:
`radar_POH: repack 35 files ok, 94 files packed, 716800 total bytes freed`

Further analysis on the dataset (thanks @edigiacomo) suggests data was correctly replaced.

Is it possible that the `wrongly ordered` warning wins over the duplicate warning? (since indeed at the end of the import of the old data the dataset was wrongly ordered)

I won't say it's a bug but I just found the log slightly misleading.

Full log attached: 
[arkilog.txt](https://github.com/ARPA-SIMC/arkimet/files/3583184/arkilog.txt)

arkimet-1.14-1.x86_64

**Comment by spanezz** [comment]
I am not sure I am able to investigate on this without being able to reproduce the issue. If at some point you see a similar behaviour and have a way to reproduce it, I'll be happy to look into it

**Comment by brancomat** [comment]
There is indeed some problem in the logs, this happened after importing about 900Mb of duplicated data:
```
[arkimet@arkimet5 prodotti_odim]$ du -hs /arkivio/arkimet/dataset/radar_POH/
1,8G	/arkivio/arkimet/dataset/radar_POH/
[arkimet@arkimet5 prodotti_odim]$ arki-check -f -r /arkivio/arkimet/dataset/radar_POH/ | tee import.log
(see import.log attached)
[arkimet@arkimet5 prodotti_odim]$ du -hs /arkivio/arkimet/dataset/radar_POH/
960M	/arkivio/arkimet/dataset/radar_POH/
```
the only mention of bytes freed is at the end of [import.log](https://github.com/ARPA-SIMC/arkimet/files/3616510/import.log) :
```
radar_POH: repack 6 files ok, 133 files packed, 3284992 total bytes freed
```

(I'm leaving this assigned to me as a reminder for me to create a smaller test to reproduce)

**Comment by brancomat** [comment]
I created a small test: 
[issue187.tar.gz](https://github.com/ARPA-SIMC/arkimet/files/3646498/issue187.tar.gz)
(it imports twice some odim data printing the dataset size and the it launches `arki-check` on it)

There are two separate issues:

The first one: at least until `arkimet-1.14` the bytes freed information is off:
```
radar_POH:2019/05-03.odimh5: item at offset 409 is wrongly ordered before item at offset 570
radar_POH:2019/05-03.odimh5: segment contains 288 file(s) that the index does now know about
radar_POH:2019/05-03.odimh5: repacked (0 freed)
radar_POH: repack: running VACUUM ANALYZE on the dataset index
radar_POH: repack: rebuilding the summary cache
radar_POH: repack 0 files ok, 1 file packed
```
However, this is fixed in newer versions of arkimet (included the `issue177` branch):
```
radar_POH:2019/05-03.odimh5: item at offset 342 is wrongly ordered before item at offset 549
radar_POH:2019/05-03.odimh5: segment contains 288 file(s) that the index does now know about
radar_POH:2019/05-03.odimh5: repacked (4059648 freed)
radar_POH: repack: running VACUUM ANALYZE on the dataset index
radar_POH: repack: rebuilding the summary cache
radar_POH: repack 0 files ok, 1 file packed, 4059648 total bytes freed
```

The second issue is that there are no mentions at all of duplicate data, only of the wrong order.
It's a minor issue, still it would be ideal to have that kind of information in the logs.

**Comment by spanezz** [comment]
Output stopped at the first issue that was found that caused the segment to be marked for repack. I changed it to print all the issues instead, and to identify possibly deleted content explicitly as gaps

**Comment by brancomat** [comment]
This is the final output of the small test above on arkimet 1.17:
```
radar_POH:2019/05-03.odimh5: item at offset 342 is wrongly ordered before item at offset 549
radar_POH:2019/05-03.odimh5: segment contains 288 file(s) that the index does now know about
radar_POH: check 0 files ok
radar_POH:2019/05-03.odimh5: item at offset 342 is wrongly ordered before item at offset 549
radar_POH:2019/05-03.odimh5: segment contains 288 file(s) that the index does now know about
radar_POH:2019/05-03.odimh5: repacked (4059648 freed)
radar_POH: repack: running VACUUM ANALYZE on the dataset index
radar_POH: repack: rebuilding the summary cache
radar_POH: repack 0 files ok, 1 file packed, 4059648 total bytes freed
```

Unfortunately there is still no mention about duplicate data.

**Comment by spanezz** [comment]
Ok, I had another look. Currently the checker does not detect if there are holes in the file: only if the data known by the index starts at the beginnig, ends at the end, and each data known by the index starts where the previous one stops.

If there are duplicates (and duplicates can't fit in the index, so old duplicate data is just data not known by the index), then there is some data in the index that does not start where the previous data in the index ended.

To identify the amount of space in the segment that is not accounted for in the index, I could add another check that looks at the size of the segment and subtracts the sum of the sizes of data in the index, and reports the amount of bytes that would be saved by a repack.

It would be impossible for segments (except for dir segments, where it would actually be possible) to tell how many duplicate items there are, without rescanning the data not known by the index.

I would guess that that's not what you need, and the main information of importance would be how much data would be recovered by a repack, to decide if it's time to schedule a repack or if it would be wasted time.

Would that be correct?

**Comment by brancomat** [comment]
Not really, at the moment there are scheduled repacks for almost every dataset in production regardless of the amount of data recovered or generic I/O considerations.
Manual repacks are generally run following some equally manual operation (e.g.: overwriting data already imported) or for diagnostic purpose.

Use case scenario: let's say I have a dataset thay _may_ have duplicate data but I'm fairly certain that has no duplicate in the last 10 days; seeing a warning for duplicate data in that days could be a symptom of some issue in the import procedure.
For some reason I was convinced that in previous versions arkimet warned when a repack would found duplicate data and I just thought it would be a relevant/useful information that could easily be restored.

Since that's not the case, it's not really a feature request (let's avoid further burdening of `arki-check`).
I'm closing the issue but I'm pinging @edigiacomo and @dcesari on the issue just to be sure we're all on the same page

**Comment by spanezz** [comment]
Ack. Meanwhile I poked around the code and pushed this update in arki-check output:
```
radar_POH:2019/05-03.odimh5: possibly deleted data found not tracked by indexed: 126864b would be freed by a repack
```
I guess if your need is just to know of the presence of duplicates, the presence of that notice in the output might alert you of exactly that: deleted data happens only in case of duplicates or in case of removals (`arki-check --remove`)

**Comment by dcesari** [comment]
> Since that's not the case, it's not really a feature request (let's avoid further burdening of `arki-check`). I'm closing the issue but I'm pinging @edigiacomo and @dcesari on the issue just to be sure we're all on the same page

I do not have a compelling need for this feature (if that was you question), thanks.

**Comment by edigiacomo** [comment]
> I do not have a compelling need for this feature (if that was you question), thanks.

Me neither, we can close the issue.
