### ISSUE TITLE
Example of slow query

### ISSUE THREAD

**Issue by mnuccioarpae** [ARPA-SIMC/arkimet#188]
As requested, here is a slow query for @spanezz. The timerange can be at most one year, because it queries from the beggining of the year. 

    arki-query --data 'reftime:>=2019-01-02,<=2019-05-31,=00:00:00
        area:VM2,1 or VM2,10 or VM2,10141 or VM2,11 or VM2,11099 or VM2,11103 or VM2,11104 or VM2,11105 or VM2,11109 or VM2,11110 or VM2,11112 or VM2,11240 or VM2,11241 or VM2,11242 or VM2,11243 or VM2,11244 or VM2,11245 or VM2,11246 or VM2,11247 or VM2,11248 or VM2,11249 or VM2,11250 or VM2,11251 or VM2,11252 or VM2,11253 or VM2,11254 or VM2,11282 or VM2,12072 or VM2,12159 or VM2,12180 or VM2,12234 or VM2,12251 or VM2,12261 or VM2,12262 or VM2,12289 or VM2,12295 or VM2,12296 or VM2,12307 or VM2,12318 or VM2,12323 or VM2,12324 or VM2,12334 or VM2,12373 or VM2,12386 or VM2,12393 or VM2,12403 or VM2,12411 or VM2,12459 or VM2,12461 or VM2,12465 or VM2,12466 or VM2,12467 or VM2,12468 or VM2,12469 or VM2,12470 or VM2,12471 or VM2,12472 or VM2,12473 or VM2,12474 or VM2,12475 or VM2,12476 or VM2,12477 or VM2,12479 or VM2,12480 or VM2,12618 or VM2,12619 or VM2,12633 or VM2,12635 or VM2,12637 or VM2,12639 or VM2,12669 or VM2,12695 or VM2,12696 or VM2,12697 or VM2,12698 or VM2,12699 or VM2,12700 or VM2,12701 or VM2,12710 or VM2,12712 or VM2,12715 or VM2,12806 or VM2,12847 or VM2,12863 or VM2,12865 or VM2,12866 or VM2,12867 or VM2,12868 or VM2,12869 or VM2,12870 or VM2,12871 or VM2,12872 or VM2,12873 or VM2,12874 or VM2,12875 or VM2,12876 or VM2,12877 or VM2,12878 or VM2,12879 or VM2,12921 or VM2,12948 or VM2,12975 or VM2,12976 or VM2,12980 or VM2,12988 or VM2,12992 or VM2,12994 or VM2,12997 or VM2,13000 or VM2,13023 or VM2,13034 or VM2,13169 or VM2,13183 or VM2,14025 or VM2,14026 or VM2,14027 or VM2,14028 or VM2,14029 or VM2,14030 or VM2,14101 or VM2,14327 or VM2,14328 or VM2,14375 or VM2,14377 or VM2,2 or VM2,2281 or VM2,2282 or VM2,2283 or VM2,2284 or VM2,2285 or VM2,2286 or VM2,2287 or VM2,2288 or VM2,2289 or VM2,2290 or VM2,2291 or VM2,2292 or VM2,2293 or VM2,2294 or VM2,2295 or VM2,2296 or VM2,2297 or VM2,2298 or VM2,2299 or VM2,2300 or VM2,2301 or VM2,2302 or VM2,2303 or VM2,2304 or VM2,2305 or VM2,2306 or VM2,2307 or VM2,2308 or VM2,2309 or VM2,2310 or VM2,2311 or VM2,2312 or VM2,2313 or VM2,2979 or VM2,2980 or VM2,2981 or VM2,2984 or VM2,2985 or VM2,2986 or VM2,2988 or VM2,2989 or VM2,2990 or VM2,2991 or VM2,2993 or VM2,2994 or VM2,2995 or VM2,2997 or VM2,2998 or VM2,2999 or VM2,3 or VM2,3000 or VM2,3001 or VM2,3004 or VM2,3007 or VM2,3008 or VM2,3011 or VM2,3012 or VM2,3013 or VM2,3014 or VM2,3015 or VM2,3016 or VM2,3017 or VM2,3018 or VM2,3019 or VM2,3020 or VM2,3021 or VM2,3022 or VM2,3023 or VM2,3024 or VM2,3025 or VM2,3026 or VM2,3028 or VM2,3029 or VM2,3030 or VM2,3031 or VM2,3032 or VM2,3033 or VM2,3035 or VM2,3036 or VM2,3037 or VM2,3038 or VM2,3039 or VM2,3040 or VM2,3041 or VM2,3042 or VM2,3043 or VM2,3044 or VM2,3045 or VM2,3046 or VM2,3047 or VM2,3048 or VM2,3049 or VM2,3050 or VM2,3051 or VM2,3052 or VM2,3053 or VM2,3054 or VM2,3055 or VM2,3056 or VM2,3057 or VM2,3058 or VM2,3060 or VM2,3061 or VM2,3062 or VM2,3064 or VM2,3077 or VM2,3078 or VM2,3080 or VM2,3094 or VM2,3096 or VM2,3097 or VM2,3099 or VM2,3101 or VM2,3104 or VM2,3106 or VM2,3118 or VM2,3120 or VM2,3124 or VM2,3133 or VM2,3142 or VM2,3143 or VM2,3148 or VM2,3154 or VM2,3155 or VM2,3156 or VM2,3172 or VM2,3173 or VM2,3202 or VM2,3207 or VM2,3212 or VM2,3213 or VM2,3219 or VM2,3220 or VM2,3721 or VM2,3722 or VM2,3723 or VM2,3724 or VM2,3726 or VM2,3727 or VM2,3728 or VM2,3729 or VM2,3730 or VM2,3731 or VM2,3732 or VM2,3733 or VM2,3734 or VM2,3735 or VM2,3737 or VM2,3738 or VM2,3739 or VM2,3740 or VM2,3741 or VM2,4 or VM2,4057 or VM2,4058 or VM2,4067 or VM2,4068 or VM2,4116 or VM2,4139 or VM2,4157 or VM2,4166 or VM2,5 or VM2,5301 or VM2,53010 or VM2,5303 or VM2,5308 or VM2,5309 or VM2,5314 or VM2,5316 or VM2,5317 or VM2,5340 or VM2,5343 or VM2,5345 or VM2,5346 or VM2,5347 or VM2,5348 or VM2,5356 or VM2,5359 or VM2,5360 or VM2,5361 or VM2,5384 or VM2,5385 or VM2,5391 or VM2,5392 or VM2,5393 or VM2,5398 or VM2,5400 or VM2,5401 or VM2,5402 or VM2,5404 or VM2,5405 or VM2,5406 or VM2,5407 or VM2,5408 or VM2,5409 or VM2,5410 or VM2,5412 or VM2,5413 or VM2,5414 or VM2,5416 or VM2,5422 or VM2,5423 or VM2,5424 or VM2,5429 or VM2,5431 or VM2,5439 or VM2,5440 or VM2,5442 or VM2,5444 or VM2,5445 or VM2,5446 or VM2,5450 or VM2,5451 or VM2,5452 or VM2,5454 or VM2,5455 or VM2,5458 or VM2,5459 or VM2,5462 or VM2,5463 or VM2,5464 or VM2,5465 or VM2,5466 or VM2,5467 or VM2,5468 or VM2,5469 or VM2,5470 or VM2,5471 or VM2,5472 or VM2,5475 or VM2,5482 or VM2,5483 or VM2,5484 or VM2,5487 or VM2,5499 or VM2,5501 or VM2,5509 or VM2,5510 or VM2,5512 or VM2,5513 or VM2,5515 or VM2,5519 or VM2,5520 or VM2,5524 or VM2,5528 or VM2,5529 or VM2,5531 or VM2,5535 or VM2,5536 or VM2,5537 or VM2,5538 or VM2,5540 or VM2,5541 or VM2,5544 or VM2,5545 or VM2,5547 or VM2,5548 or VM2,5549 or VM2,5552 or VM2,5553 or VM2,5554 or VM2,5555 or VM2,5556 or VM2,5557 or VM2,5558 or VM2,5559 or VM2,5560 or VM2,5561 or VM2,5562 or VM2,5563 or VM2,5565 or VM2,5566 or VM2,5567 or VM2,5568 or VM2,5569 or VM2,5570 or VM2,6 or VM2,6030 or VM2,6031 or VM2,6032 or VM2,6033 or VM2,6034 or VM2,6035 or VM2,6036 or VM2,6037 or VM2,6038 or VM2,6039 or VM2,6227 or VM2,6228 or VM2,6232 or VM2,6233 or VM2,6237 or VM2,6238 or VM2,6239 or VM2,6240 or VM2,6242 or VM2,6245 or VM2,6246 or VM2,6251 or VM2,6257 or VM2,6259 or VM2,6260 or VM2,6261 or VM2,6263 or VM2,6264 or VM2,6265 or VM2,6267 or VM2,6270 or VM2,6289 or VM2,6573 or VM2,6597 or VM2,6599 or VM2,6612 or VM2,6625 or VM2,6640 or VM2,6643 or VM2,7 or VM2,70000 or VM2,7218 or VM2,7331 or VM2,7332 or VM2,7333 or VM2,7334 or VM2,7340 or VM2,7341 or VM2,7353 or VM2,7354 or VM2,7355 or VM2,7356 or VM2,7357 or VM2,7359 or VM2,7360 or VM2,7361 or VM2,7362 or VM2,7363 or VM2,7364 or VM2,7365 or VM2,7366 or VM2,7367 or VM2,7368 or VM2,7780 or VM2,7790 or VM2,7791 or VM2,7794 or VM2,7795 or VM2,7797 or VM2,7816 or VM2,7817 or VM2,7818 or VM2,7819 or VM2,7820 or VM2,7821 or VM2,7824 or VM2,7836 or VM2,7847 or VM2,7850 or VM2,7853 or VM2,7855 or VM2,7856 or VM2,7861 or VM2,7865 or VM2,7867 or VM2,7869 or VM2,7870 or VM2,7871 or VM2,7872 or VM2,7873 or VM2,7874 or VM2,7875 or VM2,7876 or VM2,7877 or VM2,7916 or VM2,7917 or VM2,7922 or VM2,7938 or VM2,7979 or VM2,8 or VM2,8423 or VM2,8424 or VM2,8433 or VM2,9 or VM2,9889
        product:VM2,231 or VM2,232 or VM2,233 or VM2,279 or VM2,240 or VM2,241 or VM2,242 or VM2,288 or VM2,250 or VM2,346 or VM2,298 or VM2,227 or VM2,229 or VM2,230 or VM2,275 or VM2,251 or VM2,252 or VM2,253 or VM2,343 or VM2,246 or VM2,257 or VM2,305 or VM2,294 or VM2,243 or VM2,291 or VM2,249 or VM2,297 or VM2,327 or VM2,329 or VM2,328 or VM2,330' \
        http://arkioss.metarpa:8090

**Comment by edigiacomo** [comment]
Questa issue è stata chiusa per inattività. Nel caso in cui sia un argomento ancora rilevante, si prega di riaprirla con una motivazione che tenga conto delle modifiche applicate nel corso degli anni al progetto.
