### ISSUE TITLE
arki-scan --dispatch --files can't read the list of files properly

### ISSUE THREAD

**Issue by brancomat** [ARPA-SIMC/arkimet#19]
(riportato da @eminguzzi al momento privo di account github)

Il comando:
`    arki-scan --dispatch=config --dump --status --summary --files=import.lst`
invece di importare i dati contenuti in anai_CHI_20160206.grb, svuota il file import.lst e da' l'errore "import.lst: cannot read"

Il comando:
`   arki-scan --dispatch=config --dump --status --summary grib:anai_CHI_20160206.grb`

funziona regolarmente. 

[import_lst.zip](https://github.com/ARPA-SIMC/arkimet/files/124700/import_lst.zip)

**Comment by spanezz** [comment]
Done in c4c87915
