### ISSUE TITLE
Python BUFR scanner cannot update product metadata

### ISSUE THREAD

**Issue by edigiacomo** [ARPA-SIMC/arkimet#190]
In the scanner for the bufr "generic" I have to update the `t` key in the product metadata.

In Lua, it was:

```
local report = msg:find("rep_memo")
if report then md:set(md.product:addValues{t=report:enqc()}) end
```

In Python, `md["product"]` is passed as a string, then I can't update it `t` key. Moreover, I think that I can't create a new product metadata because the bulletin attributes `data_category,data_subcategory,data_subcategory_local` are unreachable from a `dballe.Message`.

**Comment by edigiacomo** [comment]
Note: I added the "devel blocking" label because without this scanner I can't test the `issue177` branch.

**Comment by spanezz** [comment]
you can use md.to_python("product") and you get a dict, which you can then assign to md["product"], which takes either a string or a dict

**Comment by edigiacomo** [comment]
Thank you, it works like a charm :)
