### ISSUE TITLE
Specifications for the timerange in BUFR generic

### ISSUE THREAD

**Issue by edigiacomo** [ARPA-SIMC/arkimet#191]
Questa issue era stata corretta in passatto (#125 e #130) ma sto riscrivendo lo scanner per BUFR generici in Python (#177) e ho trovato uno strano comportamento dell'attuale scanner scritto in Lua, di cui incollo qui la gestione del timerange nel caso di BUFR generici:

```
function bufr_scan_forecast(msg)
    local forecast = nil
    msg:foreach(function(v)
        if v.pind == 254 then
            -- Verify that all p1 are the same: if they differ, error()
            local p1 = v.p1
            if forecast ~= nil and forecast ~= p1 then
                error("BUFR message has contradictory forecasts"..tostring(forecast).." and "..tostring(p1))
            end
            forecast = p1
        end
    end)
    if forecast == nil then forecast = 0 end

    if forecast == 0 then
        return arki_timerange.timedef(0)
    elseif math.floor(forecast / 3600) * 3600 == forecast then
        -- If it is a multiple of one hour, represent it in hours
        return arki_timerange.timedef(forecast / 3600, "h")
    elseif math.floor(forecast / 60) * 60 == forecast then
        -- If it is a multiple of one minute, represent it in minutes
        return arki_timerange.timedef(forecast / 60, "m")
    else
        return arki_timerange.timedef(forecast, "s")
    end
end
```

In pratica, prende in considerazione solo i `p1` dei dati istantanei (`pind=254`) e in quel caso controlla che siano uguali tra loro. Se non lo sono, dà giustamente un errore, in quanto non saprebbe quale `p1` usare.

Poi, imposta il timerange usando il `p1` trovato.

Tuttavia, quello che non capisco è: **per quale motivo controlla solo i dati istantanei e ignora tutti gli altri? È corretto e c'è un motivo che mi sfugge oppure è un bug?**

Ad esempio, con una temperatura istantanea prevista +1h, tutto ok:
```
$ dbamsg dump --interpreted fc.bufr 
#0[0] generic message, 44.48714,11.36473, dt: 2019-09-19T01:00:00, 2 contexts:
Level -,-,-,-, tr -,-,-,
001194 Report mnemonic(CCITTIA5): generic
004001 YEAR(YEAR): 2019
004002 MONTH(MONTH): 9
004003 DAY(DAY): 19
004004 HOUR(HOUR): 1
004005 MINUTE(MINUTE): 0
004006 SECOND(SECOND): 0
005001 LATITUDE (HIGH ACCURACY)(DEGREE): 44.48714
006001 LONGITUDE (HIGH ACCURACY)(DEGREE): 11.36473
Level 103,2000,-,-, tr 254,3600,0
012101 TEMPERATURE/DRY-BULB TEMPERATURE(K): 292.09
[edigiacomo@trenta ~]$ arki-scan --dump fc.bufr 
Source: BLOB(bufr,/autofs/nfshomes/edigiacomo/fc.bufr:0+120)
Origin: BUFR(200, 000)
Product: BUFR(255, 255, 000, t=generic)
Timerange: Timedef(1h)
Reftime: 2019-09-19T00:00:00Z
Area: GRIB(lat=4448714, lon=1136473)
```

Il timerange è giustamente `Timedef(1h)` e il reftime è corretto all'istante di emissione (come dev'essere, si vedano gli esempi in https://github.com/ARPA-SIMC/arkimet/issues/125#issue-301403034).

Tuttavia, con una precipitazione +17h (quindi un dato non istantaneo):

```
$ dbamsg dump --interpreted tp.bufr 
#0[0] generic message, 44.48714,11.36473, dt: 2019-09-19T17:00:00, 2 contexts:
Level -,-,-,-, tr -,-,-,
001194 Report mnemonic(CCITTIA5): generic
004001 YEAR(YEAR): 2019
004002 MONTH(MONTH): 9
004003 DAY(DAY): 19
004004 HOUR(HOUR): 17
004005 MINUTE(MINUTE): 0
004006 SECOND(SECOND): 0
005001 LATITUDE (HIGH ACCURACY)(DEGREE): 44.48714
006001 LONGITUDE (HIGH ACCURACY)(DEGREE): 11.36473
Level 1,-,-,-, tr 1,61200,61200
013011 TOTAL PRECIPITATION / TOTAL WATER EQUIVALENT(KG/M**2): 3.7

$ arki-scan --dump tp.bufr 
Source: BLOB(bufr,/autofs/nfshomes/edigiacomo/tp.bufr:0+114)
Origin: BUFR(200, 000)
Product: BUFR(255, 255, 000, t=generic)
Timerange: Timedef(0s)
Reftime: 2019-09-19T17:00:00Z
Area: GRIB(lat=4448714, lon=1136473)
```

Come potete notare il timerange dice `Timedef(0s)` (osservato) perché il timerange viene ignorato (non essendo `pind=254`) e quindi di default gli associa 0 e non aggiusta l'orario, mentre dovrebbe (credo) essere `timerange: Timedef(17h); reftime:= 2019-09-09T00:00:00Z`.

**Comment by edigiacomo** [comment]
Aggiungo la label "devel blocking" perché questa issue è fondamentale per poter testare la futura versione di Arkimet basata su Python (#177).

**Comment by pat1** [comment]
credo semplicemente non sia stato molto testato con bufr di forecast con timedef diversi da 254

**Comment by edigiacomo** [comment]
Quindi lascio il comportamento attuale oppure considero tutti i p1, senza discriminare per pindicator?

**Comment by edigiacomo** [comment]
> Quindi lascio il comportamento attuale oppure considero tutti i p1, senza discriminare per pindicator?

Parlando con Davide, è venuto fuori che la risposta è "considerali tutti".

**Comment by edigiacomo** [comment]
Ho implementato lo scanner per generic in Python con tanto di gestione del timerange.

Una nota: i dati del dataset `lami_ope_temp` sono generic ma viene lanciato lo scanner relativo ai `temp` (perché `rep_memo=temp`). Se lo scanner si accorge che è un generico che pretende di essere un temp, allora aggiunge anche il timerange.

In questo modo, i "veri" temp non hanno il timerange (come succede nel dataset `gts_temp`).

In definitiva: il comportamento rimane invariato rispetto all'attuale installazione delle varie versioni di arkimet sui vari server che ospitano i dataset `lami_ope_temp` e `gts_synop`.

**Comment by edigiacomo** [comment]
@spanezz non potendo indicare il tipo di processamento statistico ma solo lo step, ho esplicitato anche gli `stat_*`

```
    return {
        "style": "Timedef",
        "step_len": p1,
        "step_unit": unit,
        "stat_type": 255,
        "stat_len": 0,
        "stat_unit": 255,
    }
```

Però mi sono accorto che, con l'opzione `--annotate`, l'effetto è il medesimo di non indicare le chiavi `stat_*`, cioé i missing (255) non sono salvati (poi l'annotate ha un KeyError perché non li trova, am questa è un'altra issue).

**Comment by edigiacomo** [comment]
This issue should be fixed in `arkimet-v1.17-1`, please review it.

**Comment by dcesari** [comment]
Sto facendo delle prove che potrebbero essere viste come la review richiesta e mai fatta (detto anche alpinismo su superfici vetrose retroargentate).

Prendo il seguente json (`esempio.json`):
```
{"network": "temp", "lon": 842300, "date": "2020-03-13T00:00:00Z", "lat": 4597600, "data": [{ "vars": {"B01019": {"v": "CANDOGLIA TOCE Q.A."},"B07030": {"v": "201"}}},{"timerange": [254,21600,0],"vars": {"B12101": {"v": "28005"},"B13003":{"v":"50"}},"level": [105,2000,null,null]}]}
```
e faccio
```
dbamsg convert -t json -d bufr esempio.json |arki-scan --yaml --stdin=bufr
```
ottengo
```
Source: INLINE(bufr,162)
Origin: BUFR(200, 000)
Product: BUFR(255, 255, 000, t=temp)
Timerange: Timedef(6h)
Reftime: 2020-03-12T18:00:00Z
Area: GRIB(lat=4597600, lon=842300)
```
quindi Timedef è presente e reftime va giustamente indietro di 6 ore. Però lo stesso ottengo se cambio network in qualsiasi altra cosa. Non che sia un problema, anzi, forse è meglio così, però allora non mi è chiaro quale sia lo scopo di `Scanner.register("temp", scan_temp, priority=1)` in `/etc/arkimet/scan/bufr_generic.py`.

Lo scopo nascosto della prova è che in Mistral dovremmo creare un ds con i bufr generici previsti di Arpa Piemonte multimodel e questi dovrebbero essere trattati come i profili verticali (cioè estraibili per reftime/timedef come i grib forecast), ma, ragionevolmente, avranno un network che non è temp. Quindi: dobbiamo fare un plugin ad hoc per questi o no? Parrebbe di no.

**Comment by edigiacomo** [comment]
Risposta breve: il timerange viene gestito per i BUFR generici che non hanno il nome della rete che va in conflitto con un tipo di BUFR (e.g. "synop", "ship", etc)  per i BUFR generici con nome rete "temp".

Per la risposta lunga, parto da una premessa: lo scan dei BUFR prevede l'impostazione di alcuni metadati da C++ (vedi https://github.com/ARPA-SIMC/arkimet/blob/master/arki/scan/bufr.cc) e il resto viene fatto da Python (i file `bufr_*.py` in https://github.com/ARPA-SIMC/arkimet/tree/master/conf/scan) e infine, il reftime viene modificato nel C++ se il timerange è stato impostato (https://github.com/ARPA-SIMC/arkimet/blob/master/arki/scan/bufr.cc#L251-L254).. Evidenzio che tra i medatadati "hardcoded" in C++ c'è il `t` del Product, che viene impostato al tipo del messaggio https://github.com/ARPA-SIMC/arkimet/blob/master/arki/scan/bufr.cc#L197, i.e. "temp", "synop", "generic".

Nel caso dei generic, viene usato lo scanner https://github.com/ARPA-SIMC/arkimet/blob/master/conf/scan/bufr_generic.py#L40, il quale prevede anche l'impostazione del timerange, oltre che la modifica del `t` del Product da "generic" al nome della rete. Questo succede per qualsiasi BUFR generico che non abbia nome della rete che va in conflitto con un tipo di BUFR ("synop", "ship", etc) Nel caso dei "temp" generici, vengono invocati gli scanner associati ai temp, in ordine descrescente di priorità: prima https://github.com/ARPA-SIMC/arkimet/blob/master/conf/scan/bufr_generic.py#L60, che imposta solo il timerange (e solo se il BUFR è davvero generico), e poi https://github.com/ARPA-SIMC/arkimet/blob/master/conf/scan/bufr_fixed.py#L4, che imposta il resto dei metadati.
