### ISSUE TITLE
Limiti delle API HTTP rispetto a arki-query

### ISSUE THREAD

**Issue by edigiacomo** [ARPA-SIMC/arkimet#192]
Quali sono i limiti delle API HTTP rispetto ad una arki-query?

Ci potrebbero essere casi in cui non è possibile installare arkimet sul client e sarebbe interessante sapere in quali limiti si incorre nell'utilizzare direttamente le API HTTP.

**Comment by spanezz** [comment]
I limiti delle API http possono essere ben pochi rispetto ad arki-query, e quei pochi possono essere risolti migliorando l'interfaccia HTTP.

L'unico limite sostanziale che mi viene in mente è fare merge di dataset su piú server, cosa che arki-query fa in locale, e un arki-server può fare solo se i dataset remoti coinvolti fanno già parte della sua configurazione, e forse è giusto cosí: non mi piace che una persona si colleghi a un arki-server e si metta a fargli fare query a host remoti a caso.

A parte le query remote a dataset arbitrari, per me non è un problema, se serve, aggiungere all'interfaccia web tutte le funzionalità di arki-query

**Comment by edigiacomo** [comment]
La limitazione del merge remoto è legittima: nel caso di client HTTP, è accettabile limitarlo ad un singolo arki-server.

Bella l'idea di aggiungere all'interfaccia web le funzionalità di arki-query! Però come priorità avremmo quella di formalizzare le API e documentarle. 

Apro una nuova issue.
