### ISSUE TITLE
Remove embedded sqlite

### ISSUE THREAD

**Issue by spanezz** [ARPA-SIMC/arkimet#194]
The fallback embedded sqlite version is 3.22, and the minimum required version is 3.14.

If/when all supported architectures contain at least sqlite >= 3.14, we can get rid of the version of sqlite embedded in the code

**Comment by edigiacomo** [comment]
Cento7 ships with sqlite 3.7, [see you in 2024](https://wiki.centos.org/About/Product) :)

**Comment by spanezz** [comment]
Thanks for checkint!

I kind of hope that Centos7 will not be a supported architecture for arkimet all the way until 2024, though

**Comment by spanezz** [comment]
Since now the minimal supported distribution is Centos8, I can finally remove embedded libraries! :scissors: :scissors:
