### ISSUE TITLE
Is timerange:GRIB2 ever used?

### ISSUE THREAD

**Issue by dcesari** [ARPA-SIMC/arkimet#197]
In [matcher/timerange.txt](https://github.com/ARPA-SIMC/arkimet/blob/master/doc/matcher/timerange.txt) the timerange:GRIB2 metadatum is documented, however it does not appear in lua scanning code and it is not cited in [scan/timerange.txt](https://github.com/ARPA-SIMC/arkimet/blob/master/doc/scan/timerange.txt) (for grib2 Timedef is used): is it used anywhere? can we ignore it for the moment?

**Comment by edigiacomo** [comment]
That was my conjecture too, but I need some help from @brancomat to check the offline datasets.

I checked `arkimet{4,5,6}` servers and it seems that GRIB2 datasets use the Timedef metadatum only:

```
$ arki-query --summary --dump --summary-restrict=timerange 'product:GRIB2' $(grep -l -i grib2 /arkivio/arkimet/dataset/*/config | xargs -n1 dirname) | grep "Timerange: Timedef" | grep -v Timerange | wc -c
0
```

**Comment by brancomat** [comment]
> I need some help from @brancomat to check the offline datasets

offline GRIB2 datasets are basically old data of currently online dataset, it's safe to assume they uses Timedef only too

> can we ignore it for the moment?

I'd say yes

**Comment by dcesari** [comment]
Good, I would thus suggest NOT to use timerange:GRIB2 in the future and keep on using Timedef for the new cases.
