### ISSUE TITLE
fallimento arki-check su dataset in fase di interrogazione

### ISSUE THREAD

**Issue by brancomat** [ARPA-SIMC/arkimet#2]
su un dataset quando ci sono interrogazioni in contemporanea all'arki-check abbiamo un:

```
database is locked. Context:     executing query PRAGMA journal_mode = TRUNCATE
```

alcuni dataset stanno diventando impossibile da mantenere senza metterli offline (che è poco accettabile): è possibile gestire la concorrenza tra scrittura (arki-check) e lettura (arki-query) concorrenti?

**Comment by spanezz** [comment]
Finora ho dato per scontato che le letture non avvengono assieme alle scritture, in un modello in cui il processing parte alla ricezione di un qualche segnale dopo l'import. In questo modello, non mi sono mai preoccupato di gestire il caso di letture e scritture concorrenti.

sqlite permette ora di leggere mentre si scrive (rimane il vincolo di avere un solo processo che scrive alla volta), con alcuni requisiti: https://www.sqlite.org/wal.html in particolare, quello che il processo che legge deve poter scrivere almeno su un file specifico di fianco all'indice, e che non funziona su file system di rete.

Se questi vincoli sono accettabili, posso procedere ad aggiungere unit testing per accessi concorrenti, dire a sqlite di usare la modalità WAL e vedere cosa rimane da fare a quel punto.

**Comment by brancomat** [comment]
I vincoli sono accettabili, nel senso che al momento gestiamo e arki-checkiamo solo su filesystem locale, in futuro potrà essere interessante rendere disponibile qualche sezione offline via nfs ma in ogni caso terremo sempre l'index.sqlite su fs locale scrivibile dall'arkiutente

**Comment by spanezz** [comment]
Di quali operazioni di arki-check stiamo parlando? Un controllo di integrità è molto piú facile da gestire (non modifica i file di dati) rispetto a un repack che modifica i file di dati.

**Comment by edigiacomo** [comment]
Il problema mi pare presentarsi sia con un `arki-check -f` che con un `arki-check -f -r`.

Il repack è più lungo e quindi è statisticamente più facile che si presenti il problema. Nel caso di solo `-f`, mi pare di capire che l'uso del WAL risolverebbe la cosa, mentre nel caso di `-r` si dovrebbe bloccare la lettura.

Mi piaceva l'idea dello "sharding" dell'indice per anno/mese di cui parlavi qualche giorno fa, in modo da limitare o evitare l'attesa di una query (che tra l'altro, permetterebbe di mantenere in linea molti più dati).

**Comment by spanezz** [comment]
Pensandoci meglio, WAL risolverebbe poco nel caso di un repack in parallelo a una lettura, perché il file di dati potrebbe cambiare radicalmente da quando si sono generati i metadati da estrarre a quando vengono effettivamente letti i dati.
Qualunque caso che non sia il repack dei segmenti invece è parallelizzabile decentemente, perché l'unico tipo di modifica dei segmenti che non sia il repack è l'append, che mantiene inalterati i dati esistenti.
Quindi, il repack di un segmento ne deve per forza bloccare la lettura, e qualunuque altra operazione no. Premesso questo, si può rilassare almeno il locking nel caso di un solo check, e nel caso di importazione in parallelo alla lettura.

**Comment by spanezz** [comment]
In f03d1b6865c24629fa9ef5fc88f9067b93f44cc3 ho implementato lo sharding.

Nella configurazione di un dataset, se si mette `shard=yearly`, `shard=monthly`, o `shard=weekly`, in fase di importazione vengono creati i subdataset dove effettivamente poi salvare i dati.

Non esiste al momento una procedura di conversione da dataset sharded a non sharded; se serve ci possiamo organizzare per conversioni manuali.

**Comment by brancomat** [comment]
Chiudo questa che s'interseca in parte con la #23, perché con il nuovo layout operativo il problema dovrebbe mitigarsi/sparire. In sostanza

- sul server arkimet dei dati osservati (vm2) usiamo lo sharding
- sul server arkimet dei dati previsti (grib, odim) in d.r. ci sarà un set ridotto di dati quindi una query talmente lunga da inchiodare il repack non dovrebbe presentarsi
- sul serverone arkimet storico dei dati previsti avverrà di fatto un rsync nelle dir .archive e uno stallo dell'arki-check per qualche giorno dovuto a query monumentali è un danno collaterale che s'è ritenuto accettabile

( @edigiacomo : se vedi errori o omissioni riapri il bug)
