### ISSUE TITLE
conflicting output on `arki-mergeconf` with multiple server with duplicate dataset names

### ISSUE THREAD

**Issue by brancomat** [ARPA-SIMC/arkimet#200]
Given four arki-server with duplicate datasets name, this command
```
arki-mergeconf --ignore-system-datasets $A $B $C $D $E > config
```
should produce a conf ignoring duplicates and in the order indicated (that is: first all datasets of `$A`, then only non duplicates datasets of `$B`, etc)

with arkimet 1.17, while the output seems correct:
```
WARNING ignoring dataset XXXX in <$E>, which has the same name as the dataset in <$A>
```
the resulting config is the opposite, having `$E` url in the dataset path.

this can be tested internally with:
```
arki-mergeconf --ignore-system-datasets http://arkiope.metarpa:8090/ http://arkirad.metarpa:8090 http://arkimet6.metarpa:8090 http://arkiold.metarpa:8090 http://arkimet.metarpa:8090 > config
```

**Comment by spanezz** [comment]
Merged in issue177, waiting for it to be merged into master.
