### ISSUE TITLE
Doc rebuild

### ISSUE THREAD

**Issue by brancomat** [ARPA-SIMC/arkimet#203]
arkimet is missing the fancy script to rebuild documentation (as seen on dballe: https://github.com/ARPA-SIMC/dballe/blob/master/rebuild-gh-pages)

**Comment by edigiacomo** [comment]
Unfortunately I'm not so sure about where the source files of the current documentation are (https://arpa-simc.github.io/arkimet), maybe in the `sphinx` branch (where I found a version of `rebuild-gh-pages`). I've tried to merge it into the master but there are too many conflicts and I'm not very confident about how to resolve some of them.

**Comment by spanezz** [comment]
I've regenerated the sphinx branch rebased on current master. Please delete the local `sphinx` branch, if you have one, before checking it out. Now it should be easily mergeable. Shall we merge it and continue from there?
