### ISSUE TITLE
arki-web-proxy

### ISSUE THREAD

**Issue by brancomat** [ARPA-SIMC/arkimet#205]
As discussed in #114, @spanezz provided a script to create a static dir layout from a config file to be served via http and act as a proxy.

It's now in the master branch as `src/arki-web-proxy`, these are further enhancements for it:

- [x] the input should be either one or more config file or one or more arkiservers (the script should treat those fields like `arki-mergeconf`)

- [x] the script could serve itself the produced output (since Werkzeug is already in arkimet dependencies)

**Comment by edigiacomo** [comment]
Il branch `issue205` contiene una versione che dovrebbe essere stabile.
