### ISSUE TITLE
expa queries don't work when the target arki-server is a web server

### ISSUE THREAD

**Issue by edigiacomo** [ARPA-SIMC/arkimet#206]
We have deployed a centralized http server (as suggested in https://github.com/ARPA-SIMC/arkimet/issues/114#issuecomment-542660963) to redirect the arkimet clients to the proper arkimet server.

Everything works fine except when querying the http server (in our case, arkimet.metarpa) with expa qmacro.

```
$ arki-query --data --qmacro="expa 2019-12-23" --file test.expa http://arkimet.metarpa:8090 > /tmp/out.grib
Traceback (most recent call last):
  File "/usr/bin/arki-query", line 11, in <module>
    main()
  File "/usr/bin/arki-query", line 7, in main
    sys.exit(Query.main())
  File "/usr/lib/python3.6/site-packages/arkimet/cmdline/base.py", line 74, in main
    cmd.run()
  File "/usr/lib/python3.6/site-packages/arkimet/cmdline/query.py", line 138, in run
    arki_query.query_qmacro(self.args.qmacro, qmacro_query)
  File "/etc/arkimet/qmacro/expa.py", line 69, in __init__
    product=self._to_matcher(mo.group("v"))
RuntimeError: cannot parse Timerange style 'f003': only GRIB1, GRIB2, Timedef and BUFR are supported (parsing Timerange style)
```

The same query works with the real arki-server http://arkimet4.metarpa:8090.

You can replicate the issue with [test.expa.gz](https://github.com/ARPA-SIMC/arkimet/files/3994303/test.expa.gz).

**Comment by spanezz** [comment]
It now seems to be `arkiold.metarpa` instead of `arkimet4.metarpa`

**Comment by spanezz** [comment]
Investigating, in the first (failing) case, the expa query is run client-side, and the alias database is empty. In the second (working) case, the expa query is run server-side, where the alias database is present.

I now need to investigate if I'm able to, and how to, populate the local alias database when running an expa query which involves remote datasets

**Comment by spanezz** [comment]
The reason the expa query is run client-side, is because not all known datasets are on the same server, and since we can't know in advance which datasets the expa query is going to use, we can't pick one of the servers to run it there, since it might not have all the datasets the expa query needs.

#153 could be an elegant long-term solution for this.

A short term option is to download alias information from all the datasets, and merge it checking that it doesn't conflict.
