### ISSUE TITLE
arki-query seems to ignore SIGINT

### ISSUE THREAD

**Issue by edigiacomo** [ARPA-SIMC/arkimet#210]
Arkimet v1.19-1.

```
$ cat test.sh 
#!/bin/bash
set -x
arki-query --data 'reftime:=today 00:00' http://arkimet.metarpa:8090/dataset/cosmo_5M_ita > /dev/null &
pid=$!
sleep 1
kill -s INT $pid
wait $pid
```

```
$ timeout -v 3m ./test.sh
+ pid=10454
+ sleep 3
+ arki-query --data 'reftime:=today 00:00' http://arkimet.metarpa:8090/dataset/cosmo_5M_ita
+ kill -s INT 10454
+ wait 10454
timeout: sending signal TERM to command ‘./test.sh’
```

**Comment by spanezz** [comment]
Uhm, arkimet isn't blocking SIGINT, but python is normally catching it to throw the KeyboardInterrupt exception. Only, arki-query uses python to set up the query, and then hands over producing the data to a (possibly long lived) C++ call, which does all the job.

Indeed, when arki-query finishes producing data, one sees the KeyboardInterrupt being raised.

I'll now try to find out how to deal with SIGINT in longrunning C code called from python…

**Comment by spanezz** [comment]
https://stackoverflow.com/questions/14707049/allowing-ctrl-c-to-interrupt-a-python-c-extension

**Comment by spanezz** [comment]
As things stand now, we don't have any obvious points where to hook a call to [PyErr_CheckSignals](https://docs.python.org/3/c-api/exceptions.html#c.PyErr_CheckSignals) every once in a while.

It could be the right prompt for adding some kind of progress reporting callback to arki-query...
