### ISSUE TITLE
nosetests hangs in CentOS7 builds

### ISSUE THREAD

**Issue by brancomat** [ARPA-SIMC/arkimet#217]
Since 42cd682, running nosetests hangs for more thant 10 minutes on [CentOS7 travis builds](https://travis-ci.org/ARPA-SIMC/arkimet/builds)

**Comment by spanezz** [comment]
I tried on the `sette` test build server, and all tests pass successfully. I currently am not able to reproduce this issue on a manchine where I can debug it :/

**Comment by edigiacomo** [comment]
The test is skipped when building on Travis (5ad6add), I don't know if it's better to leave this issue open as a reminder.

**Comment by brancomat** [comment]
It's a little more than a reminder, the problem is now moved on copr builds (https://copr.fedorainfracloud.org/coprs/simc/stable/build/1285327/):
```
Running nosetests-3.6 -s /builddir/build/BUILD/arkimet-1.23-1/python 
...............SS............SS.........S.........S.......................................................................S.SSSSSS................... !! Copr timeout => sending INT
```

Long story short: we don't have updated arkimet rpms for CentOS7.

Worst case scenario, we could skip the test altogether on CentOS7 manually forcing it on `sette` on new releases (also known as Discontinuous Integration) but it's far from ideal.

**Comment by edigiacomo** [comment]
The test is now skipped in the spec file, so that the CentOS 7 build should work both in Travis and Copr (d2a914b).
