### ISSUE TITLE
[arki-query] `--output` option is now positional. Is this ok?

### ISSUE THREAD

**Issue by brancomat** [ARPA-SIMC/arkimet#222]
I'm unsure if this might be considered a bug, since formally the `arki-query` manpage states an order for options.

Until at least arkimet 1.16, this worked:
```
arki-query  --data "reftime:= 2020-03-16 09; product: mslp or u or v; level: GRIB1,102 or g10" --output=/tmp/buttami.grib http://arkiope.metarpa:8090/dataset/cosmo_2I_ruc
```

In arkimet 1.23 this generate an error:
```
arki-query: error: unrecognized arguments: http://arkiope.metarpa:8090/dataset/cosmo_2I_ruc
```

Moving the `--output` parameter elsewhere fixes the problem. These are fine:
```
arki-query  --output=/tmp/buttami.grib --data "reftime:= 2020-03-16 09; product: mslp or u or v; level: GRIB1,102 or g10"  http://arkiope.metarpa:8090/dataset/cosmo_2I_ruc

arki-query --data "reftime:= 2020-03-16 09; product: mslp or u or v; level: GRIB1,102 or g10"  http://arkiope.metarpa:8090/dataset/cosmo_2I_ruc  --output=/tmp/buttami.grib
```

It's not a big deal, the only disorienting thing is that the "unrecognized arguments" error is related to the dataset parameter.

**Comment by edigiacomo** [comment]
From 1.16 to 1.23 the argument parser is changed - now is the Python `argparse` module, thus the different behaviour.

The problem is that the `query` argument can be specified 0 or 1 times (`nargs="?"`)  and `source` argument 0 or many times (`nargs="*"`) and it seems that, with this combination, `argparse` needs the arguments to be placed after the options.

**Comment by edigiacomo** [comment]
I have found this explanation: https://stackoverflow.com/a/51227190.

**Comment by brancomat** [comment]
Since the `arki-query` manpage is unambiguous on the matter and there haven't been other complaints, I'd say the answer to the issue titile is "yes".
