### ISSUE TITLE
Best practices on managing offline archives

### ISSUE THREAD

**Issue by brancomat** [ARPA-SIMC/arkimet#23]
Le esigenze sostanzialmente sono due:
- creazione di sezioni d'archivio partendo da dati mai archiviati senza interferire con l'arki-server di produzione
- gestione e spostamento delle sezioni di archivio (cosa portarsi dietro e necessaire pur rimetterle online)

In particolare, rispetto ai commenti di #17:  opportunità di sottodirectory .archive/ al di fuori di .archive/last (mentre il commento sul MANIFEST non l'ho capito, dovrebbe essere ricreato dinamicamente dall'arki-check)

Provo ad elencare task:
- [x] breve incontro sul tema preferibilmente di persona per verificare ns. attuale sistema vs. situazione ideale
- [x] documentazione best practices almeno sull'[arkiguide](https://github.com/ARPA-SIMC/arkimet/blob/master/doc/arkiguide.it.txt) 
- [ ] valutare integrazione/estensione di tool ad hoc (tipo [arkimet-tools](https://github.com/edigiacomo/arkimet-tools) by @edigiacomo) (opzionale)

**Comment by brancomat** [comment]
A seguito dell'incontro di ieri (prima checkbox andata) potremmo modificarlo in "implementare dataset sharded"?
E a questo punto la doc sull'arkiguide verrebbe dopo

**Comment by spanezz** [comment]
I dataset sharded sono implementati, il passo successivo è una funzione che sposti i segmenti da .archive/last al dataset online

**Comment by spanezz** [comment]
`arki-check --unarchive=segment` è implementato in b5cc5af520559d3adcd9a43a080b02a129587886.

Per i passi successivi, come procediamo?

**Comment by brancomat** [comment]
Ottimo, direi che la palla passa a noi, vediamo di ripacchettizzare l'ultimo arkimet, fare un par di test, installarlo sui server operativi, completare la doc e testare lo striplamento arkimet operativo / arkimet archivione online / arkimet archivione offline ~~facendo a gara di chiusura lavori con quelli del ponte sullo stretto~~.
Ci autoassegno il bug poi completiamo man mano andiamo avanti coi vari step.

**Comment by brancomat** [comment]
La situazione si è un pelo evoluta rispetto all'apertura di questa issue, che chiuderei riassumendo:
- la gestione degli archivi è ora sufficentemente sviscerata in ds-archive.md, in particolare la creazione di sottodirectory di `.archive` è esplicitamente menzionata nell'arkiguide
- difficile parlare di best practices da qui in poi, internamente probabilmente opteremo per un `rsync --remove-source-files` di `.archive` dall'arki-server operativo su un arki-server di archivio più pasciuto che vada in locking con le operazioni di importazione e repack per evitare che le cose avvengano contemporaneamente. Ma più che best practice sono scelte per una situazione particolare che ha poco senso integrare nella doc.
