### ISSUE TITLE
Non 0 exit code for arki scan

### ISSUE THREAD

**Issue by bchiavarini** [ARPA-SIMC/arkimet#231]
Hi,
We are using the arki-scan command in a script to move data from dballe to arkimet and it's been a couple of days since the arki-scan command has started to have a non 0 exit code.
We call the command in this way:
``` python
subprocess.call(
            ("arki-scan", "--dispatch=" + opts.arkiconf, "bufr:" + tmpdatafile, "--summary", "--dump", "--status"),
            stderr=stderr, stdout=stdout)
```
and we are getting a `65` as exit code.
Launching an `arki-check` on the datasets, we have noticed that the data have been imported but they raise these warnings:

```
spdsra:2020/07-14.bufr: item at offset 2589184 begins past the end of the previous item (offset 0)
spdsra:2020/07-14.bufr: should be packed
spdsra:2020/07-15.bufr: item at offset 5113464 begins past the end of the previous item (offset 0)
```
We are using Arkimet 1.28

What can be the problem risen during the data import? how can we fix it?
Thanks for your help!

**Comment by spanezz** [comment]
`arki-check` is only reporting that the dataset can be optimized, but it shouldn't be a reason to have trouble dispatching.

`arki-scan` should say something in its stderr about what went wrong in the dispatch. Could you send what arki-scan is saying in stderr?

**Comment by brancomat** [comment]
Closing issue since it seems stale.
@bchiavarini feel free to reopen it with additional info if needed
