### ISSUE TITLE
Implementare `eatmydata: yes` nella configurazione dei dataset

### ISSUE THREAD

**Issue by spanezz** [ARPA-SIMC/arkimet#233]
In arkimaps c'è l'esigenza di creare velocemente un dataset temporaneo di appoggio per i dati da elaborare.

Farebbe comodo avere la possibilità di configurare un dataset per non fare `fsync`/`fdatasync` in scrittura, sia sui dati che su sqlite. Su sqlite si può saltare completamente il journaling su disco.

Essendo un dataset di appoggio creato comunque in una directory di lavoro temporanea, in caso di errori si cancella comunque tutto e si riparte da zero.

**Comment by spanezz** [comment]
Meglio: nella configurazione della sessione, che è quella che poi istanzia i segmenti

**Comment by spanezz** [comment]
No, meglio nella configurazione del dataset, per poter gestire sia dataset permanenti che dataset temporanei

**Comment by dcesari** [comment]
Domanda: non è che questo, incidentalmente, permetta anche di fare arki-query su filesystem da parte di un utente senza permesso di scrittura sul dataset?

**Comment by brancomat** [comment]
Riapro issue come question per la domanda di @dcesari che in effetti è interessante

**Comment by brancomat** [comment]
Aggiunta: manca la documentazione del parametro eatmydata in `doc/datasets.rst` (rif. #143)

**Comment by spanezz** [comment]
Ho pushato la documentazione. @dcesari l'opzione eatmydata disabilita i flush in scrittura ma non i locking, per cui non ti permette comunque di fare query senza permessi di scrittura

**Comment by spanezz** [comment]
Se c'è un'esigenza specifica in quel senso, puoi aprire un ticket apposta che ne parliamo?

**Comment by dcesari** [comment]
Grazie, aperta #258
