### ISSUE TITLE
arki-query RuntimeError if client and server match-alias.conf differ: is this ok?

### ISSUE THREAD

**Issue by brancomat** [ARPA-SIMC/arkimet#238]
Somewhere after arkimet v1.22 (I'd say after #153, released in v1.27) the behaviour of `arki-query` has changed giving a runtime error if the client and the server have different opinions on the meaning of an alias, even if the alias is not used, e.g.:

```
$ arki-query --data 'reftime: >= 2020-10-20 01:00 , <= 2020-10-21 00:00' http://maialinux.metarpa:8090/dataset/ADROMS2K -o in.grib
Traceback (most recent call last):
  File "/usr/bin/arki-query", line 11, in <module>
    main()
  File "/usr/bin/arki-query", line 7, in main
    sys.exit(Query.main())
  File "/usr/lib/python3.6/site-packages/arkimet/cmdline/base.py", line 75, in main
    cmd.run()
  File "/usr/lib/python3.6/site-packages/arkimet/cmdline/query.py", line 130, in run
    self.build_config()
  File "/usr/lib/python3.6/site-packages/arkimet/cmdline/query.py", line 114, in build_config
    self.add_config_section(section, name)
  File "/usr/lib/python3.6/site-packages/arkimet/cmdline/base.py", line 203, in add_config_section
    self.session.add_dataset(section)
RuntimeError: current alias "product:GRIB1,200,2,84 or GRIB1,200,200,124 or GRIB2,200,0,200,124 or GRIB1,80,2,84" conflicts with new alias "product:GRIB1,200,2,84 or GRIB1,200,200,124 or GRIB2,200,0,200,124"
```

Before reporting this as a bug: is this a bug? What's the expected behaviour?

meanwhile, @spanezz confirmed that in #153 implemented a sort of alias database merging client and server(s) aliases and checking for this kind of errors _before_ the actual query parsing.

At fist sight, I'd say the previous behaviour was ambiguous at best, so I guess it's ok. The only improvement I can see could be throwing an error only if the inconsistent alias is actually used, but I don't know the effort to implement it and the possible performance consequences.

**Comment by brancomat** [comment]
Bump for @dcesari, @edigiacomo and @pat1 opinion on the matter.

**Comment by edigiacomo** [comment]
> Before reporting this as a bug: is this a bug? What's the expected behaviour?

IIRC this was the expected behaviour.

> At fist sight, I'd say the previous behaviour was ambiguous at best, so I guess it's ok. The only improvement I can see could be throwing an error only if the inconsistent alias is actually used, but I don't know the effort to implement it and the possible performance consequences.

Maybe it's better to know as soon as possible if two match-alias files differ.
