### ISSUE TITLE
NetCDF scan: validate product metadata

### ISSUE THREAD

**Issue by spanezz** [ARPA-SIMC/arkimet#239]
This issue is related to NetCDF support (#40).

Currently, the NetCDF scanner prototype generates a 'quantity' metadata with a list of the variable names found in the NetCDF file.

I did this because the ODIMH5 quantity metadata had the right structure to represent a list of strings, and if we decide such a list of strings is what we want, I can implement it as a Product metadata

**Comment by edigiacomo** [comment]
Questa issue è stata chiusa per inattività. Nel caso in cui sia un argomento ancora rilevante, si prega di riaprirla con una motivazione che tenga conto delle modifiche applicate nel corso degli anni al progetto.
