### ISSUE TITLE
arki-query --inline

### ISSUE THREAD

**Issue by enrenr** [ARPA-SIMC/arkimet#24]
Con la versione 1.0.3, il comando:
arki-query --inline --config=lamaz.conf --file=tmp.query.1 > tmp.out
da' l'errore: "no decoder found for item type ASSIGNEDATASE"

[bug.zip](https://github.com/ARPA-SIMC/arkimet/files/167238/bug.zip)

**Comment by palberoni** [comment]
con versione 1.0  ho un problema analogo: 
arki-query --yaml 'reftime:=2016-03'  http://arkimet.metarpa:8090/dataset/odimSPC
ritorna:
cannot parse binary data: no decoder found for item type ASSIGNEDDATASET

**Comment by brancomat** [comment]
(probabilmente collegato a #10, se aiuta)

**Comment by spanezz** [comment]
Fatto in 2bb6650c061189bb78543e09e4be9c469cd8e862.

Era collegato a #10, ma in maniera davvero non ovvia.
