### ISSUE TITLE
NetCDF scan: what area to use for Adriatic sea region?

### ISSUE THREAD

**Issue by spanezz** [ARPA-SIMC/arkimet#240]
At the moment, the NetCDF scanner prototype (#40) can look for the `region` global attribute, and the idea would be, if it finds `Adriatic Sea`, it can generate an appropriate area describing the Adriatic sea. As I understand it, it can be something like a rotated rectangle.

I'd need the exact definition to use, possibly as an arkimet Area metadata. Possibly one of the rotated GRIB latlon areas? If the current way of representing Area metadata is not sufficient in Arkimet, let's talk about it and we can see about extending it.

**Comment by edigiacomo** [comment]
Questa issue è stata chiusa per inattività. Nel caso in cui sia un argomento ancora rilevante, si prega di riaprirla con una motivazione che tenga conto delle modifiche applicate nel corso degli anni al progetto.
