### ISSUE TITLE
NetCDF scan: what to use for Origin?

### ISSUE THREAD

**Issue by spanezz** [ARPA-SIMC/arkimet#241]
At the moment the prototype NetCDF scanner (#40) fills `origin` with a dummy value. We need to define what we want as origin, if anything.

**Comment by edigiacomo** [comment]
Questa issue è stata chiusa per inattività. Nel caso in cui sia un argomento ancora rilevante, si prega di riaprirla con una motivazione che tenga conto delle modifiche applicate nel corso degli anni al progetto.
