### ISSUE TITLE
Optimize reconstructing Metadata when querying dataset indices

### ISSUE THREAD

**Issue by spanezz** [ARPA-SIMC/arkimet#247]
When querying ondisk2 and iseg datasets, Metadata is reconstructed using binary pieces encoded in the database. Right now, they are assembled in a somewhat chaotic way.

After the work in #245, they could be streamlined by composing the pieces together in the right order, appending the encoded chunks in a memory buffer alongside the instantiated metadata Types in the Metadata index.

**Comment by edigiacomo** [comment]
Questa issue è stata chiusa per inattività. Nel caso in cui sia un argomento ancora rilevante, si prega di riaprirla con una motivazione che tenga conto delle modifiche applicate nel corso degli anni al progetto.
