### ISSUE TITLE
VM2 derived values in binary encoding of metadata

### ISSUE THREAD

**Issue by spanezz** [ARPA-SIMC/arkimet#249]
At the moment, binary encoding metadata includes derived values, except when written into a dataset index (#172).

The intention of this is so that when `arki-query` runs on a remote server, the server sends the derived data and the client doesn't need to have a copy of the `meteo-vm2` derived database.

This is fine and good, except that `simple` datasets and archives also write binary metadata to disk, and they use the same encoding functions that are used to write over the net. That is, they also store derived values. I would imagine that `.metadata` files in archives of VM2 data would end up being quite big.

If that is the case, I could work on not writing derived values into simple and archive dataset `.metadata` files. However, is that a good thing to do, or would you actually want to also archive derived values?

**Comment by edigiacomo** [comment]
> If that is the case, I could work on not writing derived values into simple and archive dataset `.metadata` files. However, is that a good thing to do, or would you actually want to also archive derived values?

It would be a good thing to do because old derived values should be ignored. Currently we don't archive VM2 dataset nor use `simple` dataset, so you can consider it as a low priority issue.

**Comment by spanezz** [comment]
Ok, thanks! I'm retitling the issue and turning it into an enhancement

**Comment by edigiacomo** [comment]
Questa issue è stata chiusa per inattività. Nel caso in cui sia un argomento ancora rilevante, si prega di riaprirla con una motivazione che tenga conto delle modifiche applicate nel corso degli anni al progetto.
