### ISSUE TITLE
hanging arki-server child process

### ISSUE THREAD

**Issue by edigiacomo** [ARPA-SIMC/arkimet#252]
Sometimes arki-query hangs when querying a remote arki-server. The only effective solution found so far is to kill the child process (server side arki-query).

I'm not able to reproduce the problem, but we could discuss a workaround, e.g. a client or server side timeout (or something else).

**Comment by spanezz** [comment]
Probably a way to reproduce this is to use something like `arki-query … | sleep 1h`.

I agree it makes sense to have a timeout server-side for clients that hang during read. The question is how long: if the client is streaming the data to some slow processing chain, it makes sense to support nontrivial hang times while sending.

This is incidentally why if you query a whole segment, all the segment metadata is kept in RAM: arkimet tries to pull all the data out of the index as soon as it can, so it can release the read lock on it, and then send at the client's and network's own pace: so far I try not to assume how fast the client will read.

Meanwhile I'll read up on how to implement timeouts when using things like `sendfile()`

**Comment by spanezz** [comment]
For my future reference, this post has interesting details: https://blog.cloudflare.com/the-curious-case-of-slow-downloads/

**Comment by spanezz** [comment]
The closest information I found is at https://python.readthedocs.io/fr/latest/library/socket.html#socket-timeouts

That hints that at the OS level, there is no way to set a timeout on the single `sendfile()` operation, but I can refactor data output to set the socket in non-blocking mode, and use `sendfile()` in a `select()`/`poll()` loop, which does allow a timeout.

I can implement this, while you think what could be a good value for a write timeout

**Comment by spanezz** [comment]
I pushed a branch `issue252` which has a default 60s timeout when writing output. We can use it to try things out.

Could you give it a try and see if it breaks something?

The timeout is currently hardcoded at https://github.com/ARPA-SIMC/arkimet/blob/issue252/arki/dataset.cc#L54 if you'd like to try other values.

**Comment by spanezz** [comment]
Essendo l'invio dell'output una parte abbastanza critica, sto aggiungendo molti test per varie casistiche, e sto notando che il codice non è ancora pronto per una prova seria

**Comment by spanezz** [comment]
Ora il codice dovrebbe essere pronto per una prova seria

**Comment by spanezz** [comment]
Ora ancora piú pronto, con timeout di 60 secondi in tutti i posti che sono riuscito a trovare dove scrive output di query

**Comment by spanezz** [comment]
Ora ho fatto merge in master di tutto il discorso timeout. Per default ora **non c'è timeout**.

Si può settare `ARKI_IO_TIMEOUT` a un valore in secondi (volendo decimale, che verrà poi approssimato al millisecondo) per settare un timeout.

Ho aggiunto nell'occasione anche la documentazione delle variabili di ambiente supportate da arkimet: https://github.com/ARPA-SIMC/arkimet/blob/master/doc/config.rst

Per me ci possiamo essere. Si potrebbe al limite decidere di avere un default diverso da "nessun timeout".

Lo passo per review

**Comment by edigiacomo** [comment]
Per le query che si piantano in #269 pare che `ARKI_IO_TIMEOUT` non sortisca effetto.

**Comment by spanezz** [comment]
Qui se ho capito bene il problema è che la query che si pianta viene fatta via http. `ARKI_IO_TIMEOUT` non viene passato da `arki-query` al server, ed è sempre valido il valore settato nel server.

È probabile che dopo aver implementato tutto questo, non abbiamo mai settato `ARKI_IO_TIMEOUT` nell'environment di arki-server, e che quindi abbiamo ancora arki-server che gira senza timeout.

Propongo di settare un timeout di qualche tipo in arki-server, nello specfile/script che lo lancia

**Comment by edigiacomo** [comment]
Grazie mille, in effetti non avevo considerato che la query si pianta lato server e quindi, anche se un timeout lato client avesse killato quest'ultimo, sarebbe rimasto appeso dall'altra parte. TI confermo inoltre che il timeout è non settato nel server.

> Propongo di settare un timeout di qualche tipo in arki-server, nello specfile/script che lo lancia

Sì, assolutamente, apro altra issue in merito e chiudo questa che mi pare risolta.
