### ISSUE TITLE
arki-query --data print headers at the end of the file

### ISSUE THREAD

**Issue by edigiacomo** [ARPA-SIMC/arkimet#26]
arkimet-1.0-4

The headers are printed at the end of the response with `--data` only.

```
$ arki-query --data 'reftime:>= today 00:00' http://arkioss4.metarpa:8090/dataset/agrmet | tail 
201603151800,7357,80,10.4,,,000000000
201603151800,7357,81,1050,,,000000000
201603151800,7357,82,1029,,,000000000
201603151800,7357,99,1031,,,000000000
HTTP/1.0 200 OK
Date: Tue, 15 Mar 2016 18:42:19 GMT
Server: arkimet/1.0
Content-Type: application/octet-stream
Content-Disposition: attachment; filename=agrmet.bin
```

I run `arki-server` under gdb, it seems that the `data_start_hook` is not fired. I'm in a hurry, tomorrow I'll try to do some other tests.

@brancomat I think that tomorrow `arkioss4.metarpa` should be downgraded to the previous version.

**Comment by edigiacomo** [comment]
The bug is present at least from v1.0-1, but I think that it was introduced in commit a2f0319cf6e35a9cfe92968c8043ef53f26ace28 (see https://github.com/ARPA-SIMC/arkimet/commit/a2f0319cf6e35a9cfe92968c8043ef53f26ace28#diff-ed214b1418800f006add298e50570be3L255): : in `ReadonlyDatasetServer::do_query` the hook is set on the `ProcessorMaker`, but the hook is set in the created `BinaryProcessor` only when the postprocess is set (see https://github.com/ARPA-SIMC/arkimet/blob/v1.0-4/arki/runtime/processor.cc#L356-L360).

I don't know what's the best way to fix it, but I hope that my analysis could be helpful :)

**Comment by spanezz** [comment]
Great work on tracing the cause of the problem!
