### ISSUE TITLE
option `--usn` of arki-bufr-prepare not working

### ISSUE THREAD

**Issue by brancomat** [ARPA-SIMC/arkimet#260]
test bufr attached

```
arki-bufr-prepare --usn=100 IUSD01ERSA220000.202101220000.BIN -o buttami.bufr
Traceback (most recent call last):
  File "/usr/bin/arki-bufr-prepare", line 6, in <module>
    sys.exit(BufrPrepare.main())
  File "/usr/lib/python3.8/site-packages/arkimet/cmdline/base.py", line 75, in main
    cmd.run()
  File "/usr/lib/python3.8/site-packages/arkimet/cmdline/bufr_prepare.py", line 30, in run
    res = cmd.run(
TypeError: an integer is required (got type str)
```

As suggested by @dcesari, changing `bufr_prepare.py` like this temporary fix the problem:

```
32c32
<             usn=self.args.usn,
---
>             usn=int(self.args.usn),
```

but then when `--usn` is not specified it becomes a `TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'`
[test.tar.gz](https://github.com/ARPA-SIMC/arkimet/files/5855648/test.tar.gz)

**Comment by spanezz** [comment]
I like @dcesari's approach! It annoyingly needs a more cumbersome function, like this:
```
type=lambda x: int(x) if x is not None else None,
```
which feels frustrating to me, given how common this case would be in argparse.

Anyway, pushing a fix
