### ISSUE TITLE
Issues in dataset documentation

### ISSUE THREAD

**Issue by brancomat** [ARPA-SIMC/arkimet#261]
https://arpa-simc.github.io/arkimet/datasets.html doesn't mention the `format` options that is mandatory for `iseg` datasets.

That should be documented in `doc/datasets.rst` and maybe also in `doc/datasets/iseg.rst`.

It would be great to add some example dataset (say, one for data type including error and duplicates dataset), this was already present in the ancient `doc/DATASET` (that looks like an ancestor of `doc/dataset.rst` and I think it could be safely removed).

Since the doc regards (almost) everyone I'm assigning (almost) everyone for comments or proposals.

**Comment by spanezz** [comment]
I can see documentation for `format` in that list, but the list is unsorted and quite hard for looking things up. I sorted the options alphabetically

**Comment by brancomat** [comment]
> I can see documentation for `format` in that list, but the list is unsorted and quite hard for looking things up. I sorted the options alphabetically

Whoops, my bad. Thanks.

**Comment by spanezz** [comment]
From my side there should be everything asked so far. Feel free to close the ticket, or leave it open if you want input from others as hinted
