### ISSUE TITLE
test fails: arki_scan_any.5

### ISSUE THREAD

**Issue by spanezz** [ARPA-SIMC/arkimet#27]
```
$ eatmydata make check -C arki TEST_WHITELIST="arki_scan_any.5"
[...]
arki_scan_any.5: actual value 0 is not true
  scan/any-tut.cc:232:actual(scan::scan("inbound/example_1.nc", mdc.inserter_func())).istrue()
```
This test was added in preparation for implementing NetCDF support, which then became less of a priority. It can probably be disabled until NetCDF support becomes a priority again.

**Comment by brancomat** [comment]
We actually have to manage manually some NetCDF archives so it's a thin line between "useful" and "priority" but I have no idea of the workload behind this, anyway we should probably scrap the test and open an "enhancement" issue on NetCDF support

**Comment by edigiacomo** [comment]
See #40.
