### ISSUE TITLE
Default ARKI_IO_TIMEOUT per arki-server

### ISSUE THREAD

**Issue by edigiacomo** [ARPA-SIMC/arkimet#270]
Come suggerito da @spanezz in https://github.com/ARPA-SIMC/arkimet/issues/252#issuecomment-874856006, si potrebbe impostare un `ARKI_IO_TIMEOUT` di default.

Proporrei di metterlo nella conf del servizio systemd, che dite?

E se siete d'accordo nel mettere un default, a quale valore lo impostiamo?

**Comment by brancomat** [comment]
D'accordo.
Non ho casi d'uso sulla durata di query di grandi dimensioni ma mi vien da dire che qualsiasi cosa vada oltre le 12 ore è sinonimo di problematiche (o su come è stata impostata la query o su problemi sistemistici in corso). In alternativa possiamo tenere un default più lasco (24h) e restringerlo solo sul server operativi in DR (arkioss, arkiope) a 12h o meno.

**Comment by spanezz** [comment]
Nota che non è il timeout di tutta l'operazione, ma il timeout di una singola operazione di lettura/scrittura.

Per fare un esempio, se lo si setta a mezzora, ci può essere una query che dura due giorni, a patto che ogni volta che il server manda un po' di dati al client, il client non sta mai piú di mezz'ora senza leggerli
