### ISSUE TITLE
Arki-query problems in parsing arrays for proddef values

### ISSUE THREAD

**Issue by bchiavarini** [ARPA-SIMC/arkimet#285]
Hi,
we have experienced some problems in queries that use proddef with array values. [Here](https://github.com/ARPA-SIMC/arkimet/files/7971709/proddef_to_test.zip) you can find some data where we are experiencing the problem.
When we extract a json summary on these data we obtain proddef values described in this way:
``` json
{"items":{...... 
"proddef":[
{
"type":"proddef",
"desc":"GRIB(pl=0,10,0,0, pt=3, tod=8)",
"style":"GRIB",
"value":{"pl":"0,10,0,0","pt":3,"tod":8}}
,....]}}
```
And when we use the obtained proddef values in a new query like: 
`arki-query --summary-short --json --annotate "proddef:GRIB:pl=0,10,0,0,pt=3,tod=8" proddef_to_test.grib` the result is empty.

Are array values not supported? Is there an alternative way to filter data with these kind of proddef values?

thanks for the help!

**Comment by bchiavarini** [comment]
I am trying both using
 `arki-query --summary-short --json --annotate "proddef:GRIB:pl="0,10,0,0",pt=3,tod=8" /arkimet/datasets` 
or the result of `arki-dump --query `:
 `arki-query --summary-short --json --annotate "proddef:GRIB:pl=0,10,0,0, pt=3, tod=8" /arkimet/datasets` 
but the result is still empty..

btw i didn't know the `arki-dump --query ` command, it can be useful indeed

**Comment by dcesari** [comment]
If this is shell syntax:

> I am trying both using `arki-query --summary-short --json --annotate "proddef:GRIB:pl="0,10,0,0",pt=3,tod=8" /arkimet/datasets` 

then you are just closing and reopening the quotes, not quoting them, so the result would be the same as `"proddef:GRIB:pl=0,10,0,0,pt=3,tod=8"`

**Comment by bchiavarini** [comment]
sorry, that's true.. i have retried using `arki-query --summary-short --json --annotate proddef:GRIB:pl="0,10,0,0",pt=3,tod=8' /arkimet/datasets` and it works! I can close the issue
Thank you both for the help!
