### ISSUE TITLE
Restore HTTP GET support for /query API

### ISSUE THREAD

**Issue by edigiacomo** [ARPA-SIMC/arkimet#289]
See https://github.com/ARPA-SIMC/arkimet/blob/master/doc/http-api.rst#queryqueryqueryqmacroqmacrostylestylesortsortcommandcommand and https://github.com/ARPA-SIMC/arkimet/blob/master/doc/http-api.rst#datasetnamequeryqueryquerystylestylesortsortcommandcommand.

**Comment by spanezz** [comment]
I pushed a fix that reenables GET for `/query` only.

In theory, after having removed the link to `/query` from `/` in #144, the issue of visiting the arki-server URL and clicking on a button ending up with the download of terabytes of data should be fixed, although indeed, if one manually visits `/query` on arki-server, that might be exactly what happens.

Knowing more about how the old GET API endpoints are still used by existing clients, might allow to refine the implementation, and reduce the surface of the GET API, in the code and in the documentation

**Comment by spanezz** [comment]
I agree!

Meanwhile, if the client always and only uses postprocess, I can return method not allowed on GET unless the GET also specifies the postprocess parameter

**Comment by spanezz** [comment]
I understand this is now fixed, so I'll close the issue. Feel free to reopen if I'm mistaken
