### ISSUE TITLE
Update debian package

### ISSUE THREAD

**Issue by edigiacomo** [ARPA-SIMC/arkimet#291]

**Comment by spanezz** [comment]
It builds on bullseye. In jammy building with GEOS fails, because of https://bugs.launchpad.net/ubuntu/+source/geos/+bug/1980147

**Comment by edigiacomo** [comment]
While we wati that Ubuntu people fix the issue, we could package without GEOS in order to have a full Ubuntu image (ARPA-SIMC/simc-docker-image#5).

**Comment by edigiacomo** [comment]
It seems that GEOS C++ API shouldn't be used https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1010002#20

**Comment by spanezz** [comment]
It looks like the best thing to do is a C++ wrapper to the C API that wraps the C++ API that we are currently using.

It's really strange that the Debian developer (and not upstream!) intentionally choses to break the C++ library package to force people to use the C API. GEOS is ok if people use the C++ API, only doesn't guarantee stability, so it's up to the users to deal with API changes

**Comment by spanezz** [comment]
See also: https://lists.debian.org/debian-devel/2022/09/msg00115.html

**Comment by spanezz** [comment]
With dballe after fixing https://github.com/ARPA-SIMC/dballe/issues/274, arkimet now builds on bullseye. A Python test fails for me on jammy, to be investigated

**Comment by spanezz** [comment]
Debian packages now build for bullseye and jammy!

**Comment by edigiacomo** [comment]
I moved the debian dir to ubuntu/jammy, debian/bullseye and debian/sid branches in order to build the package with git-buildpackage.

**Comment by spanezz** [comment]
It looks good and built fine
