### ISSUE TITLE
Extract ODIMH5 based on area

### ISSUE THREAD

**Issue by tgastaldo** [ARPA-SIMC/arkimet#298]
I woluld like to extract an ODIMH5 data from an arkimet archive based on area, since origin is not defined. Performing an "arki-scan -yaml" on a similar file I have found this:

> Area: ODIMH5(lat=40883000, lon=14286000, radius=0)

So, I have tried:

> rki-query  --data -o odim_202303070300_X 'reftime:=2023-03-07 03:00; area:ODIMH5,40883000,14286000;' $WORK/casi_studio/backup_radar_vol

But i get the error:

> cannot parse type of area to match: unsupported area match: ODIMH

What should I do?

Thank you!

**Comment by mnuccioarpae** [comment]
https://arpa-simc.github.io/arkimet/matcher/area.html#matching-odimh5-areas

Does this help?

**Comment by tgastaldo** [comment]
Yes! Thank you very much!
