### ISSUE TITLE
arki-check -r non fa il repack con i VM

### ISSUE THREAD

**Issue by brancomat** [ARPA-SIMC/arkimet#3]
dataset di test in arkimet@arkioss4:~/ds/agrmet

```bash
[arkimet@arkioss4 agrmet]$ arki-check .
.: 2015/01-02.vm2 should be packed
.: 2015/01-03.vm2 should be packed
.: 2 files should be packed.

[arkimet@arkioss4 agrmet]$ arki-check -f -r .
.: packed 2015/01-02.vm2 (0 saved)
.: packed 2015/01-03.vm2 (0 saved)
.: 2 files packed, 585728 total bytes freed.

[arkimet@arkioss4 agrmet]$ arki-check .
.: 2015/01-02.vm2 should be packed
.: 2015/01-03.vm2 should be packed
.: 2 files should be packed.
```

**Comment by edigiacomo** [comment]
Aggiungo che l'arki-check in queste situazioni mangia molta RAM.

**Comment by spanezz** [comment]
Ho controllato 2015/01-02.vm2 e in effetti ha i dati fuori ordine. Posso fare un repack e vedere se funziona?

**Comment by edigiacomo** [comment]
Ti ho ricreato un dataset di prova in `arkimet@arkioss4.metarpa:~/ds/agrmet`.

**Comment by spanezz** [comment]
Con una copia di quel dataset, sul mio sistema una volta fatto un repack il dataset risulta pulito.

Emanuele ora prova anche dal suo pc; se anche lí tutto funziona bene, propongo di ricompilare l'ultimo arkimet devel e reinstallarlo su arkioss4

**Comment by edigiacomo** [comment]
Confermo, con l'ultima versione del branch devel (2929a4d) fa il repack.

Domani aggiorniamo il server e se tutto va bene chiudiamo il bug.

**Comment by spanezz** [comment]
Ok, ti passo il bug

**Comment by edigiacomo** [comment]
Ho finalmente verificato e adesso funziona bene. Chiudo.
