### ISSUE TITLE
arki-server hangs forever if filter process hangs on exit

### ISSUE THREAD

**Issue by spanezz** [ARPA-SIMC/arkimet#301]
While reads and writes towards the child filter process should use a tmeout to prevent hanging forever, `wait()`ing for the child process to exit after closing its input can (and does) currently wait forever.

This should be changed to wait with a timeout, and if the timeout expires then doing the usual SIGTERM/SIGKILL escalation to stop che child process

**Comment by spanezz** [comment]
From [here](https://stackoverflow.com/questions/282176/waitpid-equivalent-with-timeout) the cleanest way to get a timeout on a wait() call would be to use `pidfd_open`, which is available in Linux 5.3 or later.

What is the minimal kernel version that we need to support?

**Comment by edigiacomo** [comment]
We must surely support Rocky Linux 8 which is distributed with kernel version 4.18, but it's possible that we need to support Centos 7 too (Linux 3.10).

**Comment by dcesari** [comment]
There is still a machine with centos 7 and arkimet around, but it is acceptable to freeze it, so that is not a problem, however Rocky Linux 8 should be supported at the moment.
