### ISSUE TITLE
match-alias.conf documentation

### ISSUE THREAD

**Issue by brancomat** [ARPA-SIMC/arkimet#318]
Unless I'm missing something, the documentation for the `match-alias.conf` file is hard to find.

There's something in `arki/matcher/parser.h`
```
    /**
     * Read the system Matcher alias database.
     *
     * The file given in the environment variable ARKI_ALIASES is tried.
     * Else, $(sysconfdir)/arkimet/match-alias.conf is tried.
     * Else, nothing is loaded.
     */
```

But it will be nice if this information would show up by searching `match-alias.conf` in https://arpa-simc.github.io/arkimet/, along with fact that if the alias definitions differs between client and server it results in a RunTime Error (see #238)

**Comment by spanezz** [comment]
Done in 2476756fc6b74c7138fcc916d6fa7574f61e9e7c.

Let me know if it contains the information you need or if there is some aspect that still needs documenting

**Comment by brancomat** [comment]
Some minor integrations in 30d331d4524a53f144750991fe2f8613141bb42d and 12edfa505d70f399e0c0a8581642e700ac1783d7.
