### ISSUE TITLE
`cat` in postprocessor hangs when called from `arki-query --postproc`

### ISSUE THREAD

**Issue by edigiacomo** [ARPA-SIMC/arkimet#32]
Server Fedora 16, `arkimet-0.80-3162`.

```
arki-query --postproc="subarea 10 40 15 45" 'reftime:=today 00:00; product:GRIB1,200,2,11 or GRIB1,200,2,17; level:GRIB1,105,2' /arkivio/arkimet/dataset/lmsmr4x52
```
hangs on the last command (`cat`).

The same problem with a [simple `cat` postprocessor](https://github.com/ARPA-SIMC/arkimet/blob/master/test/postproc/cat).

When using the postprocessor in pipe, everything is fine:

```
arki-query --inline 'reftime:=today 00:00; product:GRIB1,200,2,11 or GRIB1,200,2,17; level:GRIB1,105,2' /arkivio/arkimet/dataset/lmsmr4x52 | /usr/lib64/arkimet/subarea 10 40 15 45
```

@brancomat if the problem is already solved in a more recent version, we could wait the server update instead of fixing this bug for the `0.80` version, what do you think?

**Comment by edigiacomo** [comment]
An update of the server wouldn't solve the problem: the bug is present in `arkimet-1.0-5` (Fedora 20) too.

**Comment by spanezz** [comment]
This seems to have become unreproducible. I'll close it for now, let's reopen it if it happens again at some point.
