### ISSUE TITLE
aliases not working since v1.48

### ISSUE THREAD

**Issue by brancomat** [ARPA-SIMC/arkimet#323]
This error appeared between v1.47 (working) and v1.48 (not working)
No changes were made in the alias file.

```
arki-query --data "reftime: =2024-01-01 00; level: g00" http://arkimet.metarpa:8090/dataset/lama5_arc > tmp.grb
Traceback (most recent call last):
  File "/usr/bin/arki-query", line 11, in <module>
    main()
  File "/usr/bin/arki-query", line 7, in main
    sys.exit(Query.main())
             ^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/arkimet/cmdline/base.py", line 85, in main
    return cmd.run()
           ^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/arkimet/cmdline/query.py", line 149, in run
    query = self.session.matcher(strquery)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cannot parse Level style 'g00': only GRIB1, GRIB2S, GRIB2D, ODIMH5 are supported (parsing Level style)
```

**Comment by spanezz** [comment]
I see that between 1.47 and 1.48 there's been the switch to building with meson. Level `g00` is available in `conf/match-alias.simc.conf`  but not in `conf/match-alias.conf`.  `match-alias.simc.conf` however seems to only be installed in documentation dirs. At the moment I have no idea how 1.47 can possibly find that alias.

I'm building RPMs for both 1.47 and 1.48 to compare, let's see...

**Comment by spanezz** [comment]
To reproduce without a dataset:
```
arki-dump --query "reftime: =2024-01-01 00; level: g00"
```

**Comment by brancomat** [comment]
Missing info (sorry about that): in our arki-servers `/etc/arkimet/match-alias.conf` is a manual copy of `conf/match-alias.simc.conf`

**Comment by spanezz** [comment]
I tried to reproduce it by building tag `v1.47-1` in moncic-ci and installing it in a rocky8 machine, and it also doesn't work:
```
[root@mc-beyetasa v47]# rpm -i arkimet-1.47-1.x86_64.rpm
Warning: arkimet user not present in this system, running an arki-server will need additional configuration
[root@mc-beyetasa v47]# arki-dump --query "reftime: =2024-01-01 00; level: g00"
Traceback (most recent call last):
  File "/usr/bin/arki-dump", line 11, in <module>
    main()
  File "/usr/bin/arki-dump", line 7, in main
    sys.exit(Dump.main())
  File "/usr/lib/python3.6/site-packages/arkimet/cmdline/base.py", line 85, in main
    return cmd.run()
  File "/usr/lib/python3.6/site-packages/arkimet/cmdline/dump.py", line 72, in run
    matcher = session.matcher(self.args.input)
RuntimeError: cannot parse Level style 'g00': only GRIB1, GRIB2S, GRIB2D, ODIMH5 are supported (parsing Level style)
```

Can you point me to a system where it works?

**Comment by spanezz** [comment]
ah ok! Now I can reproduce it

**Comment by spanezz** [comment]
The version now on the arkitest machine seems to work. It looks like the refactoring done to make alias information show with `arki-dump --info` accidentally fixed the problem
