### ISSUE TITLE
Update build instructions in README.md 

### ISSUE THREAD

**Issue by edigiacomo** [ARPA-SIMC/arkimet#329]
Given that both RPM and Debian packages are built using Meson and therefore this is the only tested build system, we could update the documentation from autotools to Meson, what do you think?

https://github.com/ARPA-SIMC/arkimet/blob/186a047363e530515dae17bee6d6999620061751/README.md?plain=1#L44-L53

**Comment by brancomat** [comment]
Ok, it makes sense
