### ISSUE TITLE
build errors on Rocky9

### ISSUE THREAD

**Issue by brancomat** [ARPA-SIMC/arkimet#338]
full log:
https://simc.arpae.it/moncic-ci/arkimet/202410080827/master/rocky9/build.log

relevant bit:
```
 * Test failures

arki_dataset_concurrent_grib_simple_plain.write_repack: value '0' is different than the expected '61'
  ../arki/dataset-concurrency-test.cc:506:actual(count) == 61u
```

**Comment by spanezz** [comment]
I failed to reproduce this on my rocky9 moncic-ci image. Is there a machine where it reproduces reliably?

**Comment by brancomat** [comment]
Apparently in the CI build after https://github.com/ARPA-SIMC/arkimet/commit/633616f44390d7b8681483ff3a7ce7f616ec8bdb the error disappeared.
I'll reopen the issue should this reoccur.
