### ISSUE TITLE
Concorrenza di arki-scan --import

### ISSUE THREAD

**Issue by edigiacomo** [ARPA-SIMC/arkimet#36]
Quali tipi di dataset supportano `arki-scan --import` concorrenti?

In particolare la cosa ci interessa (a me e @brancomat) per i dataset di tipo `error` e `duplicates`, in quanto vorremmo assegnare uno o più dataset ad un singolo script (e qui non c'è concorrenza, a maggior ragione usando dei `conf` ad-hoc) ma scriverebbero tutti sugli stessi dataset `error` e `duplicates`.

**Comment by spanezz** [comment]
In teoria, *tutti*. In pratica, ora scrivo un po' di test per chiarire la cosa una volta per tutte.

Già che si parla di riorganizzare gli script, non è detto che errors e duplicates debbano essere dei dataset, e ci possono essere altre strategie.

Per esempio, si può anche dire che se lancio `arki-scan --dispatch=conf --duplicates=duplicates/ --errors=errors/ foo.grib2`, allora le parti che danno errore di `foo.grib2` me le scrive in `errors/foo.grib2` e quelle già importate in `duplicates/foo.grib2`.

**Comment by edigiacomo** [comment]
Interessante, non so cosa ne pensa @brancomat a proposito.

Per me, i dataset con scrittura concorrente (e se sono tutti la cosa è ancora più interessante) sono sufficienti. Considera che anche l'opzione `--moveko` non l'abbiamo mai usata, preferendo cose del tipo: `arki-scan --dispatch=config $FILE || mv $FILE /path/to/err`.

**Comment by spanezz** [comment]
Ho aggiunto un test, la pratica è diversa dalla teoria. Ci lavoro nei prossimi giorni.

**Comment by edigiacomo** [comment]
Ok, grazie. Comunque, la concorrenza tra importatori non è una cosa urgente, in quanto attualmente non stiamo facendo affidamento sul dataset `error` (usiamo il `||` bovino del mio precedente commento).

**Comment by spanezz** [comment]
Ho implementato (b9ca6b21c90c088c8b62c2e378d38aafd0f3affa) locking e ora stando agli unit test tutti i dataset sono usabili da piú importer paralleli.
