### ISSUE TITLE
.archive/last riscrivibile (update/delete) per dataset ondisk2

### ISSUE THREAD

**Issue by edigiacomo** [ARPA-SIMC/arkimet#4]
Sarebbe utile avere il `last` riscrivibile per eventuali correzioni di dati archiviati in `last`.

**Comment by spanezz** [comment]
This opens a slippery slope I'm uncomfortable with: once last is writable, then also older archived data should be writable for possible corrections.

Would it be possible to keep last and all the archives read only as they are now, and in the rare cases when corrections are needed one can bring the segments back into the normal datasets, rescan them, correct them, then archive them again?

**Comment by edigiacomo** [comment]
Thank Enrico, I'm already doing what you're suggesting with a shell script. The only thing I'm worried about is the concurrency - and I think that an `arki-check` could handle it in a more clean way.

**Comment by spanezz** [comment]
Would it work to have a way, with arki-check, to move a segment back online in a concurrency-safe way?

**Comment by edigiacomo** [comment]
La commit c9e282d non c'entra, è un refuso nel messaggio di commit, scusate.

**Comment by spanezz** [comment]
Implemented arki-check --unarchive in b5cc5af520559d3adcd9a43a080b02a129587886

**Comment by edigiacomo** [comment]
We should test `--unarchive`, then the issue can be closed.

**Comment by brancomat** [comment]
`--unarchive` is mostly working except for a small issue (#100) not really related to this one
