### ISSUE TITLE
Add NetCDF support

### ISSUE THREAD

**Issue by edigiacomo** [ARPA-SIMC/arkimet#40]
- [x] Add NetCDF test file
- [x] Implement NetCDF scanner and test suite (@spanezz) (see https://github.com/ARPA-SIMC/arkimet/commit/4c7a798af36a6dd9ae00a4418e477d9755c1c159)

**Comment by spanezz** [comment]
Additionally to the NetCDF test file, I would like to also have an actual usage scenario, as in "This is going to be used by $TEAM to archive $DATA for $USE"

**Comment by brancomat** [comment]
Since nobody around here was able to provide an actual usage scenario with a sufficient level of details I'm out 😀 
I'm removing myself from the assignees but I'm leaving the issue open if ever anybody will provide additional informations

**Comment by brancomat** [comment]
After internal discussion, these prerequisites are deemed necessary to implement netcdf support:

- files should be supported (read) by libnetcdf4 
- datasets should be described with actual usage scenarios (see comment above) and basic file informations (max size expected, headers, etc)
- all the informations should be contained in the netcdf file (i.e. for forecast data: reference time, forecast time or forecast step)

**Comment by spanezz** [comment]
I notice that all the examp,le NetCDF I received so far declare following CF conventions: http://cfconventions.org/

I'm basing the first experiment on that assumption.

**Comment by spanezz** [comment]
arkimet (in branch `issue40`) can now scan NetCDF files. `conf/scan/netcdf.py` exists, but does nothing at the moment.

The next step is to play a bit with ncdump and the python netCDF4 module to see what data we have, what metadata we expect, and how to get there. I would need help with regards to "what metadata we expect" part.

**Comment by spanezz** [comment]
I received the mail with new samples from Lidia, and sent a new prototype scan as a reply

**Comment by spanezz** [comment]
Meanwhile I added tests for read/write/check of NetCDF in datasets, and after fixing a small bit of code, they pass.

I'd say that for this ticket the only part left is to perfect NetCDF scanning.

**Comment by spanezz** [comment]
I've opened #239, #240, and #241 for perfecting NetCDF scanning on the use case that we have at the moment.

Would it be ok to merge this to master and close close this issue, leaving the rest of the work to specific tickets?

**Comment by brancomat** [comment]
ok with me
