### ISSUE TITLE
arki_scan_odimh5.* test fail with Lua 5.3

### ISSUE THREAD

**Issue by edigiacomo** [ARPA-SIMC/arkimet#41]

**Comment by spanezz** [comment]
Note that Lua versions its language differently than others: Lua 5.1 is a different language from Lua 5.2 or 5.3, applications are supposed to target only one version of the language, and distributions are supposed to provide multiple ones as applications require, like they provide python2 and python3.

I recall that Fedora 20 did packaging wrong in this case, only packaging what they thought was the latest version of Lua 5. Is it the same with Fedora 24?

**Comment by edigiacomo** [comment]
> Is it the same with Fedora 24?

I think so.
