### ISSUE TITLE
Dubbio sulla conversione da Lua number a integer in ValueBag

### ISSUE THREAD

**Issue by edigiacomo** [ARPA-SIMC/arkimet#42]
Il bug #41 mi ha fatto venire un dubbio sulla conversione da double a int nei metadati settati da Lua (in `ValueBag::load_lua_table`): attualmente (con Lua < 5.3 o dopo la fix di #41 b94e2067e3bcd4995c67d659cd9962e38ab2e2f0) il double viene troncato automaticamente.

Questo comportamento mi pare essere sempre stato implicito e la suddetta fix ha mantenuto la retrocompatibilità per poter pacchettizzare la nuova versione di arkimet in tempi brevi (e anche perché nessuno si è mai lamentato del troncamento).

Tuttavia, la cosa dovrebbe essere formalizzata oppure si potrebbe decidere che il troncamento/arrotondamento è delegato agli scanner Lua - ma in tal caso credo sarebbe meglio usare `lua_tointegerx` e lanciare un'eccezione in caso di conversione fallita da double ad int.

**Comment by brancomat** [comment]
Ok, come si diceva i problemi sono due:

1. Se il troncamento sia un comportamento accettabile (rispetto ad es. all'arrotondamento) e questo mi pare _al momento_ sia assodato: riguarda in realtà solo un subset degli odimh5, potrebbe essere rimesso in discussione ad esempio da eventuale introduzione dei netcdf e questo ci porta a...

1. Documentare la cosa. Sul dove però ho qualche dubbietto.

**Comment by spanezz** [comment]
`ValueBag` supporta solo valori interi e stringhe, quindi il troncamento c'è sempre stato. L'idea è, in fase di scan, scalare i valori; per esempio le latitudini non sono restituite in gradi ma in milionesimi di grado. Per esempio, in `scan-grib2/01-common.lua`:
```lua
area.latfirst = grib.latitudeOfFirstGridPointInDegrees * 1000000
area.lonfirst = grib.longitudeOfFirstGridPointInDegrees * 1000000
```

**Comment by edigiacomo** [comment]
Forse mi sono spiegato male: sono cosciente del fatto che il troncamento c'è sempre stato e che ValueBag gestisce solo stringhe e interi (ho scritto anche alcune parti in Lua dello scanner odim), il mio dubbio riguardava il passaggio e la gestione (documentata) di un valore non intero al ValueBag da Lua (troncamento, eccezione, arrotondamento, altro).

**Comment by spanezz** [comment]
Ah, scusa, avevo interpretato male il bug.

[Lua non fa distinzione tra numeri interi e floating point](http://lua-users.org/wiki/NumbersTutorial), quindi per lanciare un'eccezione servirebbe un controllo su quanto piccola è la parte frazionaria di un numero, e come approccio non mi piace.

Considerando che chi scrive script di scansione spero guardi i risultati di quello che ha scansionato prima di metterli in produzione, propenderei per troncamento (perché mi aspetto che il codice Lua sia conscio dello star generando valori interi) e documentazione.

C'è documentazione relativa a questo aspetto di arkimet, al momento?

**Comment by edigiacomo** [comment]
Benissimo il troncamento. Per la documentazione, ho solo aggiunto una riga in c9e282d (il messaggio fa riferimento ad una issue diversa, è un refuso)

**Comment by edigiacomo** [comment]
Chiudo, per me come doc è sufficiente.
