### ISSUE TITLE
arkimet/server not installed

### ISSUE THREAD

**Issue by dcesari** [ARPA-SIMC/arkimet#45]
Arkimet rpm package was successfully built, including tests, but when starting the python arki-server I get the error:

Traceback (most recent call last):
  File "/usr/bin/arki-server", line 12, in <module>
    from arkimet.server import views
ImportError: No module named 'arkimet.server'

actually `/usr/lib/python3.x/site-packages/arkimet/server` directory is not installed, is it a makefile or a spec problem?

**Comment by spanezz** [comment]
It was a makefile problem, should be fixed now
