### ISSUE TITLE
probably off-by-one bug in importing OR repacking data (maybe already fixed)

### ISSUE THREAD

**Issue by brancomat** [ARPA-SIMC/arkimet#51]
vado in italiano che già è complicata così:

- i dataset `gts_bufr` e `gts_synop` hanno errori tipo
  ```
  BUFR validation failed: buffer does not end with '7777'
  ```
 e apparentemente manca un byte alla fine
  (i dataset sono stati copiati e accessibili da server di sviluppo su `/autofs/scratch2/dbranchini/dataset_gts`)

- questi errori non avrebbero passato un `arki-scan` quindi l'errore sta presumibilmente a valle di acquisizione e preparazione dati
- l'ultimo di questi errori nel dataset gts_temp risale al 10/04/2016 nel dataset `gts_temp`:

  ```
  Cannot parse BUFR message #1225: 2016/04-10.bufr:8871404+992: section 5 does not contain '7777' (0b inside section End section) at offset 8871404.
  ```
 - questo il susseguirsi degli aggiornamenti sul server arkimet:

  ```
  1.0.5 dal 05/11/2016
  1.0.6 dal 11/04/2015
  1.0.7 dal 03/05/2016
  ```
  quindi TEORICAMENTE (a meno che non ci sia di mezzo un problema di repack) dalla 1.0.7 il problema non si è più presentato

Attività auspicabili nell'ordine:

- [ ] identificare problema e escludere che sia ancora presente
- [ ] diagnosticare dati affetti e sanarli
- [ ]  capire quando è stato introdotto (bonus)

**Comment by spanezz** [comment]
Ora lavoro a una nuova opzione di arki-scan per trovare e *correggere* i BUFR corrotti. Una volta corretti i dataset, possiamo usare la stessa opzione per monitorarli ogni due/tre mesi per vedere se il problema si ripresenta.

**Comment by spanezz** [comment]
Ho fatto un branch `issue51` in cui ho implementato `arki-check --issue51 [--fix]`.

È possibile installarlo su arkimet, o anche solo buildarcelo in modo che si possa lanciare dalla build directory?

**Comment by spanezz** [comment]
Una settimana dopo aver lanciato `arki-check --issue51 --fix` sui due dataset che avevano dati corrotti (`gts_synop` e `gts_temp`), ho rilanciato `arki-check --issue51` su quei dataset e ora sembra tutto a posto.

Che dite, chiudiamo questo issue e mettiamo in programma di rifare un check tra un mese o due?

**Comment by brancomat** [comment]
Andata
