### ISSUE TITLE
Ordinamento VM2

### ISSUE THREAD

**Issue by edigiacomo** [ARPA-SIMC/arkimet#52]
**TL;DR**: come faccio ad ordinare dei `VM2` in modo analogo a quanto fatto da `arki-check -fr`?

Dovendo fare un'importazione molto grossa di dati `VM2`, ho pensato di ricreare i dataset a mano.

Ogni dataset ha il config con la seguente struttura:
```
type = ondisk2
step = daily
smallfiles = yes
shard = monthly
unique = reftime, area, product
index = reftime, area, product
filter = area:VM2:rep=NAME
```

(`NAME` è il nome della rete, ma questo è trascurabile, per i test basta un unico dataset con `filter = area:VM2,`)

Dopo aver sistemato i dati a mano, prima di usare l`arki-check` per ricreare l'indice, vorrei riordinare i dati, in modo che un repack non sia necessario (i dati sono già univoci).

Purtroppo, non capisco in che modo i dati siano ordinati. Ho provato un `sort -t, -n -k1,1 -k2,2 -k3,3` (ordino come lo 'unique`), ma `arki-check -f -r` mi riordina comunque i dati secondo un criterio che non capisco:

```
$ head dataset/agrmet/2000-01/01/01.vm2
200001010000,2313,305,21,,,
200001010000,2312,305,21,,,
200001010000,2307,305,21,,,
200001010000,2301,305,21,,,
200001010000,2313,257,192,,,000000000
200001010000,2312,257,433,,,000000000
200001010000,2307,257,0,,,000000000
200001010000,2301,257,0,,,000000000
200001010000,2309,233,6.2,,,000000000
200001010000,2302,233,4.9,,,000000000
$ sort -t, -n -k1,1 -k2,2 -k3,3 dataset/agrmet/2000-01/01/01.vm2 | head
200001010000,2287,78,-4.5,,,000000000
200001010000,2289,78,-3.5,,,000000000
200001010000,2290,78,-4.7,,,000000000
200001010000,2292,78,-2.4,,,000000000
200001010000,2293,78,-.9,,,000000000
200001010000,2296,78,-2.8,,,000000000
200001010000,2297,78,1.4,,,000000000
200001010000,2298,78,1.3,,,000000000
200001010000,2299,78,.2,,,000000000
200001010000,2305,78,-5.6,,,000000000
```

In allegato, il file [01.vm2.zip](https://github.com/ARPA-SIMC/arkimet/files/484896/01.vm2.zip) come è stato repack-ato da `arki-check -f -r` (`v1.0-14`).

**Comment by spanezz** [comment]
Guardando il codice, arkimet al momento ordina solo per reftime, e se l'algoritmo è stabile (credo che lo sia) il resto lo lascia com'era prima.

Che dici, cambiamo arkimet per ordinare, al repack, per reftime e una serie di altri metadati?

**Comment by edigiacomo** [comment]
Mi va benissimo l'ordinamento solo per reftime, però mi pare l'esempio che ti ho passato provi che arkimet non lascia il resto com'era prima.

Però dorse mi sono spiegato male: i dati messi a mano dentro al dataset sono già ordinati per reftime, area e product e arkimet li riordina poi nel modo che ti ho scritto.

**Comment by spanezz** [comment]
Correzione, nei dataset ondisk2 dovrebbe ordinare per reftime e offset, e quindi mantenere l'ordinamento originale.

Direi che sia un bug. Mi puoi dare un file di prova (se possibile piccolo, cosí posso aggiungerlo alla test suite) e uno script che riproduca il problema?

**Comment by edigiacomo** [comment]
Grazie Enrico, faccio lo script, il file di prova è quello già allegato [01.vm2.zip](https://github.com/ARPA-SIMC/arkimet/files/484896/01.vm2.zip)

**Comment by edigiacomo** [comment]
Allego qui [test.sh.zip](https://github.com/ARPA-SIMC/arkimet/files/492906/test.sh.zip), che incredibilmente passa. Probabilmente, la settimana scorsa mi ero bevuto qualcosa :|

Chiedo scusa...
