### ISSUE TITLE
Discriminare messaggi importati da quelli non importati

### ISSUE THREAD

**Issue by edigiacomo** [ARPA-SIMC/arkimet#54]
In fase di importazione, mi servirebbe avere una copia dei messaggi importati separati da quelli non importati all'interno di un solo file. E' possibile ottenere quest'informazione?

**Comment by spanezz** [comment]
Al momento non è possibile, posso implementarlo.

Supponiamo di avere un comando di questo tipo:

```
arki-scan --dispatch=datasets.cfg *.grib *.bufr *.odim *.vm2
```

E supponiamo di avere un'opzione per avere in output i file non importati correttamente.

Come ti aspetti di avere i dati in output?

Vuoi che i dati non importati vadano anche in error e duplicates, o che finiscano solo nell'output?

**Comment by edigiacomo** [comment]
Il comportamento attuale lo lascerei invariato per retrocompatibilità.

Un'idea potrebbe essere quella di avere qualcosa di analogo alle opzioni `--move-ok` e `--move-ko`, ma in cui i file generati contengono solo, rispettivamente, i record correttamente importati e non.

**Comment by spanezz** [comment]
Cosí su due piedi propongo `--copy-ok` e `--copy-ko` a cui si passa una directory in cui vengono creati file con lo stesso nome dei file in input, ma in cui vengono copiati i dati correttamente importati o non correttamente importati.

Nota che in caso di errore di parsing sui file in input tale per cui un dato non possa essere letto, il dato non può venire copiato in `--copy-ok` e `--copy-ko`, per cui se buttassi via l'input per tenere solo il file in `--copy-ko`, perderesti i dati non parsabili.

**Comment by edigiacomo** [comment]
Va benissimo e mi pare più che ragionevole.

**Comment by brancomat** [comment]
Non mi piace tantissimo l'ambiguità che potrebbe nascere dalle due opzioni (non è così evidente che le `--move-` siano riferite al file unico e le `--copy-` ad un subset del contenuto, tanto più che `move` e `copy` sono genericamente operazioni riferite alla stessa tipologia di oggetto) ma al momento non ho idee migliori se non robe cervellotiche tipo `--dispatchedok` e `--dispatchedko`  quindi dico ok.

Giusto per capire meglio il caso di errore di parsing: non verrebbe differenziato fra `--copyok` e `--copyko` MA finirebbe in un eventuale `--moveko`, giusto?

**Comment by spanezz** [comment]
@brancomat, giusto: supponiamo di avere un file input.grib con 3 GRIB dentro, il primo che si importa correttamente, il secondo che non entra in nessun dataset, e il terzo troncato in modo che finisca solo con `777` e non si possa parsare.

Supponiamo di fare `arki-scan --dispatch=cfg --moveok=dirmok --moveko=dirmko --copyok=dircok --copyko=dircko`.

Troveremmo:

* `dircok/input.grib` con dentro il primo GRIB
* `dircko/input.grib` con dentro il secondo GRIB
* `dirmko/input.grib` con dentro il file originale `input.grib`

E il secondo GRIB lo troveremmo anche nel dataset `error`.

**Comment by edigiacomo** [comment]
L'ho catalogato come bloccante per lo sviluppo in quanto vorremmo implementare una coda FIFO che permetta di inviare a vari destinatari i dati correttamente importati in Arkimet.
