### ISSUE TITLE
Do we need to support different data formats in the same dataset?

### ISSUE THREAD

**Issue by spanezz** [ARPA-SIMC/arkimet#59]
At the moment, arkimet theoretically supports having data in multiple formats in the same dataset, although this is not being tested.

Unless I missed something, in actual use, only one data type is ever stored in a dataset. There is a dataset full of GRIB data, one full of BUFR data, and no dataset with both GRIB and BUFR at the same time.

Can I make this official, add the data type to the dataset configuration, and enforce that only data of that type ever enters the dataset? This would also make the dataset implementation a little simpler.

**Comment by dcesari** [comment]
I hardly see the need to mix different data in a single dataset, provided that grib1 and grib2 are simply GRIB, so I think it's acceptable.
AFAIU the filter keyword does not unambiguously determine the data format at the moment, correct? So the data type keyword will be compulsory?!

**Comment by spanezz** [comment]
Correct, grib1 and grib2 are both considered grib by data handling routines, and are only differentiated during scanning.

Also correct, the filter does not unambiguously determine the data format: there could be other formats that scan to a GRIB-style origin or area, for example.

Ideally the data type keyword would be compulsory, and we can reason of a transition implementation, like for example of the data type keyword is missing, the dataset data type is assumed to be the one of the first segment that is found in the index.

**Comment by dcesari** [comment]
Can we close this issue?

**Comment by spanezz** [comment]
Yes, it's time to close this. I have been making this assumption ever since after @brancomat's reply
