### ISSUE TITLE
Cannot compile with wibble embedded

### ISSUE THREAD

**Issue by edigiacomo** [ARPA-SIMC/arkimet#6]
- `wibble/config.h` not found: when compiling the directory `embedded/wibble/wibble`, the directory itself should be included in the headers search path.
- `#ifdef POSIX` in `embedded/wibble/wibble/net/server.cpp` fails.

In commit bd063ae855 I patched the fedora package .The same patches could be applied directly to wibble.

**Comment by spanezz** [comment]
Thanks. I'm currently more interested in getting rid of wibble than in fixing it, so unless this is breaking something that needs an urgent fix, I would prefer to work on other things and remove wibble from arkimet as soon as we can compile it with a C++11 compiler.

**Comment by edigiacomo** [comment]
Then I close the issue: the Fedora patch is good enough for us.
