### ISSUE TITLE
New dataset format: one index per segment

### ISSUE THREAD

**Issue by spanezz** [ARPA-SIMC/arkimet#60]
If each dataset strictly supports only one data type, and the segment step is strictly enforced, then segment pathnames are a function of just the reference time of the data.

This means that duplicate data detection can happen at the segment level, instead of the dataset level, and that a dataset does not need a dataset-wide index, except to speed up queries that do not have any reference time bound. Non-reftime-bound queries do not seem to be frequent and time critical enough to need speeding up, though.

It could be worth exploring a new dataset type with no dataset-wide index, and one .sqlite index per segment. The index would need to store only reference time, metadata, processing log notes, and data offsets in the segment.

It potentially would be a dataset that does not require a dataset-level locking, although segment-level locking would likely still be needed.

**Comment by edigiacomo** [comment]
Mi sembra un tipo di dataset abbastanza simile al caso di uno sharded con `shard=step` e anche lo sharded dovrebbe garantire un locking su un sottoinsieme del dataset (lo shard stesso) - e se non lo fa, ti apro subito una issue :)

Parlando con @brancomat direi che attualmente non ci lanceremmo nella rigenerazione di dataset già consolidati come quelli `GRIB` e `BUFR`, mentre per i `VM2` siamo orientati sullo sharded (visto che è già implementato).

**Comment by spanezz** [comment]
Done in b2d6e96c501a77eb4cb6754ecf0a40eba05c3586

When you have time you can test the new datasets: the configuration they require is:
```
type = iseg
format = grib|bufr|vm2|odimh5
```
In order to be able to enumerate the segments of the right kind, they need to be told explicitly what data format they are going to store.

**Comment by spanezz** [comment]
Note, on venti a group of unit tests fail tagged with `arki_dataset_concurrent_*`: that is because on Fedora 20 I need to fall back to per-process locks instead of per-file-descriptor locks, which makes it impossible to simulate a situation when repack happens while a client is reading data without seriously complicating the test code.

**Comment by brancomat** [comment]
So, after only two weeks from @spanezz request I've repackaged arkimet. Since `arki_dataset_concurrent_*` unit tests were failing on F20 I disabled `make check` on F20 systems (more elegant solutions are welcomed but not mandatory)

@edigiacomo: let's keep the bug open until we manage to test the new dataset

**Comment by edigiacomo** [comment]
I'm testing this dataset and it works without problems.

@spanezz just a question: using an `iseg` dataset, should I worry about repacking and scanning concurrently?

**Comment by edigiacomo** [comment]
@spanezz it seems that while repacking it's possible to query data but dispatching awaits - maybe `arki-check -f -r` locks the whole dataset?

**Comment by edigiacomo** [comment]
> @spanezz just a question: using an iseg dataset, should I worry about repacking and scanning concurrently?
> @spanezz it seems that while repacking it's possible to query data but dispatching is suspended - maybe arki-check -f -r locks the whole dataset?

I've opened the issue #108 - which I think it's the last step for the review of this issue.

**Comment by edigiacomo** [comment]
Related issue #115
