### ISSUE TITLE
Parametri GET non più presenti

### ISSUE THREAD

**Issue by edigiacomo** [ARPA-SIMC/arkimet#63]
Ci capita di fare query su arkimet usando dei client HTTP (e.g. cURL, wget, etc). La cosa non è più possibile dalla versione `1.0-16` in quanto l'arki-server non riconosce più alcuni parametri GET.

Alcuni esempi:
- http://arkioss:8090/dataset/locali/summary?style=json
- http://arkioss:8090/dataset/locali/query?style=postprocess&command=json&query=reftime:=today

Attualmente, i casi in cui usiamo un client HTTP sono: 

1. Non è possibile installare arkimet sul client
2. Per evitare di lanciare sottoprocessi (e.g. ho un'applicazione web in Python che scarica i dati da arkimet)

**Comment by dcesari** [comment]
Scusate, mi intrometto perché l'argomento mi interessa, possiamo affermare che l'arki-server ha una "web-api" (stabile|documentata|varieedeventuali)? qualche tempo fa debuggando arki-query con strace avevo notato che fa una serie di richieste http non ovvie e mi ero messo il cuore in pace.

**Comment by spanezz** [comment]
@dcesari si, possiamo affermare che la web api di arki-server sia stabile, anche perché c'è da mantenere la compatibilità con degli `arki-query` molto vecchi.

Se vuoi costruirci sopra, apri magari un ticket per avere un `arki-server-webapi.md` con la documentazione delle varie chiamate.

**Comment by edigiacomo** [comment]
Mi dispiace riaprilo a distanza di una settimana, ma non avevo controllato con sufficiente attenzione:

> http://arkioss:8090/dataset/locali/summary?style=json

Continua a restituire dati in formato binario (`arkimet-1.0-17`).

**Comment by brancomat** [comment]
Aggiungo che a questo punto vincolerei la ripacchettizzazione alla chiusura del #64
