### ISSUE TITLE
Test per web api di arki-server

### ISSUE THREAD

**Issue by edigiacomo** [ARPA-SIMC/arkimet#64]
Con riferimento a #63, sarebbe utile avere dei test sulle web api.

**Comment by spanezz** [comment]
I test sulle web api al momento ci sono (`src/arki-server-test.cc`) limitatamente alla parte delle web api usata da `arki-query`.

Per testare il resto delle web api, mi serve un elenco di quali web api sono usate al di fuori di arki-query (e a quel punto i test ne diventano anche una documentazione).

Sto aggiungendo un test per `/dataset/<nome>/summary?style=json`; ce ne sono altre?

**Comment by edigiacomo** [comment]
Sulle macchine in cui non è possibile installare Arkimet, mi basta poter scaricare il summary in formato JSON (con parametro `query` opzionale) e i dati postprocessati (cosa già possibile, mi pare).

A suo tempo, avevo implementato anche `/dataset/<nome>/summaryshort`. Tuttavia, posso farne temporaneamente a meno se passeremo in futuro ad un client Python.

**Comment by spanezz** [comment]
Ok, allora mancano solo i test (e l'implementazione) di summaryshort. Mi ricordi cosa faceva?

**Comment by edigiacomo** [comment]
E' simile al summary, ma raggruppa per metadato. Qui fondo trovi un esempio, altrimenti puoi lanciare il comando `arki-query --summary-short 'reftime:=today' http://arkimet.metarpa:8090/dataset/lmsmr4x52`

```json
{
    "items": {
        "summarystats": {
            "b": [
                2016,
                12,
                22,
                0,
                0,
                0
            ],
            "e": [
                2016,
                12,
                22,
                12,
                0,
                0
            ],
            "c": 11432,
            "s": 2128912768
        },
        "origin": [
          {
                "t": "origin",
                "s": "GRIB1",
                "ce": 200,
                "sc": 255,
                "pr": 59
            }
        ],
        "product": [
          {
                "t": "product",
                "s": "GRIB1",
                "or": 200,
                "ta": 2,
                "pr": 2
            },
            ...
         ],
     "level": [
         ...
     ],
     ...
}
```

**Comment by spanezz** [comment]
Implementato, incluso il test
