### ISSUE TITLE
Risposta di arki-query --inline troncata

### ISSUE THREAD

**Issue by edigiacomo** [ARPA-SIMC/arkimet#66]
arki-query non restituisce tutti i dati presenti. Il problema pare presentarsi con ~100K dati.

```
$ arki-query --inline "product: hmixdia" http://arkimet.metarpa:8090/dataset/lamaz | arki-xargs --time-interval=day grib_get -PdataDate,dataTime > /tmp/log
$ sort /tmp/log | tail -n1
20160904 900
$ arki-query --summary --dump --summary-restrict=reftime "product: hmixdia" http://arkimet.metarpa:8090/dataset/lamaz
SummaryItem:
SummaryStats:
  Count: 116345
  Size: 9983254764
  Reftime: 2003-04-01T01:00:00Z to 2016-12-18T00:00:00Z
```

**Comment by spanezz** [comment]
Il problema sembra essere in arki-server:
```
$ arki-query --inline "product: hmixdia" /…/dataset/lamaz | arki-xargs --time-interval=day grib_get -PdataDate,dataTime  > hmixdia-local.log
$ arki-query --inline "product: hmixdia" http://…/dataset/lamaz | arki-xargs --time-interval=day grib_get -PdataDate,dataTime  > hmixdia-remote.log
$ ls -la hmixdia*.log
-rw-rw-r-- 1 arkimet arkimet 1575131 Jan  2 13:24 hmixdia-local.log
-rw-rw-r-- 1 arkimet arkimet 1510898 Jan  2 13:23 hmixdia-remote.log
```

**Comment by spanezz** [comment]
E sembra un problema di arki-server che muore per uso eccessivo di ram:
```
$ dmesg
[8469308.403281] Out of memory: Kill process 12390 (arki-server htt) score 917 or sacrifice child
[8469308.406925] Killed process 12390 (arki-server htt) total-vm:9720424kB, anon-rss:7357548kB, file-rss:0kB
```
e da ps con una query in corso:
```
arkimet  31021 20.8 42.9 3831584 3515352 ?     D    15:40   2:14 arki-server http://arkimet.metarpa:8090/dataset/lamaz/query for 172.20.1.158
```

**Comment by enrenr** [comment]
-E sembra un problema di arki-server che muore per uso eccessivo di ram:

...corrisponde alla natura errabonda e non riproducibile dell'errore...
Siccome il problema para porsi solo con query particolarmente lunghe, non è
che magari da qualche parte dentor arkimet c'è qualcosa che allocca memoria
senza liberarla, andando progressivamente a rimepire la RAM? (Possibile
ipotetico indizio: ho l'impressione che il problema si verifichi solo
quando la query è in pipe ad arki-xargs)

Ciao e auguri!
Enrico

$ dmesg

**Comment by spanezz** [comment]
Si, sospetto sia legato all'uso di `--inline`, ora metto su una filiera di test per verificare meglio dove viene persa RAM.
