### ISSUE TITLE
arki-server: when streaming results, append a status packet at the end

### ISSUE THREAD

**Issue by brancomat** [ARPA-SIMC/arkimet#71]
Currently after arki-server starts streaming results, the HTTP 200 status code has been sent and arki-query has no way to know that the streaming was interrupted because of an error server-side (like in #66).

The client-server protocol can be updated to transmit an extra metadata item at the end containing an "all ok" indication.

This would break backwards compatibility, but could be enabled only if the client adds something like `protocol=1.1` to the query, so old clients are not affected.

This would not work in case of `arki-query --data`, because data streamed in that case is not wrapped in extra metadata. It's worth considering implementing `arki-query --data` like `arki-query --inline`, discarding the arkimet envelopes before outputting the data.

**Comment by edigiacomo** [comment]
Questa issue è stata chiusa per inattività. Nel caso in cui sia un argomento ancora rilevante, si prega di riaprirla con una motivazione che tenga conto delle modifiche applicate nel corso degli anni al progetto.
