### ISSUE TITLE
arki-query autenticata

### ISSUE THREAD

**Issue by dcesari** [ARPA-SIMC/arkimet#72]
Sarebbe utile avere la possibilità di usare arki-query con un server https autenticato es. con apache mod_proxy davanti all'arki-server, quindi:
1. passare al server le informazioni di autenticazione, es. leggendole da `.netrc`
2. gestire gli url https://
3. ehm...(problema strettamente personale) poter gestire un server https con certificato autofirmato, opzione -k di curl

**Comment by dcesari** [comment]
Il punto 3 è risolto con letsencrypt, spero in maniera duratura, possiamo limitarci ai primi due.

**Comment by edigiacomo** [comment]
La PR #85 risolve il punto (1), mentre il punto (2) è già [gestito da arkimet][1].

[1]: https://github.com/ARPA-SIMC/arkimet/blob/97a0ca3b7a4d2b0e002da76e43ca6640da3accbb/arki/dataset.cc#L317
