### ISSUE TITLE
Appending arkimet metadata

### ISSUE THREAD

**Issue by dcesari** [ARPA-SIMC/arkimet#74]
Is this incremental indexing
```
> index.arkimet
for file in file?; do
    arki-scan grib:$file >> index.arkimet
done
```
equivalent to
```
arki-scan grib:file1 grib:file2 > index.arkimet
```
? In other words, can I append binary arkimet metadata?

**Comment by edigiacomo** [comment]
> In other words, can I append binary arkimet metadata?

I think so. But you can test it:

```
$ for f in file? ; do arki-scan grib1:$f >> index1.arkimet ; done
$ arki-scan grib:file1 grib:file2 > index.arkimet
$ diff -y <(arki-dump index1.arkimet) <(arki-dump index2.arkimet)
```

The differences are related only to the order if the record and the `Note` metadata.

**Comment by dcesari** [comment]
Thanks, satisfactory, but I suspect a bug, #75
