### ISSUE TITLE
arki-scan refuses to scan files with the same name in different dirs

### ISSUE THREAD

**Issue by dcesari** [ARPA-SIMC/arkimet#75]
The following command (see attached examples [bug_arki-scan.zip](https://github.com/ARPA-SIMC/arkimet/files/760383/bug_arki-scan.zip)):
```
arki-scan --yaml lon.grib lat.grib
```
scans both (different) grib files, the same command applied to copies of the two previous files in different subdirectories, with the same file name in each:

```
arki-scan --yaml sub1/ll.grib sub2/ll.grib
```
scans only the first file. **Is it a bug or a feature?**
(originally for clarity sub?/ll.grib were symbolic links to the other files, but zip does not conserve links, anyway the juice does not change).

**Comment by edigiacomo** [comment]
I think #73 is related.

**Comment by spanezz** [comment]
This looks like a bug: it should scan all files given as arguments

**Comment by spanezz** [comment]
Ora è sistemato, però occhio se usi una o piú delle opzioni `--moveok`, `--moveko`, `--movework`, `--copyok`, `--copyko`: se ci sono due input con lo stesso nome di file, il secondo sovrascrive il primo nella directory di destinazione.

**Comment by spanezz** [comment]
Il commit precedente doveva invece riferirsi a #65, scusate
