### ISSUE TITLE
[dataset config] filter grib with missing key

### ISSUE THREAD

**Issue by brancomat** [ARPA-SIMC/arkimet#78]
I have a bunch of (too much) similar gribs, and the only way I have to differentiate them in different datasets is by the presence of the `marsType` key.

Testing the presence sounds easy (`proddef:GRIB:marsType=x`) but I'm unsure if there's a way to specify in the filter expression the absence of a key.

**Comment by spanezz** [comment]
Not at the moment. Feel free to turn this issue into a request to have this feature implemented.

**Comment by brancomat** [comment]
At the moment I don't think it's worth the effort, I'm closing the bug.
