### ISSUE TITLE
arki-query --summary con valori raggruppati per tipo di metadato

### ISSUE THREAD

**Issue by edigiacomo** [ARPA-SIMC/arkimet#8]
(Titolo fuorviante, ma non riesco proprio a sintetizzare la cosa)

Sarebbe utile avere un'opzione di `arki-query` che permettesse di elencare tutti i valori per ogni tipo di metadato.

Ad esempio:
```
$ arki-query --dump --group-by-type QUERY DATASET

SummaryItem:
    Origin:
        GRIB1(098, 000, 145)
    Product:
         GRIB1(098, 128, 187)
         GRIB1(098, 228, 024)
         ...
    Level:
         GRIB1(001)
     ...
SummaryStats:
    Count: 124
    Size: 24404
    Reftime: 2015-12-14T00:00:00Z to 2015-12-15T00:00:00Z
```

**Comment by spanezz** [comment]
Done: `arki-query --summary-short [--json] ...`

**Comment by edigiacomo** [comment]
Scusami Enrico, riapro la issue perché sarebbe utile averlo anche tra le richieste HTTP all'arki-server (come ti dicevo in chat il 25 gennaio 2016).

Ad esempio: `/dataset/NAME/summary?style=json&short=true` oppure `/dataset/NAME/summaryshort?style=json` (la seconda mi pare più omogenea con le opzioni da riga di comando).

Sto guardando come inserire la cosa in `ReaderServer` (`arki/dataset/http/server.cc`), ma mi pare di capire che si debba passare (lasciando le cose come stanno, cioè passando per `ProcessorMaker`) per una "rivisitazione" di `LegacyQueryParams::set_into`, in modo che venga usato non solo nel caso di `/query`, ma anche nel caso di `/summary`, etc.

Ci do un occhio io se non ti scoccia, al massimo se non riesco ti riconsegno la issue tra cocenti lagrime di delusione.
