### ISSUE TITLE
arki/dataset/local.cc does not remove "lock" file

### ISSUE THREAD

**Issue by brancomat** [ARPA-SIMC/arkimet#80]
We're finding a lot of "lock" empty files inside the dataset dirs.
It seems like the file is not deleted when released.
I'm labeling this as a question because I'm not sure if there's a reason behind this.

**Comment by spanezz** [comment]
It is intended: the presence of the file does not make the dataset locked, but the file is used as a well-known place to run locking functions.
The actual locking functions used are these ones: https://www.gnu.org/software/libc/manual/html_node/Open-File-Description-Locks.html

Is there something in the `lock` files that worry you?

I could document them. What would be a good place?

**Comment by brancomat** [comment]
> Is there something in the `lock` files that worry you?

After the explanation, not really. At the time of the `arki-check` problems I first noticed the files and I thought they could be a sign of problems in the locking functions, I was assuming that the file should have been deleted when the lock was released

Mentioning the `lock` file in the documentation sounds good but I really don't know where (meaning: I don't know where I'd go to search that kind of information).
I'm adding a mention in the arkiguide and I'm closing the bug since I have no better ideas. If @edigiacomo or others have some proposals, feel free to reopen the bug.
