### ISSUE TITLE
tar odimh5 dataset files by step

### ISSUE THREAD

**Issue by brancomat** [ARPA-SIMC/arkimet#86]
_disclaimer: @edigiacomo told me this has already been proposed years ago so I might be missing some information_

Our current offline/backup handling procedures perform rather poorly with a large amount of files, this is particularly evident with `odimh5` datasets (200ish files a day per dataset).
It would be awesome if (filesystem-wise) the `odimh5` file currently grouped in a subdir by the `step` parameter could be tarred in a single file.

This could be either a global dataset setting or something triggered by `archive age` via repack, suggestions are welcome.

To be clear: this should affect only how files are stored, the change should be transparent for clients.

**Comment by brancomat** [comment]
this has become a duplicate of issue #131

**Comment by spanezz** [comment]
Oh, I missed this when I opened #131. Tecnically, #131 is the duplicate of this one. Sorry about that.
