### ISSUE TITLE
arki-server http global summary not working

### ISSUE THREAD

**Issue by brancomat** [ARPA-SIMC/arkimet#87]
At one point, we used to do something like: `http://arkioss4.metarpa:8090/summary?style=json`
Now it doesn't work anymore saying: 
```
file .lua not found; tried: /etc/arkimet/qmacro
```
It's still working on single datasets (like: `http://arkioss4.metarpa:8090/dataset/boa/summary?style=json`) and we're using a loop on existing datasets as a sad workaround.

Here's when I copy&paste what @edigiacomo said hoping he'll chime in:
it seems that the server is considering the single dataset and the dataset root as the same thing (somewhere around [arki/runtime.cc:70](https://github.com/ARPA-SIMC/arkimet/blob/dac31781b3412d436233f98a450e2e2f6b442afa/arki/runtime.cc#L70) ).

`http://arkioss4.metarpa:8090/summary?qmacro=noop` gives a:
```
cannot parse /etc/arkimet/qmacro/noop.lua: /etc/arkimet/qmacro/noop.lua:4: Dataset  not found
```

**Comment by spanezz** [comment]
Correzione, riapro e riassegno a @brancomat per verifica
