### ISSUE TITLE
specifiche arki-check

### ISSUE THREAD

**Issue by brancomat** [ARPA-SIMC/arkimet#89]
Qui passo all'italiano perché è fondamentale capirsi bene :)

La issue #88 ha messo in luce alcune criticità: abbiamo alcuni dataset i cui tempi di check stanno salendo esponenzialmente e nel cercare di capire come mai con @edigiacomo è emerso che ci sono un po' di nebbie sulle specifiche di cosa dovrebbe fare `arki-check`, in particolare i dati contenuti dentro a `.archive`.

Al momento sui nostri server questo tipo di cartelle contengono:
 * la subdir `last` popolata e organizzata dal repack
 * una serie di sottodir con dati spostati da last, che vengono reindicizzati con un check e il summary viene spostato fuori, ovvero:
    `$dataset/.archive/qualcosa/summary` viene copiato come `$dataset/.archive/qualcosa.summary` permettendo ad un'`arki-query --summary` di accedere al summary anche nel caso la cartella venga spostata fuori linea

La domanda è: come si dovrebbe comportare `arki-check` in questo contesto?

Una proposta potrebbe essere ignorare le sottodir di `.archive` con un summary dal nome corrispondente  alla sottodir, ma magari avete idee migliori

Questa s'interseca pesantemente con la #88 perché la manpage di arki-check parla di rigenerare "outdated summaries" ma al momento non ci è chiarissimo come discrimini, quindi magari è un tema già affrontato in passato.

**Comment by edigiacomo** [comment]
Aggiungo: ci sono alcune operazioni lunghe che non hanno messaggi di debug, e.g. il vacuum fatto alla fine del fix e del repack.

**Comment by spanezz** [comment]
Ora che #88 è fatto propongo di mandarlo in produzione e vedere se ci sono comportamenti che non coincidono con i risultati attesi dalla documentazione; se ci sono comportamenti attesi che andrebbero aggiunti alla documentazione; se ci sono comportamenti che al momento non sono attesi ma che sarebbe il caso di avere.

arki-check non dovrebbe toccare gli archivi, a meno ché non siano stati pistolati manualmente. File spostati da un archivio alll'altro spostando sia i dati che i metadati assieme, dovrebbero semplicemente venire aggiunti al MANIFEST e per il resto lasciati stare. Ho visto che c'era un problema nell'ordinamento del repack nei dataset di tipo `simple`, l'ho commentato nel messaggio di chiusura di #88 e l'ho corretto. Vediamo se è risolutivo

**Comment by spanezz** [comment]
Lascierei questo issue aperto finché non aggiungo un logging di debug al vacuum, e con quello lo chiuderei, con l'idea che si possono aprire altri bug uno per ogni comportamento atteso/non atteso/desiderato e per ogni altra cosa che dovrebbe essere loggata.

**Comment by spanezz** [comment]
Mergiato in master anche il logging del vacuum.
