### ISSUE TITLE
Specifiche per il sistema di documentazione

### ISSUE THREAD

**Issue by edigiacomo** [ARPA-SIMC/arkimet#90]
@spanezz, premetto che è molto bello il sistema di documentazione che hai messo in piedi (#88).

Premetto pure che la risposta giusta alla presente issue sarebbe la creazione della label "dovevi svegliarti prima", ma dopo averci riflettuto un po' e aver chiacchierato con @brancomat proporrei di buttare giù un po' di specifiche per la documentazione. Non voglio dire di bloccare l'attuale lavoro di documentazione, ma semplicemente tenere aperta una discussione per poi eventualmente portare la doc da un sistema ad un altro.

I punti che a me premono sono:

1. Avere la documentazione generata tutta insieme, browsabile.
2. Documentazione integrata del codice e delle parte più "prosaica". Ad esempio, dalla descrizione di un tipo di dataset (documentazione "prosaica") avere dei link alla documentazione delle classi coinvolte.
3. Leggere la documentazione nei sorgenti senza compilazione.
4. Non dover mai dipendere da una compilazione "pesante" (e.g. il lungo `make check` di adesso, ma nemmeno la compilazione del codice C++) per leggere la documentazione generata.
5. Documentazione di come si scrive la documentazione, di cosa si deve documentare e come generare la documentazione. In altre parole: se usiamo un sistema già esistente, una parte del lavoro è già fatta.
6. Possibilità di auto-deploy: al markdown renderizzato da GitHub preferirei un sistema che la compila e la pubblica in modo indipendente da chi fa le commit.

A me viene in mente Doxygen (soprattutto per i punti 2 e 3), ma sono fondamentalmente agnostico: quello che mi preme è avere delle specifiche condivise.

**Comment by spanezz** [comment]
Ciao,

butto giú quello che mi viene in mente al volo.

L'idea di far evolvere i .md attuali in un qualcosa di integrato col
resto del codice, da sviluppatore, mi piace. Non so se, chi non
sviluppa il codice di arkimet, possa preferire una separazione tra un
manuale di uso e manutenzione e la documentazione del codice.

In teoria, posso organizzare la documentazione di doxygen in due sezioni
separate. Rimarrebbero i link alle classi in mezzo alla parte di uso e
manutenzione, che non so dire se diventerebbero un rumore fastidioso o
un link utile.


Per evitare di dover fare make check per generare la documentazione,
avevo già pensato stamattina, parlando con @brancomat, di cambiare il
doc/Makefile.am per generare un file .json con la documentazione
estratta dai test, e committarlo, il modo tale che la documentazione
possa essere comunque buildata senza avere la test suite compilata.


Doxygen mi va bene: ho scelto di generare i markdown perché era il modo
piú veloce che mi è venuto in mente per rispondere all'esigenza di
sapere cosa succedeva al check/repack. Ora che quell'esigenza è risolta,
possiamo pensare a come strutturare la documentazione di tutto.

> 6. Possibilità di auto-deploy: al markdown renderizzato da GitHub
> preferirei un sistema che la compila e la pubblica in modo
> indipendente da chi fa le commit.

C'è un modo di dire a github di far girare doxygen e pubblicare la
documentazione?


Enrico

-- 
GPG key: 4096R/634F4BD1E7AD5568 2009-05-08 Enrico Zini <enrico@enricozini.org>

**Comment by edigiacomo** [comment]
Grazie @spanezz!

In effetti, io vedo la cosa da un punto di vista un po' intermedio tra uno sviluppatore e un utilizzatore di arkimet: quindi, su quanto (e magari su quali sezioni) avere netta la distinzione tra codice e utilizzo o meno vorrei che si esprimessero anche gli altri. Però personalmente non vorrei bruciarmi la possibilità di avere link da una all'altra.

Sugli altri temi:

* Ma quindi i file `JSON` li estrarresti direttamente dal codice sorgente?
* [Doxygen supporta markdown dalla versione 1.8][1] (ma non l'ho mai usato), quindi potremmo pure integrarvi la documentazione.
* Pare che qualcuno ce l'abbia fatta a pubblicare doc Doxygen su github [usando gh-pages e Travis][2], ma potremmo pure farla in casa (e qui @brancomat mi picchia) con una procedura che periodicamente ricompila la doc e la pusha.

Non vorrei date l'impressione di essere un fanatico di Doxygen, ma semplicemente è l'unico generatore di documentazione che ho conosco :)

[1]: http://www.stack.nl/~dimitri/doxygen/manual/markdown.html
[2]: https://gist.github.com/vidavidorra/548ffbcdae99d752da02

**Comment by brancomat** [comment]
Sono un po' troppo ignorante sul tema per dare contribuiti sensati, ho due punti di vista separati che valgono il giusto:

Da end user, il punto d'arrivo che mi piacerebbe sarebbe una doc inclusa nel pacchetto come man page e (più estesa) come html locali che possano essere letti _anche_ su github (che sia md renderizzato direttamente da github o altro). Magari citando esplicitamente la doc html locale dalla manpage anche se è poco usuale.

Da sistemista limitare le dipendenze legate alla doc a doxygen mi piace più che altro perché lo usiamo per un buon 80% degli altri progetti e avendo già qualche competenza interna (anche se non mia) aiuta.

L'auto deploy al momento lo vedo come un non problema (o a bassissima priorità), siamo passati dal non avere documentazione su certi temi a porci il problema di come autoaggiornarla... l'importante è che ci sia (as in: inclusa nella dist in forma compilata)  poi se si tratta di tirare un make in più o qualche altro comando mistico a mano per rigenerarla periodicamente al momento mi pare comunque accettabile

**Comment by spanezz** [comment]
Intanto ho committato nel branch issue90 una patch per poter generare la documentazione senza dover fare `make check`, ora ragiono di doxygen

**Comment by edigiacomo** [comment]
Grazie Enrico!

Visto che la issue non è bloccante per la produzione e quindi immagino che verrà scodata con calma, chiedo a @dcesari e @pat1 se hanno cose da aggiungere alle specifiche prima di affrontare la issue - e quindi se/come ragionare su doxygen.

**Comment by spanezz** [comment]
On Fri, Jun 09, 2017 at 12:35:49AM -0700, Emanuele Di Giacomo wrote:

> * Ma quindi i file `JSON` li estrarresti direttamente dal codice sorgente?

Preferisco farli stampare dalla test suite come ora: mi piace che siano
integrati nel codice, e ho sempre paura che se invece ci metto un
commento di fianco, il commento prima o poi si perda. Inoltre non ho
idea di come in doxygen commentare una chiamata a funzione in modo da
poterla trovare bene dopo: al momento posso filtrare facilmente la
documentazione in base al nome completo del test, facendo cose tipo:
{{testdoc("arki_dataset_simple_maintenance_grib_plain.check_*")}}

Però posso (e l'ho fatto) fare cache della documentazione generata dalla
test suite, e committare la cache in git. In questo modo il Makefile non
dovrebbe piú cercare di far build di arki-test col make check se
testdata.json già esiste, e cercare di rebuildarlo solo quando vede che
arki-test è piú nuovo.

Se non lo fa, è un difetto nel Makefile che devo correggere.


Enrico

-- 
GPG key: 4096R/634F4BD1E7AD5568 2009-05-08 Enrico Zini <enrico@enricozini.org>

**Comment by dcesari** [comment]
Mi inserisco in ritardo:

* Pare che qualcuno ce l'abbia fatta a pubblicare doc Doxygen su github usando gh-pages e Travis, ma potremmo pure farla in casa (e qui @brancomat mi picchia) con una procedura che periodicamente ricompila la doc e la pusha.

Io questo l'ho fatto per il progettino [nwpconf](https://github.com/ARPA-SIMC/nwpconf) alla maniera casalinga: mi tengo un checkout separato del ramo gh-pages e faccio alla bisogna un make; rsync -a doc/html path/to/gh-pages; cd path/to/gh-pages; git commit -a; git push; è un po' macchinoso ma funziona con poco setup.

Supporto la proposta delle pagine in markdown-doxygen, che tra l'altro, se sono sotto git, lasciano aperta la possibilità di sfogliarle in github, che sia o meno pubblicato doxygen online.

Riguardo i link alle classi in mezzo alla parte di uso e manutenzione li ritengo sicuramente utili.

**Comment by dcesari** [comment]
Un'alternativa per pubblicare doxygen automaticamente è questo sito https://codedocs.xyz/, scoperto sulla mailing list di doxygen, io l'ho provato con https://codedocs.xyz/dcesari/fortrangis/ ricordo che è stato abbastanza semplice integrarlo, però al momento il nostro proxy lo blocca con un messaggio terribile. E poi non è garantito che non diventi un servizio a pagamento.

**Comment by brancomat** [comment]
ho un blocco websense per "Elevated exposure" su https://codedocs.xyz/ 

> Elevated Exposure: Sites that camouflage their true nature or that include elements suggesting latent malicious intent.

Questo conferma la mia teoria che in informatica la documentazione è considerata una cosa malvagia

**Comment by dcesari** [comment]
Si, infatti ho accertato che esiste ancora navigandoci dal cellulare.

**Comment by spanezz** [comment]
Aggiornamento su questo tema: per wreport e dballe ho sperimentato con abbastanza gioia un sistema di documentazione unificato basato su [sphinx](https://www.sphinx-doc.org/) e [breathe](https://breathe.readthedocs.io).  L'output è qui: [wreport](https://arpa-simc.github.io/wreport/) e [dballe](https://arpa-simc.github.io/dballe/).

Mi sono trovato molto bene, e a questo punto propongo di fare lo stesso in arkimet

**Comment by edigiacomo** [comment]
Per me benissimo!

**Comment by brancomat** [comment]
ok anche per me

**Comment by spanezz** [comment]
Ho unificato la documentazione esistente qui: https://arpa-simc.github.io/arkimet/

Il lavoro è al momento nel branch `sphinx`, al momento temporaneo, di cui poi farò merge una volta che `issue177` sarà in master.

**Comment by edigiacomo** [comment]
@spanezz questa issue può essere chiusa in quanto è stato fatto il merge, giusto?

**Comment by spanezz** [comment]
Direi di sí
