### ISSUE TITLE
arki-check: inconsistenze nella gestione dei file "MANIFEST"

### ISSUE THREAD

**Issue by brancomat** [ARPA-SIMC/arkimet#91]
(testato su archivi odimh5 con arkimet v1.2-1 su fedora 20)

con una situazione di archivio tipo:
```odimSPC/.archive/odimSPC-20150201```

 * se non esiste il file `MANIFEST` viene completamente ignorata la cartella (con o senza `-f`)
 * se il file `MANIFEST` esiste ed è più recente dei file `.metadata`,  viene comunque segnalata la necessità del rescan o effettuato il rescan dei file (con `-f`). Al termine del rescan della sezione passa alla successiva ma NON aggiorna il file MANIFEST (non so se lo avrebbe fatto al termine perché dopo una decina di sezioni va in out of memory - cosa che magari tracciamo in issue separata)

ho difficoltà a riprodurre quest'ultimo punto fuori dal server operativo: un'intera sezione sono una 40ina di giga quindi ho isolato un giorno solo, e lì arki-check pare funzionare (tranne quando manca il `MANIFEST`), magari dimmi qualcosa a me o a @edigiacomo  quando ci lavori che ti mostriamo la situazione su server operativo

**Comment by spanezz** [comment]
Gli archivi presi in considerazione sono o i file `.summary` per conto loro (archivi offline) o le directory che contengono un manifest: il controllo è [qui](https://github.com/ARPA-SIMC/arkimet/blob/master/arki/dataset/archive.cc#L39) e l'enumerazione degli archivi è [qui](https://github.com/ARPA-SIMC/arkimet/blob/master/arki/dataset/archive.cc#L109)

**Comment by spanezz** [comment]
Un motivo per riscansionare un file anche se il suo `.metadata` è piú vecchio del `MANIFEST` e i suoi data son piú vecchi del `.metadata` è se il `MANIFEST` non contiene quel segmento.
La riscansione di un dataset, a prescindere da quanto grande, NON dovrebbe andare out of memory: quello è un bug, e brutto.
Se ci arrivasse in fondo, scriverebbe il `MANIFEST`. Posso modificare il codice per aggiornare il `MANIFEST` dopo ogni segmento riscansionato con successo.

**Comment by brancomat** [comment]
Non mi è chiaro il discorso sulla presenza del `MANIFEST`: se non mi sfugge qualcosa (non ho scritto io le procedure) storicamente il modo che abbiamo per creare sezioni di archivio è spostare una selezione di dati da `.archive/last` ad un'altra dir `.archive/${qualcosa}`.

Al termine dell'operazione viene lanciato un arki-check e alla fine l'unica altra operazione manuale è un `cp .archive/${qualcosa}/summary .archive/${qualcosa}.summary`. Sono abbastanza certo che i MANIFEST che trovo dentro alle singole sezioni li abbia creati un arki-check e che non fossero pre-esistenti.

Per chiarire meglio: non sto parlando del `${dataset}/.archive/last/MANIFEST` ma dei`${dataset}/.archive/${qualcosa}/MANIFEST`.
In questo senso sì, al di là del memory leak mi parrebbe più corretto che aggiornasse il singolo file MANIFEST alla fine dell'analisi di quella dir (abbiamo archivi enormi e ci sono N motivi per cui può non arrivarci in fondo alla prima botta e ripartire sempre dall'inizio non è il massimo)

**Comment by spanezz** [comment]
Giusto. Visto come vengono creati gli archivi non-`last`, il controllo dell'esistenza del MANIFEST non è corretto, e va cambiato perché sia sufficiente la presenza di una directory.

**Comment by brancomat** [comment]
(scopro ora per caso che era già successo qualcosa di simile nella #17)

**Comment by spanezz** [comment]
Aggiornamento, ho trovato e tappato un po' di memory leak, poi testando questo vediamo se ne troviamo degli altri.

**Comment by brancomat** [comment]
Ora la situazione mi pare corretta e consistente con la documentazione.
