### ISSUE TITLE
arki-check: inconsistenze nel riordino dei dati

### ISSUE THREAD

**Issue by brancomat** [ARPA-SIMC/arkimet#92]
log allegati, ma riassumendo, nella sezione `.archive` di un dataset ondisk2 :

- `arki-check` segnala che praticamente tutti i file in `.archive/last` "contains deleted data or data to be reordered"
- `arki-check -f` dice "repacked" per gli stessi file
- `arki-check` tirato immediatamente dopo il repack segnala gli stessi identici file "contains deleted data or data to be reordered", eccetera

Forse rilevante: le segnalazioni riguardano tutte i dati presenti in sottodir di `.archive` e non nella dir principale

Purtroppo come per il #91 viste le dimensioni del dataset faccio fatica a creare un test case riproducibile su server non operativo.

[arkicheckcosmo5Mita.txt](https://github.com/ARPA-SIMC/arkimet/files/1074418/arkicheckcosmo5Mita.txt)

**Comment by spanezz** [comment]
In https://github.com/ARPA-SIMC/arkimet/blob/issue92/testtar ho prototipato una versione modificata di tar per fare versioni di test dei dataset. Il tar risultante conterrà tutto il contenuto del dataset, eccetto i dati salvati nei segmenti. Quando con `testtar` si scompatta uno di quei tar, i segmenti risultanti avranno la lunghezza giusta, ma non occuperanno spazio su disco e conterranno solo zeri.
Questo permette di riprodurre problemi di manutenzione, a patto di non usare `arki-check --accurate`.
Con questo sono riuscito a riprodurre il problema dell'ordinamento sul mio computer di lavoro, ora vedo se capisco perché succede.
Quel `testtar` mi sembra interessante: vale la pena di pacchettizzarlo come `src/arki-testtar` e installarlo assieme agli altri arki-tool?

**Comment by brancomat** [comment]
Direi che potebbe essere comodo... per capire meglio: questo permetterebbe di riprodurre più comodamente e di testare problemi relativi a tutte le arki-check-dinamiche a valle della lettura del dato stesso (quindi nel caso degli archives subordinato almeno alla presenza dei `.summary` e `.metadata` associati al singolo file (dir per gli odimh5)?

**Comment by spanezz** [comment]
@brancomat esatto

**Comment by spanezz** [comment]
Dovrebbe essere risolto in 4fd913adf2fa0db431f1760017902a5fac5092da

**Comment by brancomat** [comment]
Confermo, non segnala più problemi di ordinamento.
