### ISSUE TITLE
Split delete age and repack operations in arki-check

### ISSUE THREAD

**Issue by dcesari** [ARPA-SIMC/arkimet#94]
Currently "lightweight" operations such as the deletion of files according to `delete age` can be performed only with `arki-check -f` implying also a repack, which may be a "heavyweight" operation if the dataset really needs repacking. It would be thus helpful to have specific options in `arki-check` to perform just the `delete age` (and possibly other lightweight maintenance operations) without a repack, or something like `--op-list=CDRA...` to select the operations to be performed.

**Comment by spanezz** [comment]
This is now possible with `arki-check --remove-old`. `--offline`, `--online`, `--filter` all apply. By default, only online data are considered for removal.
