### ISSUE TITLE
Add logrotate in spec file for arki-server logs

### ISSUE THREAD

**Issue by edigiacomo** [ARPA-SIMC/arkimet#98]
Log files in `/var/log/arkimet/` are not rotated. The packaged version could be shipped with a default logrotate configuration file.

**Comment by dcesari** [comment]
[I seize the ball to leap](https://translate.google.com/#it/en/cogliere%20la%20palla%20al%20balzo) :-) to ask: does arki-server tolerate a log rotation? i.e. moving the log away and maybe compressing it, and/or would something like

```
    postrotate
        /usr/bin/killall -HUP arki-server
    endscript
```
help this process?

**Comment by brancomat** [comment]
Done in b2b8bc7 , but I have a couple of doubts:
  @spanezz : do arki-server need some postrotate magic after the logrotate? I noticed that `apache2` logrotate conf has a reload in the postrotate section (I see now @dcesari asked a similar thing)
 @edigiacomo: 
  - I couldn't find a clever way to match the logdir definition in `arkimet.service` and the one in the logrotate conf. I ended up adding a warning in `arkimet.service` (maybe it's not really an issue since logrotate conf has the `missingok` option)
 - please review logrotate conf (it's similar to the apache2 one)

**Comment by edigiacomo** [comment]
Ahahah, you're too fast, I've made a branch (issue98) but I was too slow to push it :) I'll delete the branch and review your code, thanks.

> do arki-server need some postrotate magic after the logrotate? I noticed that apache2 logrotate conf has a reload in the postrotate section (I see now @dcesari asked a similar thing)

The default configuration of `arki-server` use a [`WatchedFileHandler`][1], that doesn't need any reload of the daemon.

> I couldn't find a clever way to match the logdir definition in arkimet.service and the one in the logrotate conf. I ended up adding a warning in arkimet.service (maybe it's not really an issue since logrotate conf has the missingok option)

I think it's the same in `httpd`: if you change the `CustomLog` directory in `httpd.conf` you must properly change the logrotate config file but - you're right - with the `missingok` you can leave the logrotate config file unchanged.

[1]: https://docs.python.org/3.6/library/logging.handlers.html#watchedfilehandler

**Comment by dcesari** [comment]
Great thanks, I'll start rotating right now.

**Comment by edigiacomo** [comment]
1. `size 100M` and `rotate 52` means that we keep at most 1 file of 100M and 51 of 100M compressed. If it's good for the sysadmin, [good shirt everybody][1] :)
2. I think `create 0600 root root` it's useless (`WatchedFileHandler` will recreate the file after rotation) but could be dangerous too (`arkimet` user cannot write in a file owned by `root` and with `0600` mode).

[1]: https://www.youtube.com/watch?v=Ssvb89JRVkM

**Comment by edigiacomo** [comment]
In ee37d86 I wrote a generic logrotate config (the behaviour heavily depends on logrotate defaults): customizations can be made in the individual servers - and they will not be overwritten on package update.
