### ISSUE TITLE
Improve (or define) "user" setting for arki-server

### ISSUE THREAD

**Issue by brancomat** [ARPA-SIMC/arkimet#99]
As @dcesari painfully knows, right now the user of the arki-server is hard coded and changing it it's not straightforward.
Moreover, we're using as a default a `arkimet` user without checking if it's actually present on the system.

I'd start with a list of desiderata to see how we can integrate a more standard approach .
Right now, for what I know:
- at SIMC, we generally need an existing `arkimet` user but _with a given uid and particular groups_ (this could complicate a create-if-needed approach)
- it should be easier to change the daemon user
- rpm doesn't allow things like user prompts in postinstall or `dpkg-reconfigure`

Maybe the simpler solution would be the "Dynamic allocation" described in https://fedoraproject.org/wiki/Packaging:UsersAndGroups, being aware that:
 - if `arkimet` user doesn't already exist in SIMC production systems with the correct groups, uid and gids, is the sysadmin fault 😢 
 - it's the package that decides the running user (for example changing the apache user it's not straightforward nor it's supposed to be)

**Comment by dcesari** [comment]
A related problem is that, with systemd, the username is hardcoded in `/usr/lib/systemd/system/arkimet.service` and systemd does not allow to override it from the environment, e.g. from `/etc/sysconfig/arkimet`, so if a user different than `arkimet` is used, it is reset to `arkimet` on any rpm update, but I am afraid there is not much we can do here.

**Comment by brancomat** [comment]
> it is reset to arkimet on any rpm update

This can (probably) be solved in specfile by changing:
```
%{_unitdir}/%{name}.service
```
to
```
%config(noreplace) %{_unitdir}/%{name}.service
```
But I don't know if it's a good idea (if we change something substantial in the unit file you won't see it)

**Comment by edigiacomo** [comment]
Reading the documentation(see section _Example 2. Overriding vendor settings_ in `man 5  systemd.unit`), it seems that there are two ways to override the default unit configuration `/lib/systemd/system/$UNIT.service`:

* `/etc/systemd/system/$UNIT.service` completely overrides the default
* `/etc/systemd/system/$UNIT.service.d/$NAME.conf` that add/edit the some values (the `$NAME.conf` are evaluated in alphabetical order)

Then, if you want to change the user only:

```
# mkdir -p /etc/systemd/system/arkimet.service.d
# cat  <<EOF > /etc/systemd/system/arkimet.service.d
[Service]
User=johnnypomodoro
EOF
```

I have only read the docs but I haven't tried it - @dcesari could you please test it?

**Comment by edigiacomo** [comment]
Update: I changed the user in `/etc/systemd/system/arkimet.service.d/user.conf` and it works 🍺

**Comment by brancomat** [comment]
So, a quick recap:
 - changing the user of the arki-server should be done following @edigiacomo suggestions
 - since for a number of reasons we're not unanimous on whether arkimet should automatically create an user, I added a warning in the specifle: if _at the first installation_ the `arkimet` user is not present on the system, there's a warning that the arki-server can't be run without additional configuration.

(by the way:  http://meinit.nl/rpm-spec-prepostpreunpostun-argument-values is an interesting link for detecting first installations, updates and uninstallations in specfiles)

I'm closing the issue, anybody feel free to reopen it if there's something missing or to clarify

**Comment by dcesari** [comment]
A bit late, I confirm the suggestion works for me too.

**Comment by brancomat** [comment]
> Then, if you want to change the user only:
> 
> \# mkdir -p /etc/systemd/system/arkimet.service.d
> \# cat  <<EOF > /etc/systemd/system/arkimet.service.d/user.conf
> [Service]
> User=johnnypomodoro
> EOF

resuming the thread to pin a cleaner way to do this:
```
systemctl edit arkimet.service
```
this opens a editor and does what @edigiacomo did but automagically

the "replace the whole file" flavour is:
```
systemctl edit --full <service-name>
```
(I'm unsure whether a `systemctl daemon-reload` is also needed)

**Comment by edigiacomo** [comment]
It seem that `systemctl daemon-reload` is automatically executed. From `man systemctl`:

>```
> edit NAME...
>     [...]
>    After the units have been edited, systemd configuration is reloaded
>    (in a way that is equivalent to daemon-reload).
>```
